#!/bin/sh

set -e

# Load lts.conf variables
. /usr/share/ltsp/ltsp_config

if boolean_is_true "${USE_NFS_HOMES}" ; then
  if [ "${PAM_TYPE}" = "open_session" ]; then
    # rpc.gssd needs a user principal on netboot devices as they do not have
    # machine principals
    if [ ! -f "/etc/krb5.keytab" ]; then
      TMP_KRB5CCNAME=$(echo $KRB5CCNAME | sed -e 's/^FILE://')
      install -o root -g root -m 600 "$TMP_KRB5CCNAME" /tmp/krb5cc_0

      service idmapd restart  || service idmapd start
      service gssd restart    || service gssd start
    fi

    # NSS needs to be working so that we get the home directory with getent.
    # For LTSP thin client and fat clients this comes most probably from
    # libnss-extrausers that gets populated during PAM auth.
    HOME=$(getent passwd $PAM_USER | awk -F: '{ print $6 }')

    # Request a remote directory for the user (three second timeout, may fail)
    { echo "$PAM_USER" | nc -w 3 "$SERVER" 907; } || true

    # Create a local directory for the user and mount it using nfs4+krb5
    mkdir -p ${HOME}
    mount -t nfs4 -o sec=krb5 ${SERVER}:${HOME} ${HOME}
  fi
else
  HOME=$(getent passwd $PAM_USER | awk -F: '{ print $6 }')
  mkdir -p ${HOME}
  chown $PAM_USER: ${HOME}
fi

exit 0
