#!/bin/sh

set -eu

case "$(cat /etc/puavo/hosttype)" in
    laptop)
        break
        ;;
    *)
        exit 0
        ;;
esac

case "$(echo $LANG | cut -c 1-2)" in
  fi)
    sharepath='yhteiset'
    ;;
  sv)
    sharepath='delade_filer'
    ;;
  *)
    sharepath='share'
    ;;
esac

homedirserver="homedir.$(cat /etc/puavo/domain)"
gvfsroot="${HOME}/.gvfs"

gvfs-mount "smb://${homedirserver}/${USER}" || true
gvfs-mount "smb://${homedirserver}/share/${sharepath}/$(id -gn)" || true

usermountdir="smb-share:server=${homedirserver},share=${USER}"
sharemountdir="smb-share:server=${homedirserver},share=share"

ln -sf "${gvfsroot}/${usermountdir}" "${HOME}/.puavo-sharedir.user"
ln -sf "${gvfsroot}/${sharemountdir}" "${HOME}/.puavo-sharedir.share"
