# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{puavo-client}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jouni Korhonen"]
  s.date = %q{2011-10-19}
  s.description = %q{Simple ruby wrapper for the Puavo API}
  s.email = %q{puavo@opinsys.fi}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "COPYING",
    "README.md",
    "Rakefile",
    "VERSION.yml",
    "lib/puavo-client.rb",
    "lib/puavo/client/api/base.rb",
    "lib/puavo/client/api/devices.rb",
    "lib/puavo/client/api/groups.rb",
    "lib/puavo/client/api/organisation.rb",
    "lib/puavo/client/api/schools.rb",
    "lib/puavo/client/api/users.rb",
    "lib/puavo/client/base.rb",
    "lib/puavo/client/device.rb",
    "lib/puavo/client/group.rb",
    "lib/puavo/client/model.rb",
    "lib/puavo/client/organisation.rb",
    "lib/puavo/client/school.rb",
    "lib/puavo/client/user.rb",
    "puavo-client.gemspec"
  ]
  s.homepage = %q{https://github.com/opinsys/puavo-client}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple ruby wrapper for the Puavo API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

