#!/bin/bash
#
# ##############################################################################
#
# Copyright (C) 2014 Opinsys Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# ##############################################################################
#
# Author: Tuomas Räsänen <tuomasjjrasanen@tjjr.fi>

set -eu

. "${RESTRICTED_PKG_LIBDIR}/common"

on_exit()
{
    local exitval=$?
    set +e

    rm -f "${upstream_pack}.tmp"

    exit $exitval
}

package=$1

custom_script="${RESTRICTED_PKG_SHAREDIR}/${package}/download"

packagedir=$(packagedir "$package")
upstream_pack_md5sum=$(upstream_pack_md5sum "$package")
upstream_pack="${packagedir}/upstream.pack"

cache_path=$(upstream_pack_cache_path "$package")

mkdir -p "$packagedir"

if [ -e "$cache_path" -a ! "$cache_path" -ef "$upstream_pack" ]; then
  cp -u "$cache_path" "$upstream_pack"
fi

echo "${upstream_pack_md5sum}  ${upstream_pack}" \
    | md5sum --check --status 2>/dev/null && {
    echo "I: upstream pack is already in place and has a correct checksum" >&2
    exit 0
}

url_file="${RESTRICTED_PKG_SHAREDIR}/${package}/upstream.pack.url"

trap on_exit EXIT

if [ -x "${custom_script}" ]; then
    "${custom_script}" "${url_file}" "${upstream_pack}.tmp" || {
      echo "E: package downloader returned an error!"; exit 1;
    }
else
    wget \
        --no-use-server-timestamps \
        --no-verbose \
        --no-check-certificate \
        --no-cookies \
        --input-file "${url_file}" \
        --output-document "${upstream_pack}.tmp"
fi

if [ ! -f "${upstream_pack_md5sum}.nocheck" ]; then
  echo "${upstream_pack_md5sum}  ${upstream_pack}.tmp" \
      | md5sum --check --status 2>/dev/null || {
      echo "E: downloaded upstream pack has incorrect checksum" >&2
      exit 1
  }
fi

mv "${upstream_pack}.tmp" "${upstream_pack}"

exit 0
