use Time::HiRes qw(usleep);
use Mojo::Base 'basetest';
use testapi;

sub toggle_secure_boot_and_reboot {
  record_info('UEFI', 'Toggling SecureBoot state');

  send_key('down', wait_screen_change => 1);  # skip language option
  send_key('ret',  wait_screen_change => 1);  # enter Device Manager

  send_key('down', wait_screen_change => 1);  # move down to
  send_key('down', wait_screen_change => 1);  #   Secure Boot Configuration
  send_key('ret',  wait_screen_change => 1);  # enter it

  send_key('down', wait_screen_change => 1);  # move to Attempt Secure Boot
  send_key('spc',  wait_screen_change => 1);  # toggle it off
  send_key('esc',  wait_screen_change => 1);  # escape the dialog
  send_key('esc',  wait_screen_change => 1);  # escape
  send_key('esc',  wait_screen_change => 1);  # escape

  send_key('down', wait_screen_change => 1);  # move down to
  send_key('down', wait_screen_change => 1);  #   Continue
  send_key('down', wait_screen_change => 1);  # and
  send_key('ret',  wait_screen_change => 1);  # reboot

  send_key('ret',  wait_screen_change => 1);  # confirm reset
}

sub enroll_mok {
  send_key('spc',  wait_screen_change => 1);  # enter MOK management
  send_key('down', wait_screen_change => 1);  # Enroll MOK
  send_key('ret',  wait_screen_change => 1);

  # there might be two keys to view, skip them
  send_key('down', wait_screen_change => 1);
  # sleep 1; # waiting for screen change seems to be ineffective
  send_key('down', wait_screen_change => 1);
  # sleep 1;
  send_key('ret',  wait_screen_change => 1);  # continue

  # enroll the key(s): go down and select "Yes"
  send_key('down', wait_screen_change => 1);
  send_key('ret',  wait_screen_change => 1);  # Yes

  # password: 0
  send_key('0',    wait_screen_change => 0);  # the password is invisible
  send_key('ret',  wait_screen_change => 1);
  send_key('ret',  wait_screen_change => 1);  # reboot
}

sub run {
  select_console 'sut';

  # Press F2 every second until boot menu appear for maximum 5 minutes.
  # If the boot menu does not appear, this test fails.
  send_key_until_needlematch('bios', 'f2', 120);
  record_info('UEFI', 'BIOS setup reached, turning off Secure Boot...');
  toggle_secure_boot_and_reboot();

  # Wait until the disk installer UI shows up.
  assert_screen('darkdm', timeout => 300);
  record_info('Puavo', 'DarkDM reached, expecting reboot...');

  # The installer will detect missing MOK keys and Secure Boot being off,
  # which causes it to reboot back into firmware setup.
  assert_screen('bios', timeout => 300);
  record_info('UEFI', 'BIOS setup reached, turning Secure Boot back on...');
  toggle_secure_boot_and_reboot();

  # Enroll the device-specific MOK keys generated by Puavo.
  assert_screen('shim', timeout => 60);
  record_info('UEFI', 'SHIM reached, enrolling MOK keys...');
  enroll_mok();

  assert_screen('darkdm', timeout => 300);
  record_info('Puavo', 'DarkDM reached, checking Secure Boot and TPM...');

  # Switch keyboard layout to US.
  type_string('kbd us');
  send_key('ret', wait_screen_change => 1);

  # Switch to a new tmux console where we can type commands.
  send_key('ctrl-b', wait_screen_change => 1);
  send_key('c',      wait_screen_change => 1);

  assert_script_run(q{dmesg | grep -q 'Secure boot enabled'}, timeout => 30);
  record_info('Puavo', 'Secure Boot enabled');

  assert_script_run('grep -q 2 /sys/class/tpm/tpm0/tpm_version_major',
                    timeout => 30);
  type_string('ls -la /dev/tpm*');
  send_key('ret', wait_screen_change => 1);
  record_info('Puavo', 'TPM 2.x exists');

  # Return back to the primary console for the next test.
  send_key('ctrl-b', wait_screen_change => 1);
  send_key('0',      wait_screen_change => 1);
}

sub test_flags {
  return { fatal => 1, milestone => 1 };
}

1;
