use Time::HiRes qw(usleep);
use Mojo::Base 'basetest';
use testapi;

sub run {
    select_console 'sut';

    # Press F2 every second until boot menu appear for maximum 5 minutes.
    # If the boot menu does not appear, this test fails.
    send_key_until_needlematch('boot-menu', 'f2', 120);
    record_info('UEFI', 'Boot menu reached, turning off Secure Boot...');

    # Turn off Secure Boot:
    send_key('down', wait_screen_change => 1); # Skip the first boot option
    send_key('ret', wait_screen_change => 1);  # Select firmware setup

    assert_screen('bios', timeout => 10);
    record_info('UEFI', 'Firmware setup reached, turning off Secure Boot...');

    send_key('down', wait_screen_change => 1); # Skip language option
    send_key('ret', wait_screen_change => 1);  # Enter Device Manager

    send_key('ret', wait_screen_change => 1);  # Secure Boot Configuration

    send_key('down', wait_screen_change => 1); # Move down to Attempt Secure Boot
    send_key('spc', wait_screen_change => 1);  # Toggle it off
    send_key('esc', wait_screen_change => 1);  # Escape the dialog

    send_key('esc', wait_screen_change => 1);  # Escape
    send_key('esc', wait_screen_change => 1);  # Escape
    send_key('esc', wait_screen_change => 0);  # Escape

    send_key('down', wait_screen_change => 1);  # Move down to Continue
    send_key('down', wait_screen_change => 1);  # Move down to Continue
    send_key('down', wait_screen_change => 1);  # Move down to Continue
    send_key('ret', wait_screen_change => 1);   # Reboot!

    send_key('ret', wait_screen_change => 1);   # Confirm reset

    # Give the firmware a moment
    sleep 1;

    send_key('ret', wait_screen_change => 1); # Select the first boot option

    # Wait until the disk installer UI shows up
    assert_screen('darkdm', timeout => 300);
    record_info('Puavo', 'DarkDM reached, expecting reboot...');
   
    # The installer will detect missing MOK keys and Secure Boot being off, which causes it to reboot back into firmware setup
    assert_screen('boot-menu', timeout => 120);
    record_info('UEFI', 'Boot menu, turning on Secure Boot...');

    # Toggle Secure Boot back on:
    send_key('down', wait_screen_change => 1); # Skip the first boot option
    send_key('ret', wait_screen_change => 1);  # Select firmware setup

    assert_screen('bios', timeout => 10);
    record_info('UEFI', 'Firmware setup reached, turning on Secure Boot...');

    send_key('down', wait_screen_change => 1); # Skip language option
    send_key('ret', wait_screen_change => 1);  # Enter Device Manager

    send_key('ret', wait_screen_change => 1);  # Secure Boot Configuration

    send_key('down', wait_screen_change => 1); # Move down to Attempt Secure Boot
    send_key('spc', wait_screen_change => 1);  # Toggle it off
    send_key('esc', wait_screen_change => 1);  # Escape the dialog

    send_key('esc', wait_screen_change => 1);  # Escape
    send_key('esc', wait_screen_change => 1);  # Escape
    send_key('esc', wait_screen_change => 0);  # Escape

    send_key('down', wait_screen_change => 1); # Move down to Continue
    send_key('down', wait_screen_change => 1); # Move down to Continue
    send_key('down', wait_screen_change => 1); # Move down to Continue
    send_key('ret', wait_screen_change => 1);  # Reboot

    send_key('ret', wait_screen_change => 1);  # Confirm reset

    # Enroll the device-specific MOK keys generated by Puavo
    assert_screen('shim', timeout => 60);
    record_info('UEFI', 'SHIM reached, enrolling MOK keys...');

    send_key('spc', wait_screen_change => 1);  # Confirm we want to enter MOK management
    send_key('down', wait_screen_change => 1); # Go to "Enroll MOK"
    send_key('ret', wait_screen_change => 1);  # Enroll MOK

    # There might be two keys to view, skip them
    send_key('down', wait_screen_change => 0);
    sleep 1; # Waiting for screen change seems to be ineffective
    send_key('down', wait_screen_change => 0);
    sleep 1;
    send_key('ret', wait_screen_change => 1); # Continue

    # Enroll the key(s): Go down and select 'Yes'
    send_key('down', wait_screen_change => 1); 
    send_key('ret', wait_screen_change => 1);  # Yes

    # Password: 0
    send_key('0', wait_screen_change => 0); # The password is invisible
    send_key('ret', wait_screen_change => 1);

    send_key('ret', wait_screen_change => 1); # Reboot

    assert_screen('darkdm', timeout => 300);
    sleep 30;
    record_info('Puavo', 'DarkDM reached, checking Secure Boot and TPM...');

    # Switch keyboard layout to US
    type_string("kbd us");
    send_key('ret', wait_screen_change => 1);
    sleep 2;

    # Switch to a new tmux console where we can type commands
    send_key('ctrl-b');
    send_key('c');
    sleep 2;

    assert_script_run('dmesg | grep -q "Secure boot enabled"', timeout => 30);
    record_info('Puavo', 'Secure Boot enabled');

    assert_script_run('cat /sys/class/tpm/tpm0/tpm_version_major | grep -q 2', timeout => 30);
    type_string("ls -la /dev/tpm*");
    send_key('ret');
    sleep 1;
    record_info('Puavo', 'TPM 2.x exists');

    # Return back to the primary console for the next test
    send_key('ctrl-b');
    send_key('0');
    sleep 2;
}

sub test_flags {
    return { fatal => 1, milestone => 1 }; # always_rollback => 1
}

1;
