#!/bin/bash
set -eu

usage() {
  echo "Usage: $0 <output-directory>" >&2
  exit 1
}

if [[ $# -ne 1 ]]; then
  usage
fi

output_directory=$1

script_directory=$(dirname "$0")
configurators_directory="${script_directory}/../configurators/"

install_configurator() {
  local configurator_name=$1
  local configurator_directory="${configurators_directory}/${configurator_name}"
  if [[ -d "${configurator_directory}" ]]; then
    cp -r "${configurator_directory}/." "$output_directory"
  fi
}

install_configurator fallback
install_configurator primary
install_configurator secure-boot-updates
