#!/bin/sh

usage_error()
{
    echo "error: $1" >&2
    echo "Try '$0 --help' for more information". >&2
    exit 1
}

hosttype=$(cat /etc/puavo/hosttype)

if [ "$hosttype" != "laptop" -a \
    "$hosttype" != "wirelessaccesspoint" ]; then
    echo 'This script should be run only for laptops and wirelessaccesspoints!' \
        > /dev/stderr
    exit 1
fi

use_rate_limit=false
do_image_update=true
async=false

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            shift
            echo "Usage: $0"
            echo
            echo "Update device configuration and images."
            echo
            echo "Options:"
            echo "    --async                      do not wait for a reply"
            echo "    --use-rate-limit             limit the image download rate"
            echo "    --no-image-update            do not update images, only configurations"
            echo "    -h, --help                   print help and exit"
            echo
            exit 0
            ;;
        --async)
            shift
            async=true
            ;;
        --use-rate-limit)
            shift
            use_rate_limit=true
            ;;
        --no-image-update)
            shift
            do_image_update=false
            ;;
        --)
            shift
            break
            ;;
        -*)
            usage_error "invalid argument '$1'"
            ;;
        *)
            break
            ;;
    esac
done

if [ $# -ne 0 ]; then
    usage_error "invalid number of arguments ($#), expected 0"
fi

set -u

dbus_send_args=

if ! $async; then
    dbus_send_args='--print-reply=literal'
fi

# if synchronous call, fail after 30 seconds
dbus-send --system --dest=org.puavo.client.Daemon \
    --reply-timeout=30000 \
    ${dbus_send_args} \
    /updater org.puavo.client.update.UpdateConfiguration || true

if $do_image_update; then
    # if synchronous cal, fail after 8 hours
    dbus-send --system --dest=org.puavo.client.Daemon \
        --reply-timeout=28800000 \
        ${dbus_send_args} \
        /updater org.puavo.client.update.UpdateImages "boolean:${use_rate_limit}" || true
fi
