#!/bin/bash

set -eu
set -o pipefail

request_confirmation=true
use_secure_delete=false

destroy_in_dir() {
  local delete_cmd directory force_insecure message preserve_etc_puavo

  force_insecure=false
  preserve_etc_puavo=false
  while true; do
    case "$1" in
      --force-insecure)     force_insecure=true;     shift;;
      --preserve-etc-puavo) preserve_etc_puavo=true; shift;;
      *) break ;;
    esac
  done

  directory=$1
  message=$2

  if [ ! -e "$directory" ]; then
    return 0
  fi

  if ! $force_insecure && $use_secure_delete; then
    delete_cmd='srm -llr'
  else
    delete_cmd='rm -rf'
  fi

  if $preserve_etc_puavo; then
    find "$directory" -mindepth 5 -maxdepth 5 ! -path '*/etc/puavo' -print0
  else
    find "$directory" -mindepth 1 -maxdepth 1 -print0
  fi | pv -F ">>> $message %t" \
     | { xargs -0 --no-run-if-empty $delete_cmd || return 1; }
}

usage() {
  cat <<EOF
$(basename $0) [--force] [--secure-delete]

  --force               no questions asked
  --secure-delete       overwrite files before unlinking them (slow!)
EOF
  exit 1
}

send_state_reset_to_puavo() {
  local hostname reset_json reset_override_path url

  reset_override_path=$1

  hostname=$(cat /etc/puavo/hostname)                      || return 1
  reset_json=$(jq '{ "reset": . }' "$reset_override_path") || return 1

  url="/v3/devices/${hostname}/state_update"

  echo -n '>>> Sending reset information to Puavo... '
  timeout -k 5 30 puavo-rest-request "$url" --post --user-etc --writable \
    -- --data-binary "$reset_json" -H 'Content-Type: application/json' \
    > /dev/null || return 1
  echo DONE.
}

write_reset_override() {
  local current_time operation reset_override_path user

  operation=$1
  reset_override_path=$2

  current_time=$(date -Iseconds) || return 1
  user="${SUDO_USER:-}"
  if [ -z "$user" ]; then user="${USER:-}"; fi
  if [ -z "$user" ]; then user='?'        ; fi

  jq -r --arg current_time "$current_time" \
        --arg operation    "$operation"    \
        --arg user         "$user" '
    if (.|has("reset")) and (.reset|type == "object") then
      .reset
    else
      {
        "from":         $user,
        "operation":    $operation,
        "request-time": $current_time,
      }
    end | .["request-fulfilled"] = $current_time
  ' /state/etc/puavo/device.json > "${reset_override_path}.tmp" || return 1
  mv "${reset_override_path}.tmp" "$reset_override_path" || return 1
}

if [ "$(id -u)" -ne 0 ]; then
  echo 'You can run me as root only!' >&2
  exit 1
fi

if [ "$(puavo-conf puavo.mounts.nethomes.enabled)" = 'true' ]; then
  echo 'Refusing to do anything as network home directories are enabled' >&2
  exit 1
fi

for mnt in /home /images /state; do
  if ! mountpoint -q "$mnt"; then
    echo "${mnt} is not mounted, not continuing" >&2
    exit 1
  fi
done

puavo_hosttype=$(cat /etc/puavo/hosttype)

if [ "$puavo_hosttype" != "laptop" ]; then
  echo "I do not know how to wipe hosts of type '${puavo_hosttype}'" >&2
  exit 1
fi

if ! args=$(getopt -n "$0" -o + -l 'force,secure-delete' -- "$@"); then
  usage
fi

eval "set -- $args"
while [ $# -ne 0 ]; do
  case "$1" in
    --force)         request_confirmation=false; shift ;;
    --secure-delete) use_secure_delete=true    ; shift ;;
    --) shift; break ;;
    *)  usage ;;
  esac
done

[ $# -eq 0 ] || usage

if $use_secure_delete; then
  operation='reset'
else
  operation='fast-reset'
fi

while $request_confirmation; do
  cat <<'EOF'
DANGER, WILL ROBINSON!  DANGER!

THIS PROCEDURE WILL DESTROY ALL YOUR DATA IN YOUR HOME DIRECTORY!

This utility tries to quickly reset laptop state to something as if
it came from "the factory", as if nobody had ever used it.  This will
DESTROY YOUR STUFF and home directory contents, though in a quick way so
that old files MAY still recoverable with suitable tools.  If possible,
you should consider erasing things in a more secure way by doing a
reinstall with a full disk device "wipe".  That option is not perfect
either, but much better than this quick-and-dirty procedure.

DANGER!
THIS PROCEDURE WILL DESTROY ALL YOUR DATA IN YOUR HOME DIRECTORY, AND MORE!
WHEN IN DOUBT, TURN OFF THE MACHINE, PANIC AND RUN AWAY!
EOF
  echo
  read -p 'Are you sure you want to continue? (yes/no) ' answer
  case "$answer" in
    yes)
      echo 'THIS WILL DESTROY EVERYTHING!!!  WHAT ARE YOU THINKING?!?!?'
      read -p 'Are you REALLY sure? (yes/no) ' second_answer
      if [ "$second_answer" = "yes" ]; then
        break
      fi
      ;;
    no)
      echo 'Okay then, maybe a wise choice!'
      exit 0
      ;;
    *)
      echo "I do not understand that.\n" >&2
      ;;
  esac
done

resetstatus=0

if [ -b /dev/mapper/puavo-imageoverlays ]; then
  if ! mountpoint -q /imageoverlays; then
    if ! { mkdir -p /imageoverlays \
             && mount /dev/mapper/puavo-imageoverlays /imageoverlays; }; then
      echo 'Could not mount imageoverlays' >&2
      resetstatus=1
    fi
  fi
fi

cd /

# Remove primary user (so that we will send this information
# to Puavo through update-configuration).
cat /dev/null > /state/etc/puavo/primary_user_override || resetstatus=1

# we can speed up secure delete by not applying it to puavo-pkgs
destroy_in_dir --force-insecure /images/puavo-pkg/ 'Removing all puavo-pkgs' \
  || resetstatus=1

destroy_in_dir /home/ 'Cleaning up home directories' || resetstatus=1
destroy_in_dir /state/etc/puavo/local/ \
               'Removing local configurations (made by user)' || resetstatus=1
destroy_in_dir /state/var/cache/ 'Cleaning up caches' || resetstatus=1
destroy_in_dir /state/var/lib/   'Removing some system configurations' \
  || resetstatus=1

{ /usr/lib/puavo-ltsp-install/update-configuration || true; } 2>&1 \
  | pv -F '>>> Updating system configuration... %t' > /dev/null

destroy_in_dir --force-insecure --preserve-etc-puavo /imageoverlays/ \
               'Cleaning up most of /imageoverlays' || resetstatus=1
destroy_in_dir /state/etc/NetworkManager/system-connections/ \
               'Removing network manager connections' || resetstatus=1

reset_override_path='/state/etc/puavo/reset_override'
if ! write_reset_override "$operation" "$reset_override_path"; then
  echo
  echo 'Error in writing reset override' >&2
  echo
  resetstatus=1
fi

if [ "$resetstatus" -eq 0 ] \
  && ! send_state_reset_to_puavo "$reset_override_path"; then
    {
      echo
      echo 'Failed to sending reset information to Puavo.  You may reboot'
      echo 'this host, it tries to update the reset information later,'
      echo 'but you may also remove it manually from the Puavo interface.'
      echo
    } >&2
    resetstatus=1
fi

destroy_in_dir --force-insecure /imageoverlays/ \
               'Cleaning up all of /imageoverlays' || resetstatus=1

if [ "$resetstatus" -ne 0 ]; then
  echo 'Errors in device reset' >&2
  exit $resetstatus
fi

i=5
echo
echo -n "Rebooting in $i seconds..."
while [ "$i" -gt 0 ]; do
  i=$(($i - 1))
  sleep 1
  echo -n " $i"
done
echo .

reboot
