#!/bin/sh

set -e

puavo-register --accepted-devicetypes \
	       fatclient,laptop,ltspserver,thinclient,wirelessaccesspoint

hosttype="$(cat /etc/puavo/hosttype)"

case "$hosttype" in
  laptop|wirelessaccesspoint)
    puavo-setup-filesystems

    mkdir -p /state/etc
    cp -aT /etc/puavo /state/etc/puavo

    # install from nbd, the ltsp image must contain its name in this path
    ltspimage_name=$(cat /etc/ltsp/this_ltspimage_name)

    puavo-install-and-update-ltspimages --install-from-nbd /dev/nbd0 \
					"$ltspimage_name"

    echo -n "Doing grub installation: "
    puavo-install-grub
    sync

    echo "Updating $hosttype configuration..."
    if puavo-update-thishost; then
      echo "  ... $hosttype configuration updated."
    else
      echo "  ... a problem occurred (updating configuration later)."
    fi
    sync

    umount /state /images /home

    echo "Press ENTER to reboot"
    read answer
    ;;
  ltspserver)
    puavo-setup-filesystems
    mkdir -p /state/etc
    cp -a /etc/puavo /state/etc

    sync
    umount /state
    ;;
esac
