#!/bin/sh

set -eu

# This script is run on image updates from puavo-image-preinst so that only
# /images is writable!  (and some other pseudo-filesystems such as /dev and
# /proc are accessible as well).

grub_efi_arguments() {
  [ -d /sys/firmware/efi ] || return 0
  echo '--target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=debian'
  if [ "$(puavo-conf puavo.grub.efi.force_extra_removable)" = 'true' ]; then
    echo '--force-extra-removable'
  fi
}

grub_m4_template() {
  cat <<'EOF'
set default="0"
load_env

function load_video {
  if [ x$feature_all_video_module = xy ]; then
    insmod all_video
  else
    insmod efi_gop
    insmod efi_uga
    insmod ieee1275_fb
    insmod vbe
    insmod vga
    insmod video_bochs
    insmod video_cirrus
  fi
}

if loadfont unicode ; then
  set gfxmode=auto
  load_video
  insmod gfxterm
  set locale_dir=$prefix/locale
  insmod gettext
fi
terminal_output gfxterm
set timeout=5
### END /usr/local/etc/grub.d/00_header ###

function get_kernelarch { regexp -s 2:"$2" '^(.*)-(i386|amd64)$' "$1"; }
function get_pathname { regexp -s 2:"$2" '^(\(.*\))?(/.*)$' "$1"; }

function get_kernelversion {
  if regexp -s 1:"$2" '^(.*)-(i386|amd64)$' "$1"; then
    :
  else
    set $2="$1"
  fi
}

function ltsp_image_entry {
  set imagefile="$1"
  set description="$2"
  set kernelparameters="$3"
  set boottype="$4"

  get_pathname $imagefile imagepath

  # ${puavo_kernel_arguments} comes from a grub environment file
  # (if it is defined there)
  set kernelparameters="${kernelparameters} ${puavo_kernel_arguments}"
  if test "$boottype" = "liveboot"; then
    set kernelparameters="${kernelparameters} puavo.hosttype=laptop puavo.guestlogin.enabled=true"
  fi

  if test "$imagepath" = "/${puavo_grub_puavo_os_default_image}" \
       -a "$boottype" = "$puavo_grub_puavo_os_default_mode"; then
    set default="${description} (${imagepath})"
  fi

  menuentry "${description} (${imagepath})" "$imagefile" "$imagepath" "$kernelparameters" {
    set kernel_version=''
    # --- remove "#" from the following if you need another kernel ---
    # set kernel_version='default'
    # set kernel_version='legacy'
    # set kernel_version='fresh'

    set imagefile="$2"
    set imagepath="$3"

    loopback loop "${imagefile}"
    set root='(loop)'

    #
    # this mirrors code in puavo-ltspboot-config (puavo-tftpd hook)
    #

    if test "$kernel_version" = ""; then
      # ${puavo_kernel_version} comes from a grub environment file
      # (if it is defined there)
      set kernel_version="$puavo_kernel_version"
    elif test "$kernel_version" = "default"; then
      set kernel_version=""
    fi

    set use_if64cpu='false'

    set kernel_version_suffix=''
    if test -n "${kernel_version}"; then
      if regexp -- '-(amd64|i386)$' "${kernel_version}"; then
        # kernel_version set to particular arch
        if test -e "(loop)/boot/vmlinuz-${kernel_version}"; then
          set kernel_version_suffix="-${kernel_version}"
        else
          true  # ... but kernel not available, so just use default
        fi
      elif test -e "(loop)/boot/vmlinuz-${kernel_version}-amd64" \
             -a -e "(loop)/boot/vmlinuz-${kernel_version}-i386"; then
        set use_if64cpu='true'
        set kernel_version_suffix="-${kernel_version}"
      elif test -e "(loop)/boot/vmlinuz-${kernel_version}"; then
        # no kernels for both archs, but some kernel exists, so use that
        set kernel_version_suffix="-${kernel_version}"
      else
        # requested kernel not found, use default
        true
      fi
    elif test -e '(loop)/boot/vmlinuz-amd64' \
           -a -e '(loop)/boot/vmlinuz-i386'; then
      set use_if64cpu='true'
    else
      true              # okay, just use default kernel
    fi

    if test "${use_if64cpu}" = 'true'; then
      if cpuid -l; then
        set kernel_version_suffix="${kernel_version_suffix}-amd64"
      else
        set kernel_version_suffix="${kernel_version_suffix}-i386"
      fi
    fi

    # one more sanity test (also checks the corresponding initrd.img)
    if test -e "(loop)/boot/initrd.img${kernel_version_suffix}" \
         -a -e "(loop)/boot/vmlinuz${kernel_version_suffix}"; then
      true      # all is okay
    else
      # something is wrong, use the default kernel
      set kernel_version_suffix=''
    fi

    set kernelparameters="$4"

    linux   /boot/vmlinuz${kernel_version_suffix} ro init=/sbin/init-puavo __PUAVO_KERNEL_ARGUMENTS__ ${kernelparameters}
    initrd  /boot/initrd.img${kernel_version_suffix}

    loopback -d loop
  }
}

## Superlaptop mode = persistent image changes + local admins
function ltsp_image_entry_superlaptop {
  set imagefile="$1"
  set description="$2"
  set kernelparameters="$3"

  if test "${puavo_show_imageoverlays}" = "true" \
            -a -d (lvm/puavo-imageoverlays); then
    set kernelparameters="$kernelparameters puavo.image.overlay=personal"

    ltsp_image_entry "${imagefile}" "${description}" "${kernelparameters}" "developer"
  fi
}

insmod gzio
insmod part_msdos
insmod ext2
insmod squash4
insmod biosdisk
insmod regexp
insmod loopback
insmod usb_keyboard
insmod lvm
insmod jpeg
insmod png

for dev in (lvm/__PUAVO_LVM_PARTITION__); do
  for file in ${dev}/*.default; do
    regexp -s default_alias_no_suffix '^(.*)\.default$' "${file}"
    break
  done
  for file in ${dev}/*.backup; do
    regexp -s backup_alias_no_suffix '^(.*)\.backup$' "${file}"
    break
  done

  set default_image="${dev}/ltsp.img"
  set backup_image="${dev}/ltsp-backup.img"
  set default_image_alias="${default_alias_no_suffix}.img"
  set backup_image_alias="${backup_alias_no_suffix}.img"

  if test "$lang" = "de_CH.UTF-8" -o "$lang" = "de_DE.UTF-8"; then
    set text_normal_startup="Normaler Start"
    set text_liveboot_startup="Liveboot-Start"
    set text_developer_mode="Entwicklermodus"
    set text_backup_normal_startup="Backup-System, normaler Start"
    set text_backup_developer_mode="Backup-System, Entwicklermodus"
    set text_other_system_normal_startup="Anderes System, normaler Start"
    set text_other_system_developer_mode="Anderes System, Entwicklermodus"
  elif test "$lang" = "fi_FI.UTF-8"; then
    set text_normal_startup="Normaali käynnistys"
    set text_liveboot_startup="Liveboot-käynnistys"
    set text_developer_mode="Kehittäjätila"
    set text_backup_normal_startup="Varajärjestelmä, normaali käynnistys"
    set text_backup_developer_mode="Varajärjestelmä, kehittäjätila"
    set text_other_system_normal_startup="Muu järjestelmä, normaali käynnistys"
    set text_other_system_developer_mode="Muu järjestelmä, kehittäjätila"
  elif test "$lang" = "fr_CH.UTF-8"; then
    set text_normal_startup="Démarrage normal"
    set text_liveboot_startup="Démarrage live"
    set text_developer_mode="Mode développeur"
    set text_backup_normal_startup="Système de secours, démarrage normal"
    set text_backup_developer_mode="Système de secours, mode développeur"
    set text_other_system_normal_startup="Autre système, démarrage normal"
    set text_other_system_developer_mode="Autre système, mode développeur"
  elif test "$lang" = "sv_FI.UTF-8"; then
    set text_normal_startup="Normal start"
    set text_liveboot_startup="Start av liveboot"
    set text_developer_mode="Utvecklarläge"
    set text_backup_normal_startup="Backup-system, normal start"
    set text_backup_developer_mode="Backup-system, utvecklarläge"
    set text_other_system_normal_startup="Annat system, normal start"
    set text_other_system_developer_mode="Annat system, utvecklarläge"
  else
    set text_normal_startup="Normal startup"
    set text_liveboot_startup="Liveboot startup"
    set text_developer_mode="Developer mode"
    set text_backup_normal_startup="Backup system, normal startup"
    set text_backup_developer_mode="Backup-system, developer mode"
    set text_other_system_normal_startup="Other system, normal startup"
    set text_other_system_developer_mode="Other system, developer mode"
  fi

  if test -f "${default_image}"; then
    ltsp_image_entry "${default_image}" "${text_normal_startup} - ${default_image_alias}" "" "normal"
    if test "__PUAVO_LIVEBOOT_OPTION__" = "true"; then
      ltsp_image_entry "${default_image}" "${text_liveboot_startup} - ${default_image_alias}" "" "liveboot"
    fi
    ltsp_image_entry_superlaptop "${default_image}" "${text_developer_mode} - ${default_image_alias}"

    loopback default_image_loop "${default_image}"
    set possible_puavo_grub_theme_path="(default_image_loop)/boot/grub/themes/${puavo_grub_theme}/theme.txt"
    if test -f "${possible_puavo_grub_theme_path}"; then
      set theme="${possible_puavo_grub_theme_path}"
    fi
  fi
  if test -f "${backup_image}"; then
    ltsp_image_entry "${backup_image}" "${text_backup_normal_startup} - ${backup_image_alias}" "" "normal"
    ltsp_image_entry_superlaptop "${backup_image}" "${text_backup_developer_mode} - ${backup_image_alias}"
  fi

  for file in ${dev}/*.img; do
    if test "${file}" = "${default_image}";       then continue; fi
    if test "${file}" = "${backup_image}";        then continue; fi
    if test "${file}" = "${default_image_alias}"; then continue; fi
    if test "${file}" = "${backup_image_alias}";  then continue; fi

    ltsp_image_entry "${file}" "${text_other_system_normal_startup}" "" "normal"
    ltsp_image_entry_superlaptop "${file}" "${text_other_system_developer_mode}"
  done
done
EOF
}

find_grub_target_devices_on_raid() {
  _diskdev=$1
  mdadm --detail "$_diskdev" \
    | awk '   $1 ~ /^[0-9]+$/ \
           && $2 ~ /^[0-9]+$/ \
           && $3 ~ /^[0-9]+$/ {
             split($0, a)
             for (i in a) {
               if (a[i] ~ /^\/dev\/[a-z]+[0-9]+$/) {
                  sub(/[0-9]+$/, "", a[i])
                  print a[i]
               }
             }
           }'
}

handle_windows_partion_file() {
  local possible_windows_disk_dev windows_partition_number \
        windows_partition_path

  # set up this file so that UI tools can check if host has
  # a Windows-partition

  possible_windows_disk_dev=$1
  windows_partition_number=$2
  windows_partition_path=/images/boot/.puavo_windows_partition

  if [ -n "$windows_partition_number" ]; then
    printf "%s%s\n" "$possible_windows_disk_dev" "$windows_partition_number" \
      > "${windows_partition_path}.tmp"
    if ! cmp "${windows_partition_path}.tmp" \
             "$windows_partition_path" 2>/dev/null; then
      mv "${windows_partition_path}.tmp" "$windows_partition_path"
    else
      rm -f "${windows_partition_path}.tmp"
    fi
  else
    rm -f "$windows_partition_path"
  fi
}

lookup_windows_partition_number() {
  # Presume that the first partition not containing "Linux"
  # is a Windows-partition.
  _diskdev=$1
  env LANG=C fdisk -l "$_diskdev" \
    | awk '$1 ~ "^/dev/" && !/(BIOS boot|Extended|Linux)/ {
	     if (match($1, /[0-9]+$/, _)) { print _[0]; exit }
           }'
}

usage() {
  cat <<EOF
$(basename $0) [optional arguments]

  $(basename $0) takes the following optional arguments:

    --hosttype           hosttype
    --images-dir         imagesdir
    --only-update-config
    --vgname             vgname
EOF
  exit 1
}

exitstatus=0

hosttype=$(cat /etc/puavo/hosttype 2>/dev/null || true)
images_dir=/images
only_update_config=false
vgname=puavo

if ! args=$(getopt -n "$0" -o +                                          \
                   -l 'hosttype:,images-dir:,only-update-config,vgname:' \
                   -- "$@"); then
  usage
fi

eval "set -- $args"
while [ $# -ne 0 ]; do
  case "$1" in
    --hosttype)           hosttype=$2;             shift; shift ;;
    --images-dir)         images_dir=$2;           shift; shift ;;
    --only-update-config) only_update_config=true; shift        ;;
    --vgname)             vgname=$2;               shift; shift ;;
    --) shift; break ;;
    *)  usage ;;
  esac
done

[ $# -eq 0 ] || usage

if [ ! -d "$images_dir" ]; then
  echo "'$images_dir' is not a directory" >&2
  exit 1
fi

if [ -z "$hosttype" ]; then
  echo 'Hosttype is not set' >&2
  exit 1
fi

boot_dir="${images_dir}/boot"

# pvs and assorted utilities complain if we leak file descriptors, that is
# why we do "3>&- 4>&- 5>&-" (same with grub-install)
diskdev=$(pvs 3>&- 4>&- 5>&-                                            \
            | awk -v vgname="$vgname" '$2 == vgname { print $1; exit }' \
            | sed -E '
                /\/dev\/loop/   { s|p[0-9]+$|| }
                /\/dev\/mmcblk/ { s|p[0-9]+$|| }
                /\/dev\/md/     { s|p[0-9]+$|| }
                /\/dev\/nvme/   { s|p[0-9]+$|| }
                /\/dev\/[sv]d/  { s|[0-9]+$||  }
              ')

if [ -z "$diskdev" ]; then
  echo "Could not find the disk device where volume group '${vgname}' is" >&2
  exit 1
fi

case "$diskdev" in
  /dev/md*)
    grub_target_devices=$(find_grub_target_devices_on_raid "$diskdev")
    if [ -z "$grub_target_devices" ]; then
      echo 'Could not find grub target devices on RAID configuration' >&2
      exit 1
    fi
    possible_windows_disk_dev=''
    ;;
  *)
    grub_target_devices="$diskdev"
    possible_windows_disk_dev="$diskdev"
    ;;
esac

if [ "$hosttype" = 'diskinstaller' ]; then
  puavo_liveboot_option='true'
  puavo_lvm_partition='puavoinstaller-installimages'
else
  puavo_liveboot_option='false'
  puavo_lvm_partition='puavo-images'
fi

# loop= parameter is legacy and is meant for the old Trusty-based Puavo-systems.
common_kernel_arguments="puavo.hosttype=${hosttype} root=/dev/mapper/${puavo_lvm_partition} loop=\"\${imagepath}\" puavo.image.path=\"\${imagepath}\""

case "$hosttype" in
  bootserver|diskinstaller|preinstalled|wirelessaccesspoint)
    puavo_kernel_arguments="$common_kernel_arguments"
    ;;
  laptop)
    puavo_kernel_arguments="quiet splash ${common_kernel_arguments}"
    ;;
  *)
    echo "Hosttype '$hosttype' is not supported" > /dev/stderr
    exit 1
    ;;
esac

if ! $only_update_config; then
  for grubdev in $grub_target_devices; do
    if ! grub_msg=$(grub-install --boot-directory="$boot_dir" \
                     $(grub_efi_arguments) "$grubdev" \
                     3>&- 4>&- 5>&- 2>&1); then
          echo "Grub installation to $grubdev failed: $grub_msg" >&2
          exit 1
    fi
  done

  grub-install --version | awk '{ print $3 }' > "${boot_dir}/grub/version.tmp"
  if [ ! -s "${boot_dir}/grub/version.tmp" ]; then
    echo 'Could not determine new grub version' >&2
    rm -f "${boot_dir}/grub/version.tmp"
    exitstatus=1
  else
    mv "${boot_dir}/grub/version.tmp" "${boot_dir}/grub/version"
    echo "Grub has been installed to: $(echo $grub_target_devices)."
  fi
fi

grub_cfg_path="${boot_dir}/grub/grub.cfg"
tmp_grub_cfg_path="${grub_cfg_path}.tmp"

grub_m4_template                                              \
  | m4 -D__PUAVO_KERNEL_ARGUMENTS__="$puavo_kernel_arguments" \
       -D__PUAVO_LIVEBOOT_OPTION__="$puavo_liveboot_option"   \
       -D__PUAVO_LVM_PARTITION__="$puavo_lvm_partition"       \
  > "$tmp_grub_cfg_path"

if [ -n "$possible_windows_disk_dev" ]; then
  windows_partition_number=$(lookup_windows_partition_number \
                               "$possible_windows_disk_dev")

  handle_windows_partion_file "$possible_windows_disk_dev" \
                              "$windows_partition_number"

  if [ -n "$windows_partition_number" ]; then
    cat <<EOF >> "$tmp_grub_cfg_path"

if test "\${puavo_grub_windows_enabled}" = "true"; then
  menuentry "Windows" {
    insmod ntfs
    set root=(hd0,$windows_partition_number)
    chainloader +1
  }
  if test "\${puavo_grub_boot_default}" = "windows"; then
    set default="Windows"
  fi
fi
EOF
  fi
fi


if cmp "$grub_cfg_path" "$tmp_grub_cfg_path" >/dev/null 2>&1; then
  rm -f "$tmp_grub_cfg_path"
else
  mv "$tmp_grub_cfg_path" "$grub_cfg_path"
fi

# We have got some weird spurious grub errors of the sort (at first boot):
# "error: ELF header smaller than expected", so we play it safe
# and try weird tricks to flush all caches to actual, physical disk.
# But we are not quite sure yet this will actually work (the problem is
# difficult to reproduce).
sync
echo 3 > /proc/sys/vm/drop_caches

for grubdev in $grub_target_devices; do
  blockdev --flushbufs "$grubdev"
done

for grubdev in $grub_target_devices; do
  case "$grubdev" in
    /dev/[sv]d*)
      hdparm -qF "$grubdev"
      ;;
  esac
done

exit $exitstatus
