#!/bin/sh
set -eu

boot_directory=$1

if [ -z "$boot_directory" ]; then
  echo "Usage: $0 <boot_directory>"
  exit 1
fi

if [ ! -d "$boot_directory" ]; then
  echo "Boot directory '$boot_directory' does not exist" >&2
  exit 1
fi

install_boot_entry_config() {
  local extra_directory="$1"
  local environment_file="${extra_directory}/grubenv"

  if [ ! -r /etc/puavo-image/class ] || [ ! -r /etc/puavo-image/release ]; then
    echo "Missing boot entry information" >&2
    return 1
  fi

  local class release label
  class=$(cat /etc/puavo-image/class)
  release=$(cat /etc/puavo-image/release)
  label="PuavoOS (${release})" # Todo: Decide how we generate the labels

  [ -f "$environment_file" ] || grub-editenv "$environment_file" create || {
    echo "Failed to create the GRUB environment of a boot entry" >&2
    return 1
  }

  (grub-editenv "$environment_file" set "label=${label}" &&
    grub-editenv "$environment_file" set "class=${class}") || {
    echo "Failed to write the GRUB environment of a boot entry" >&2
    return 1
  }
}

install_uki() {
  local uki="$1"
  local destination="$2"
  local name
  name=$(basename "$uki")

  if ! cp "$uki" "$destination"; then
    echo "Failed to copy UKI to EFI partition" >&2
    return 1
  fi

  local extra_directory="${destination}/${name}.extra.d"
  if ! mkdir -p "$extra_directory"; then
    echo "Failed to create the extra directory for UKI in EFI partition" >&2
    return 1
  fi

  install_boot_entry_config "$extra_directory"
}

for uki in /boot/*.uki.efi; do
  install_uki "$uki" "$boot_directory"
done
