#!/bin/sh

set -e

install_from_nbd() {
  images_dir=$1
  imagename=$2
  imagepath=$images_dir/$imagename

  test -e "$imagepath" && return 0

  # clean up old temporary images
  rm -f $images_dir/*.tmp

  total_size=$(df /dev/nbd0 | awk '$1 == "/dev/nbd0" { print $2 "k" }')
  dd if=/dev/nbd0 2>/dev/null | pv -s "$total_size" \
    > "${imagepath}.tmp"
  sync
  mv "${imagepath}.tmp" "$imagepath"
  sync
}

# XXX duplicate code with puavo-update-ltspimage
set_image_as_default_image() {
  images_dir=$1
  imagename=$2
  imagepath=$images_dir/$imagename

  backup_ltspimage_path=$images_dir/ltsp-backup.img
  default_ltspimage_path=$images_dir/ltsp.img

  ln -f "$default_ltspimage_path" "$backup_ltspimage_path" 2>/dev/null || true
  ln -f "$imagepath" "${default_ltspimage_path}.tmp"
  sync
  mv "${default_ltspimage_path}.tmp" "$default_ltspimage_path"
  sync

  update_image_labels_for_grub "$images_dir"
  sync

  echo "The PuavoLTSP image $imagename"
  echo "is now installed and set as default."
}

# XXX duplicate code with puavo-update-ltspimage
lookup_ltspimage_name_by_alias() {
  images_dir=$1
  imagename=$2

  current_ltspimage_path="$images_dir/$imagename"
  current_ltspimage_inode="$(stat -c %i $current_ltspimage_path 2>/dev/null || true)"

  for file in $images_dir/*.img; do
    # check that *.img expands to something
    test -e "$file" || continue

    # ltsp.img is not what we are looking for
    test "$file" = "$current_ltspimage_path" && continue

    # we want its other name...
    if [ "$(stat -c %i "$file" || true)" = "$current_ltspimage_inode" ]; then
      echo "$(basename "$file")"
      return 0
    fi
  done
}

query_update_confirmation() {
  current_ltspimage_name=$1
  new_ltspimage_name=$2

  cat <<EOF
The current PuavoLTSP image is $current_ltspimage_name,
but version $new_ltspimage_name is available.

Press ENTER to proceed to update it.
EOF
  read answer
}

install_image() {
  images_dir=$1
  imagename=$2

  current_ltspimage_name=$(lookup_ltspimage_name_by_alias "$images_dir" \
							  ltsp.img)
  if [ "$current_ltspimage_name" = "$imagename" ]; then
    echo "The wanted PuavoLTSP image $imagename"
    echo "is already in place."
    return 0
  fi

  if [ -n "$current_ltspimage_name" ]; then
    query_update_confirmation "$current_ltspimage_name" "$imagename"
  fi

  install_from_nbd "$images_dir" "$imagename"
  set_image_as_default_image "$images_dir" "$imagename"
}

# XXX duplicate code with puavo-update-ltspimage
update_image_labels_for_grub() {
  images_dir=$1

  default_image=$(lookup_ltspimage_name_by_alias "$images_dir" ltsp.img)
  backup_image=$( lookup_ltspimage_name_by_alias "$images_dir" ltsp-backup.img)

  rm -f ${images_dir}/ltsp-*.backup ${images_dir}/ltsp-*.default

  test -n "$default_image" && touch "${default_image%.img}.default"
  test -n "$backup_image"  && touch "${backup_image%.img}.backup"
}


ltspimage_name=$1
images_dir=${2:-/images}

if [ -z "$ltspimage_name" -o ! -d "$images_dir" ]; then
  echo "Usage: $(basename $0) ltspimage_name images_dir" > /dev/stderr
  exit 1
fi

hosttype=$(cat /etc/puavo/hosttype)

case "$hosttype" in
  laptop)
    install_image "$images_dir" "$ltspimage_name"
    ;;
  *)
    echo "Hosttype '$hosttype' is not supported" > /dev/stderr
    exit 1
    ;;
esac
