#!/bin/bash

if [ $# -ne 2 ]; then
    echo "wrong number of arguments" >&2
    exit 1
fi

tap=$1
bridge=$2

source puavo-wlanap-env || exit 1
source "${PWAP_DATADIR}/config"
source "${PWAP_DATADIR}/config" || true

networks="${PWAP_RUNDIR}/networks"

(
    flock "${networksfd}"

    tmpfile=$(mktemp) || exit 1

    sort -u "${networks}" <(echo "${tap} ${bridge}") >"${tmpfile}" || {
        rm -f "${tmpfile}"
        exit 1
    }

    mv "${tmpfile}" "${networks}" || {
        rm -f "${tmpfile}"
        exit 1
    }
) {networksfd}>"${networks}"
