#!/bin/sh

set -eu

# XXX should use syslog?

lock_wifi() {
  local currently_active_wifi_network_uuid current_nmconnection_path \
        nm_statedir

  currently_active_wifi_network_uuid=$(
    env LANG=C nmcli -t -f TYPE,UUID connection show --active \
      | awk -F: '$1 == "802-11-wireless" { print $2; exit(0) }')

  if [ -z "$currently_active_wifi_network_uuid" ]; then
    echo 'no currently active wifi network' >&2
    return 1
  fi

  nm_statedir='/state/etc/NetworkManager/system-connections'
  current_nmconnection_path=$(
    awk -F= -v active_uuid="$currently_active_wifi_network_uuid" '
      $1 == "uuid" && $2 == active_uuid { print FILENAME; exit 0 }
    ' "$nm_statedir"/*)
  if ! [ -e "$current_nmconnection_path" ]; then
    echo 'could not find nm connection file' >&2
    return 1
  fi

  rm -rf /etc/NetworkManager/system-connections.exammode
  mkdir -p /etc/NetworkManager/system-connections.exammode
  cp -p "$current_nmconnection_path" \
        /etc/NetworkManager/system-connections.exammode
  ln -fns system-connections.exammode \
          /etc/NetworkManager/system-connections

  nmcli connection reload
  nmcli connection modify "$currently_active_wifi_network_uuid" \
                   connection.autoconnect yes
  nmcli connection modify "$currently_active_wifi_network_uuid" \
                   connection.autoconnect-priority 999
}

unlock_wifi() {
  ln -fns /state/etc/NetworkManager/system-connections \
          /etc/NetworkManager/system-connections
  nmcli connection reload
  rm -rf /etc/NetworkManager/system-connections.exammode
}

if ! mountpoint -q /state; then
  echo '/state is not mounted, is this a laptop?' >&2
  exit 1
fi

mode=${1:-}

case "$mode" in
  --lock)
    lock_wifi
    ;;
  --unlock)
    unlock_wifi
    ;;
  '')
    echo "Usage: $(basename "$0") --lock|--unlock" >&2
    exit 1
    ;;
  *)
    echo "unsupported mode '${mode}'" >&2
    exit 1
    ;;
esac
