#!/bin/sh

DAEMON_PID_FILE=$1

if [ -n "${DAEMON_PID_FILE}" ]; then
  DAEMON_PID=$(cat ${DAEMON_PID_FILE})

  if [ -n "${DAEMON_PID}" ]; then
    rm "/run/puavo-vpn-client/services-${DAEMON_PID}"

    /usr/lib/puavo-vpn-client/set-servers
  fi
fi
