"""
Test puavodisplays.xrandr
"""
import dataclasses
import json

import puavodisplays.xrandr


def _read_prop(file_path: str) -> str:
    with open(file_path, encoding="utf-8") as xrandr_prop_output_file:
        return xrandr_prop_output_file.read()


def test_prop_parser():
    xrandr_prop_output = _read_prop("xrandr_prop_output_1_display.txt")
    parser = (
        puavodisplays.xrandr._XRandrPropOutputParser()  # pylint: disable=protected-access
    )
    prop = parser.parse(xrandr_prop_output)

    assert json.dumps(
        {n: dataclasses.asdict(o) for n, o in prop.items()}, sort_keys=True, indent=2
    ) == json.dumps(
        {
            "eDP-1": {
                "is_primary": True,
                "name": "eDP-1",
                "state": "connected",
                "current_mode": {
                    "aspect_ratio": "16:9",
                    "refresh_rate": 60.01,
                    "resolution_x": 1920,
                    "resolution_y": 1080,
                },
                "modes": [
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 60.0,
                        "resolution_x": 3840,
                        "resolution_y": 2160,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.98,
                        "resolution_x": 3840,
                        "resolution_y": 2160,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.97,
                        "resolution_x": 3840,
                        "resolution_y": 2160,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 40.0,
                        "resolution_x": 3840,
                        "resolution_y": 2160,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.96,
                        "resolution_x": 3200,
                        "resolution_y": 1800,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.94,
                        "resolution_x": 3200,
                        "resolution_y": 1800,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.96,
                        "resolution_x": 2880,
                        "resolution_y": 1620,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.97,
                        "resolution_x": 2880,
                        "resolution_y": 1620,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.99,
                        "resolution_x": 2560,
                        "resolution_y": 1600,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.97,
                        "resolution_x": 2560,
                        "resolution_y": 1600,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.99,
                        "resolution_x": 2560,
                        "resolution_y": 1440,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.99,
                        "resolution_x": 2560,
                        "resolution_y": 1440,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.96,
                        "resolution_x": 2560,
                        "resolution_y": 1440,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.95,
                        "resolution_x": 2560,
                        "resolution_y": 1440,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.0,
                        "resolution_x": 2048,
                        "resolution_y": 1536,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.0,
                        "resolution_x": 1920,
                        "resolution_y": 1440,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.01,
                        "resolution_x": 1856,
                        "resolution_y": 1392,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.01,
                        "resolution_x": 1792,
                        "resolution_y": 1344,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.99,
                        "resolution_x": 2048,
                        "resolution_y": 1152,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.98,
                        "resolution_x": 2048,
                        "resolution_y": 1152,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.9,
                        "resolution_x": 2048,
                        "resolution_y": 1152,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.91,
                        "resolution_x": 2048,
                        "resolution_y": 1152,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.88,
                        "resolution_x": 1920,
                        "resolution_y": 1200,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.95,
                        "resolution_x": 1920,
                        "resolution_y": 1200,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 60.01,
                        "resolution_x": 1920,
                        "resolution_y": 1080,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.97,
                        "resolution_x": 1920,
                        "resolution_y": 1080,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.96,
                        "resolution_x": 1920,
                        "resolution_y": 1080,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.93,
                        "resolution_x": 1920,
                        "resolution_y": 1080,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.0,
                        "resolution_x": 1600,
                        "resolution_y": 1200,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.95,
                        "resolution_x": 1680,
                        "resolution_y": 1050,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.88,
                        "resolution_x": 1680,
                        "resolution_y": 1050,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 59.98,
                        "resolution_x": 1400,
                        "resolution_y": 1050,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.99,
                        "resolution_x": 1600,
                        "resolution_y": 900,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.94,
                        "resolution_x": 1600,
                        "resolution_y": 900,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.95,
                        "resolution_x": 1600,
                        "resolution_y": 900,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.82,
                        "resolution_x": 1600,
                        "resolution_y": 900,
                    },
                    {
                        "aspect_ratio": "5:4",
                        "refresh_rate": 60.02,
                        "resolution_x": 1280,
                        "resolution_y": 1024,
                    },
                    {
                        "aspect_ratio": "14:9",
                        "refresh_rate": 59.96,
                        "resolution_x": 1400,
                        "resolution_y": 900,
                    },
                    {
                        "aspect_ratio": "14:9",
                        "refresh_rate": 59.88,
                        "resolution_x": 1400,
                        "resolution_y": 900,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.0,
                        "resolution_x": 1280,
                        "resolution_y": 960,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 60.0,
                        "resolution_x": 1440,
                        "resolution_y": 810,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.97,
                        "resolution_x": 1440,
                        "resolution_y": 810,
                    },
                    {
                        "aspect_ratio": "57:32",
                        "refresh_rate": 59.88,
                        "resolution_x": 1368,
                        "resolution_y": 768,
                    },
                    {
                        "aspect_ratio": "57:32",
                        "refresh_rate": 59.85,
                        "resolution_x": 1368,
                        "resolution_y": 768,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.99,
                        "resolution_x": 1280,
                        "resolution_y": 800,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.97,
                        "resolution_x": 1280,
                        "resolution_y": 800,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.81,
                        "resolution_x": 1280,
                        "resolution_y": 800,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.91,
                        "resolution_x": 1280,
                        "resolution_y": 800,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 60.0,
                        "resolution_x": 1280,
                        "resolution_y": 720,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.99,
                        "resolution_x": 1280,
                        "resolution_y": 720,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.86,
                        "resolution_x": 1280,
                        "resolution_y": 720,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.74,
                        "resolution_x": 1280,
                        "resolution_y": 720,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.04,
                        "resolution_x": 1024,
                        "resolution_y": 768,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.0,
                        "resolution_x": 1024,
                        "resolution_y": 768,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.0,
                        "resolution_x": 960,
                        "resolution_y": 720,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.05,
                        "resolution_x": 928,
                        "resolution_y": 696,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.01,
                        "resolution_x": 896,
                        "resolution_y": 672,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.95,
                        "resolution_x": 1024,
                        "resolution_y": 576,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.96,
                        "resolution_x": 1024,
                        "resolution_y": 576,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.9,
                        "resolution_x": 1024,
                        "resolution_y": 576,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.82,
                        "resolution_x": 1024,
                        "resolution_y": 576,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.93,
                        "resolution_x": 960,
                        "resolution_y": 600,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 60.0,
                        "resolution_x": 960,
                        "resolution_y": 600,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.96,
                        "resolution_x": 960,
                        "resolution_y": 540,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.99,
                        "resolution_x": 960,
                        "resolution_y": 540,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.63,
                        "resolution_x": 960,
                        "resolution_y": 540,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.82,
                        "resolution_x": 960,
                        "resolution_y": 540,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.0,
                        "resolution_x": 800,
                        "resolution_y": 600,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.32,
                        "resolution_x": 800,
                        "resolution_y": 600,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 56.25,
                        "resolution_x": 800,
                        "resolution_y": 600,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 60.01,
                        "resolution_x": 840,
                        "resolution_y": 525,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.88,
                        "resolution_x": 840,
                        "resolution_y": 525,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.92,
                        "resolution_x": 864,
                        "resolution_y": 486,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.57,
                        "resolution_x": 864,
                        "resolution_y": 486,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 59.98,
                        "resolution_x": 700,
                        "resolution_y": 525,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.95,
                        "resolution_x": 800,
                        "resolution_y": 450,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.82,
                        "resolution_x": 800,
                        "resolution_y": 450,
                    },
                    {
                        "aspect_ratio": "5:4",
                        "refresh_rate": 60.02,
                        "resolution_x": 640,
                        "resolution_y": 512,
                    },
                    {
                        "aspect_ratio": "14:9",
                        "refresh_rate": 59.96,
                        "resolution_x": 700,
                        "resolution_y": 450,
                    },
                    {
                        "aspect_ratio": "14:9",
                        "refresh_rate": 59.88,
                        "resolution_x": 700,
                        "resolution_y": 450,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.0,
                        "resolution_x": 640,
                        "resolution_y": 480,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 59.94,
                        "resolution_x": 640,
                        "resolution_y": 480,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.51,
                        "resolution_x": 720,
                        "resolution_y": 405,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 58.99,
                        "resolution_x": 720,
                        "resolution_y": 405,
                    },
                    {
                        "aspect_ratio": "57:32",
                        "refresh_rate": 59.88,
                        "resolution_x": 684,
                        "resolution_y": 384,
                    },
                    {
                        "aspect_ratio": "57:32",
                        "refresh_rate": 59.85,
                        "resolution_x": 684,
                        "resolution_y": 384,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.88,
                        "resolution_x": 640,
                        "resolution_y": 400,
                    },
                    {
                        "aspect_ratio": "8:5",
                        "refresh_rate": 59.98,
                        "resolution_x": 640,
                        "resolution_y": 400,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.86,
                        "resolution_x": 640,
                        "resolution_y": 360,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.83,
                        "resolution_x": 640,
                        "resolution_y": 360,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.84,
                        "resolution_x": 640,
                        "resolution_y": 360,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.32,
                        "resolution_x": 640,
                        "resolution_y": 360,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.0,
                        "resolution_x": 512,
                        "resolution_y": 384,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 60.0,
                        "resolution_x": 512,
                        "resolution_y": 288,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.92,
                        "resolution_x": 512,
                        "resolution_y": 288,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.63,
                        "resolution_x": 480,
                        "resolution_y": 270,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.82,
                        "resolution_x": 480,
                        "resolution_y": 270,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.32,
                        "resolution_x": 400,
                        "resolution_y": 300,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 56.34,
                        "resolution_x": 400,
                        "resolution_y": 300,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.92,
                        "resolution_x": 432,
                        "resolution_y": 243,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.57,
                        "resolution_x": 432,
                        "resolution_y": 243,
                    },
                    {
                        "aspect_ratio": "4:3",
                        "refresh_rate": 60.05,
                        "resolution_x": 320,
                        "resolution_y": 240,
                    },
                    {
                        "aspect_ratio": "180:101",
                        "refresh_rate": 59.51,
                        "resolution_x": 360,
                        "resolution_y": 202,
                    },
                    {
                        "aspect_ratio": "180:101",
                        "refresh_rate": 59.13,
                        "resolution_x": 360,
                        "resolution_y": 202,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.84,
                        "resolution_x": 320,
                        "resolution_y": 180,
                    },
                    {
                        "aspect_ratio": "16:9",
                        "refresh_rate": 59.32,
                        "resolution_x": 320,
                        "resolution_y": 180,
                    },
                ],
                "preferred_mode": {
                    "aspect_ratio": "16:9",
                    "refresh_rate": 60.0,
                    "resolution_x": 3840,
                    "resolution_y": 2160,
                },
                "props": {
                    "_MUTTER_PRESENTATION_OUTPUT": {
                        "name": "_MUTTER_PRESENTATION_OUTPUT",
                        "value": "0",
                    },
                    "EDID": {
                        "name": "EDID",
                        "value": "00ffffffffffff0009e5f30700000000011c0104a5221378037b80a6544d9b26115054000000010101010101010101010101010101014dd000a0f0703e803020a50058c21000001ae08a00a0f0703e803020a50058c21000001a00000000000000000000000000000000000000000002000a29ff0f3cc823123cc800000000ea",
                    },
                    "scaling mode": {
                        "name": "scaling mode",
                        "value": "Full aspect",
                        "supported_values": ["Full", "Center", "Full aspect"],
                    },
                    "Colorspace": {
                        "name": "Colorspace",
                        "value": "Default",
                        "supported_values": [
                            "Default",
                            "RGB_Wide_Gamut_Fixed_Point",
                            "RGB_Wide_Gamut_Floating_Point",
                            "opRGB",
                            "DCI-P3_RGB_D65",
                            "BT2020_RGB",
                            "BT601_YCC",
                            "BT709_YCC",
                            "XVYCC_601",
                            "XVYCC_709",
                            "SYCC_601",
                            "opYCC_601",
                            "BT2020_CYCC",
                            "BT2020_YCC",
                        ],
                    },
                    "max bpc": {
                        "name": "max bpc",
                        "int_value": 12,
                        "int_value_min": 6,
                        "int_value_max": 12,
                        "value": "12",
                    },
                    "Broadcast RGB": {
                        "name": "Broadcast RGB",
                        "value": "Automatic",
                        "supported_values": ["Automatic", "Full", "Limited 16:235"],
                    },
                    "panel orientation": {
                        "name": "panel orientation",
                        "value": "Normal",
                        "supported_values": [
                            "Normal",
                            "Upside Down",
                            "Left Side Up",
                            "Right Side Up",
                        ],
                    },
                    "link-status": {
                        "name": "link-status",
                        "value": "Good",
                        "supported_values": ["Good", "Bad"],
                    },
                    "CTM": {
                        "name": "CTM",
                        "value": "0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 00 1",
                    },
                    "CONNECTOR_ID": {
                        "name": "CONNECTOR_ID",
                        "value": "95",
                        "supported_values": ["95"],
                    },
                    "non-desktop": {
                        "name": "non-desktop",
                        "int_value": 0,
                        "int_value_min": 0,
                        "int_value_max": 1,
                        "value": "0",
                    },
                },
            },
            "DP-1": {
                "is_primary": False,
                "name": "DP-1",
                "state": "disconnected",
                "current_mode": None,
                "preferred_mode": None,
                "modes": [],
                "props": {
                    "HDCP Content Type": {
                        "name": "HDCP Content Type",
                        "value": "HDCP Type0",
                        "supported_values": ["HDCP Type0", "HDCP Type1"],
                    },
                    "Content Protection": {
                        "name": "Content Protection",
                        "value": "Undesired",
                        "supported_values": ["Undesired", "Desired", "Enabled"],
                    },
                    "Colorspace": {
                        "name": "Colorspace",
                        "value": "Default",
                        "supported_values": [
                            "Default",
                            "RGB_Wide_Gamut_Fixed_Point",
                            "RGB_Wide_Gamut_Floating_Point",
                            "opRGB",
                            "DCI-P3_RGB_D65",
                            "BT2020_RGB",
                            "BT601_YCC",
                            "BT709_YCC",
                            "XVYCC_601",
                            "XVYCC_709",
                            "SYCC_601",
                            "opYCC_601",
                            "BT2020_CYCC",
                            "BT2020_YCC",
                        ],
                    },
                    "max bpc": {
                        "name": "max bpc",
                        "int_value": 12,
                        "int_value_min": 6,
                        "int_value_max": 12,
                        "value": "12",
                    },
                    "Broadcast RGB": {
                        "name": "Broadcast RGB",
                        "value": "Automatic",
                        "supported_values": ["Automatic", "Full", "Limited 16:235"],
                    },
                    "audio": {
                        "name": "audio",
                        "value": "auto",
                        "supported_values": ["force-dvi", "off", "auto", "on"],
                    },
                    "subconnector": {
                        "name": "subconnector",
                        "value": "Unknown",
                        "supported_values": [
                            "Unknown",
                            "VGA",
                            "DVI-D",
                            "HDMI",
                            "DP",
                            "Wireless",
                            "Native",
                        ],
                    },
                    "link-status": {
                        "name": "link-status",
                        "value": "Good",
                        "supported_values": ["Good", "Bad"],
                    },
                    "CTM": {
                        "name": "CTM",
                        "value": "0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 00 1",
                    },
                    "CONNECTOR_ID": {
                        "name": "CONNECTOR_ID",
                        "value": "103",
                        "supported_values": ["103"],
                    },
                    "non-desktop": {
                        "name": "non-desktop",
                        "int_value": 0,
                        "int_value_min": 0,
                        "int_value_max": 1,
                        "value": "0",
                    },
                },
            },
            "HDMI-1": {
                "is_primary": False,
                "name": "HDMI-1",
                "state": "disconnected",
                "current_mode": None,
                "preferred_mode": None,
                "modes": [],
                "props": {
                    "HDCP Content Type": {
                        "name": "HDCP Content Type",
                        "value": "HDCP Type0",
                        "supported_values": ["HDCP Type0", "HDCP Type1"],
                    },
                    "Content Protection": {
                        "name": "Content Protection",
                        "value": "Undesired",
                        "supported_values": ["Undesired", "Desired", "Enabled"],
                    },
                    "max bpc": {
                        "name": "max bpc",
                        "int_value": 12,
                        "int_value_min": 8,
                        "int_value_max": 12,
                        "value": "12",
                    },
                    "content type": {
                        "name": "content type",
                        "value": "No Data",
                        "supported_values": [
                            "No Data",
                            "Graphics",
                            "Photo",
                            "Cinema",
                            "Game",
                        ],
                    },
                    "Colorspace": {
                        "name": "Colorspace",
                        "value": "Default",
                        "supported_values": [
                            "Default",
                            "SMPTE_170M_YCC",
                            "BT709_YCC",
                            "XVYCC_601",
                            "XVYCC_709",
                            "SYCC_601",
                            "opYCC_601",
                            "opRGB",
                            "BT2020_CYCC",
                            "BT2020_RGB",
                            "BT2020_YCC",
                            "DCI-P3_RGB_D65",
                            "DCI-P3_RGB_Theater",
                        ],
                    },
                    "aspect ratio": {
                        "name": "aspect ratio",
                        "value": "Automatic",
                        "supported_values": ["Automatic", "4:3", "16:9"],
                    },
                    "Broadcast RGB": {
                        "name": "Broadcast RGB",
                        "value": "Automatic",
                        "supported_values": ["Automatic", "Full", "Limited 16:235"],
                    },
                    "audio": {
                        "name": "audio",
                        "value": "auto",
                        "supported_values": ["force-dvi", "off", "auto", "on"],
                    },
                    "link-status": {
                        "name": "link-status",
                        "value": "Good",
                        "supported_values": ["Good", "Bad"],
                    },
                    "CTM": {
                        "name": "CTM",
                        "value": "0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 00 1",
                    },
                    "CONNECTOR_ID": {
                        "name": "CONNECTOR_ID",
                        "value": "113",
                        "supported_values": ["113"],
                    },
                    "non-desktop": {
                        "name": "non-desktop",
                        "int_value": 0,
                        "int_value_min": 0,
                        "int_value_max": 1,
                        "value": "0",
                    },
                },
            },
            "DP-2": {
                "is_primary": False,
                "name": "DP-2",
                "state": "disconnected",
                "current_mode": None,
                "preferred_mode": None,
                "modes": [],
                "props": {
                    "HDCP Content Type": {
                        "name": "HDCP Content Type",
                        "value": "HDCP Type0",
                        "supported_values": ["HDCP Type0", "HDCP Type1"],
                    },
                    "Content Protection": {
                        "name": "Content Protection",
                        "value": "Undesired",
                        "supported_values": ["Undesired", "Desired", "Enabled"],
                    },
                    "Colorspace": {
                        "name": "Colorspace",
                        "value": "Default",
                        "supported_values": [
                            "Default",
                            "RGB_Wide_Gamut_Fixed_Point",
                            "RGB_Wide_Gamut_Floating_Point",
                            "opRGB",
                            "DCI-P3_RGB_D65",
                            "BT2020_RGB",
                            "BT601_YCC",
                            "BT709_YCC",
                            "XVYCC_601",
                            "XVYCC_709",
                            "SYCC_601",
                            "opYCC_601",
                            "BT2020_CYCC",
                            "BT2020_YCC",
                        ],
                    },
                    "max bpc": {
                        "name": "max bpc",
                        "int_value": 12,
                        "int_value_min": 6,
                        "int_value_max": 12,
                        "value": "12",
                    },
                    "Broadcast RGB": {
                        "name": "Broadcast RGB",
                        "value": "Automatic",
                        "supported_values": ["Automatic", "Full", "Limited 16:235"],
                    },
                    "audio": {
                        "name": "audio",
                        "value": "auto",
                        "supported_values": ["force-dvi", "off", "auto", "on"],
                    },
                    "subconnector": {
                        "name": "subconnector",
                        "value": "Unknown",
                        "supported_values": [
                            "Unknown",
                            "VGA",
                            "DVI-D",
                            "HDMI",
                            "DP",
                            "Wireless",
                            "Native",
                        ],
                    },
                    "link-status": {
                        "name": "link-status",
                        "value": "Good",
                        "supported_values": ["Good", "Bad"],
                    },
                    "CTM": {
                        "name": "CTM",
                        "value": "0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 00 1",
                    },
                    "CONNECTOR_ID": {
                        "name": "CONNECTOR_ID",
                        "value": "119",
                        "supported_values": ["119"],
                    },
                    "non-desktop": {
                        "name": "non-desktop",
                        "int_value": 0,
                        "int_value_min": 0,
                        "int_value_max": 1,
                        "value": "0",
                    },
                },
            },
            "HDMI-2": {
                "is_primary": False,
                "name": "HDMI-2",
                "state": "disconnected",
                "current_mode": None,
                "preferred_mode": None,
                "modes": [],
                "props": {
                    "HDCP Content Type": {
                        "name": "HDCP Content Type",
                        "value": "HDCP Type0",
                        "supported_values": ["HDCP Type0", "HDCP Type1"],
                    },
                    "Content Protection": {
                        "name": "Content Protection",
                        "value": "Undesired",
                        "supported_values": ["Undesired", "Desired", "Enabled"],
                    },
                    "max bpc": {
                        "name": "max bpc",
                        "int_value": 12,
                        "int_value_min": 8,
                        "int_value_max": 12,
                        "value": "12",
                    },
                    "content type": {
                        "name": "content type",
                        "value": "No Data",
                        "supported_values": [
                            "No Data",
                            "Graphics",
                            "Photo",
                            "Cinema",
                            "Game",
                        ],
                    },
                    "Colorspace": {
                        "name": "Colorspace",
                        "value": "Default",
                        "supported_values": [
                            "Default",
                            "SMPTE_170M_YCC",
                            "BT709_YCC",
                            "XVYCC_601",
                            "XVYCC_709",
                            "SYCC_601",
                            "opYCC_601",
                            "opRGB",
                            "BT2020_CYCC",
                            "BT2020_RGB",
                            "BT2020_YCC",
                            "DCI-P3_RGB_D65",
                            "DCI-P3_RGB_Theater",
                        ],
                    },
                    "aspect ratio": {
                        "name": "aspect ratio",
                        "value": "Automatic",
                        "supported_values": ["Automatic", "4:3", "16:9"],
                    },
                    "Broadcast RGB": {
                        "name": "Broadcast RGB",
                        "value": "Automatic",
                        "supported_values": ["Automatic", "Full", "Limited 16:235"],
                    },
                    "audio": {
                        "name": "audio",
                        "value": "auto",
                        "supported_values": ["force-dvi", "off", "auto", "on"],
                    },
                    "link-status": {
                        "name": "link-status",
                        "value": "Good",
                        "supported_values": ["Good", "Bad"],
                    },
                    "CTM": {
                        "name": "CTM",
                        "value": "0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 00 1",
                    },
                    "CONNECTOR_ID": {
                        "name": "CONNECTOR_ID",
                        "value": "125",
                        "supported_values": ["125"],
                    },
                    "non-desktop": {
                        "name": "non-desktop",
                        "int_value": 0,
                        "int_value_min": 0,
                        "int_value_max": 1,
                        "value": "0",
                    },
                },
            },
            "DP-3": {
                "is_primary": False,
                "name": "DP-3",
                "state": "disconnected",
                "current_mode": None,
                "preferred_mode": None,
                "modes": [],
                "props": {
                    "HDCP Content Type": {
                        "name": "HDCP Content Type",
                        "value": "HDCP Type0",
                        "supported_values": ["HDCP Type0", "HDCP Type1"],
                    },
                    "Content Protection": {
                        "name": "Content Protection",
                        "value": "Undesired",
                        "supported_values": ["Undesired", "Desired", "Enabled"],
                    },
                    "Colorspace": {
                        "name": "Colorspace",
                        "value": "Default",
                        "supported_values": [
                            "Default",
                            "RGB_Wide_Gamut_Fixed_Point",
                            "RGB_Wide_Gamut_Floating_Point",
                            "opRGB",
                            "DCI-P3_RGB_D65",
                            "BT2020_RGB",
                            "BT601_YCC",
                            "BT709_YCC",
                            "XVYCC_601",
                            "XVYCC_709",
                            "SYCC_601",
                            "opYCC_601",
                            "BT2020_CYCC",
                            "BT2020_YCC",
                        ],
                    },
                    "max bpc": {
                        "name": "max bpc",
                        "int_value": 12,
                        "int_value_min": 6,
                        "int_value_max": 12,
                        "value": "12",
                    },
                    "Broadcast RGB": {
                        "name": "Broadcast RGB",
                        "value": "Automatic",
                        "supported_values": ["Automatic", "Full", "Limited 16:235"],
                    },
                    "audio": {
                        "name": "audio",
                        "value": "auto",
                        "supported_values": ["force-dvi", "off", "auto", "on"],
                    },
                    "subconnector": {
                        "name": "subconnector",
                        "value": "Unknown",
                        "supported_values": [
                            "Unknown",
                            "VGA",
                            "DVI-D",
                            "HDMI",
                            "DP",
                            "Wireless",
                            "Native",
                        ],
                    },
                    "link-status": {
                        "name": "link-status",
                        "value": "Good",
                        "supported_values": ["Good", "Bad"],
                    },
                    "CTM": {
                        "name": "CTM",
                        "value": "0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 00 1",
                    },
                    "CONNECTOR_ID": {
                        "name": "CONNECTOR_ID",
                        "value": "129",
                        "supported_values": ["129"],
                    },
                    "non-desktop": {
                        "name": "non-desktop",
                        "int_value": 0,
                        "int_value_min": 0,
                        "int_value_max": 1,
                        "value": "0",
                    },
                },
            },
            "HDMI-3": {
                "is_primary": False,
                "name": "HDMI-3",
                "state": "disconnected",
                "current_mode": None,
                "preferred_mode": None,
                "modes": [],
                "props": {
                    "HDCP Content Type": {
                        "name": "HDCP Content Type",
                        "value": "HDCP Type0",
                        "supported_values": ["HDCP Type0", "HDCP Type1"],
                    },
                    "Content Protection": {
                        "name": "Content Protection",
                        "value": "Undesired",
                        "supported_values": ["Undesired", "Desired", "Enabled"],
                    },
                    "max bpc": {
                        "name": "max bpc",
                        "int_value": 12,
                        "int_value_min": 8,
                        "int_value_max": 12,
                        "value": "12",
                    },
                    "content type": {
                        "name": "content type",
                        "value": "No Data",
                        "supported_values": [
                            "No Data",
                            "Graphics",
                            "Photo",
                            "Cinema",
                            "Game",
                        ],
                    },
                    "Colorspace": {
                        "name": "Colorspace",
                        "value": "Default",
                        "supported_values": [
                            "Default",
                            "SMPTE_170M_YCC",
                            "BT709_YCC",
                            "XVYCC_601",
                            "XVYCC_709",
                            "SYCC_601",
                            "opYCC_601",
                            "opRGB",
                            "BT2020_CYCC",
                            "BT2020_RGB",
                            "BT2020_YCC",
                            "DCI-P3_RGB_D65",
                            "DCI-P3_RGB_Theater",
                        ],
                    },
                    "aspect ratio": {
                        "name": "aspect ratio",
                        "value": "Automatic",
                        "supported_values": ["Automatic", "4:3", "16:9"],
                    },
                    "Broadcast RGB": {
                        "name": "Broadcast RGB",
                        "value": "Automatic",
                        "supported_values": ["Automatic", "Full", "Limited 16:235"],
                    },
                    "audio": {
                        "name": "audio",
                        "value": "auto",
                        "supported_values": ["force-dvi", "off", "auto", "on"],
                    },
                    "link-status": {
                        "name": "link-status",
                        "value": "Good",
                        "supported_values": ["Good", "Bad"],
                    },
                    "CTM": {
                        "name": "CTM",
                        "value": "0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 00 1",
                    },
                    "CONNECTOR_ID": {
                        "name": "CONNECTOR_ID",
                        "value": "135",
                        "supported_values": ["135"],
                    },
                    "non-desktop": {
                        "name": "non-desktop",
                        "int_value": 0,
                        "int_value_min": 0,
                        "int_value_max": 1,
                        "value": "0",
                    },
                },
            },
        },
        sort_keys=True,
        indent=2,
    )
