#!/bin/sh
set -e

usage() {
  echo "Usage: $0 <boot-folder> <key-folder> <kernel-version> <output>"
  exit 1
}

if [ "$#" -ne 4 ]; then
  usage
fi

boot_folder=$1
key_folder=$2
kernel_version=$3
output=$4

kernel_image="${boot_folder}/vmlinuz-${kernel_version}"
initrd_image="${boot_folder}/initrd.img-${kernel_version}"
os_release=$(basename "$output")

# NOTE: By default, halt on emergency instead of dropping to shell for security
ukify build \
  --linux="$kernel_image" \
  --initrd="$initrd_image" \
  --uname="${kernel_version}" \
  --os-release="$os_release" \
  --cmdline="rd.emergency=halt rd.shell=0" \
  --pcr-private-key="${key_folder}/tpm2-pcr-private-key.pem" \
  --pcr-public-key="${key_folder}/tpm2-pcr-public-key.pem" \
  --pcr-banks=sha1,sha256 \
  --output "$output" \
  --measure
