#!/bin/sh
set -e

usage() {
  echo "Usage: $0 <cmdline> <output>"
  exit 1
}

if [ "$#" -ne 2 ]; then
  usage
fi

cmdline=$1
output=$2
output_basename=$(basename "$output")

# Todo: Check SBAT
ukify build \
  --cmdline="$cmdline" \
  --sbat="sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
  $output_basename.puavo-os,1,kernel-command-line-addon,$output_basename.puavo-os,1,https://github.com/puavo-org/puavo-os" \
  --output="$output"
