#!/bin/sh
set -e

usage() {
  echo "Usage: $0 <boot-folder> <key-folder> <image-file>"
  exit 1
}

if [ "$#" -ne 3 ]; then
  usage
fi

boot_folder=$1
key_folder=$2
image_file=$3

for kernel_image in "$boot_folder"/vmlinuz-*; do
  test -h "$kernel_image" && continue
  kernel_version=$(basename "$kernel_image" | sed 's/vmlinuz-//')
  output_path="${boot_folder}/kernel-${kernel_version}.uki.efi"
  .aux/create-uki "$boot_folder" "$key_folder" "$kernel_version" "$output_path"
done

addon_folder="$boot_folder/addons"
mkdir -p "$addon_folder"

common_arguments='ro rd.auto=1 init=/sbin/init-puavo'
.aux/create-cmdline-addon "$key_folder" "nosplash ${common_arguments} puavo.hosttype=bootserver puavo.image.path=/images/${image_file}"                                           "${addon_folder}/bootserver.addon.efi"
.aux/create-cmdline-addon "$key_folder" "nosplash ${common_arguments} puavo.hosttype=diskinstaller puavo.image.path=/installimages/${image_file}"                                 "${addon_folder}/diskinstaller.addon.efi"
.aux/create-cmdline-addon "$key_folder" "quiet loglevel=3 splash ${common_arguments} puavo.hosttype=exam puavo.image.path=/examimages/${image_file} puavo.image.load_to_ram=true" "${addon_folder}/exam.addon.efi"
.aux/create-cmdline-addon "$key_folder" "quiet loglevel=3 splash ${common_arguments} puavo.hosttype=laptop puavo.image.path=/images/${image_file}"                                "${addon_folder}/laptop.addon.efi"
.aux/create-cmdline-addon "$key_folder" "nosplash ${common_arguments} puavo.hosttype=preinstalled puavo.image.path=/images/${image_file}"                                         "${addon_folder}/preinstalled.addon.efi"
