#!/bin/sh
set -e

usage() {
  echo "Usage: $0 <boot-folder> <key-folder> <image-file> <output-name>"
  exit 1
}

if [ "$#" -ne 4 ]; then
  usage
fi

boot_folder=$1
key_folder=$2
image_file=$3
output_name=$4

.aux/create-uki "$boot_folder" "$key_folder" "${boot_folder}/${output_name}"

addon_folder="$boot_folder/addons"
mkdir -p "$addon_folder"

.aux/create-cmdline-addon "ro splash loglevel=3 rd.auto=1 init=/sbin/init-puavo puavo.hosttype=diskinstaller puavo.image.path=/installimages/${image_file}" "${addon_folder}/diskinstaller.addon.efi"
.aux/create-cmdline-addon "ro splash loglevel=3 rd.auto=1 init=/sbin/init-puavo puavo.hosttype=preinstalled puavo.image.path=/images/${image_file}" "${addon_folder}/preinstalled.addon.efi"
.aux/create-cmdline-addon "ro splash loglevel=3 rd.auto=1 init=/sbin/init-puavo puavo.hosttype=laptop puavo.image.path=/images/${image_file}" "${addon_folder}/laptop.addon.efi"
