#!/bin/sh
set -eu

echo "generating Secure Boot certificates..."

# Generate a unique owner GUID that associates all generated
# certificates as belonging to the same entity in UEFI firmware.
guid=$(uuidgen)

# Generate certificates
openssl req -new -x509 -newkey rsa:4096 -nodes -days 36500 \
  -subj "/CN=Puavo PK, O=Puavo/" \
  -keyout PK.key -out PK.crt

openssl req -new -x509 -newkey rsa:4096 -nodes -days 36500 \
  -subj "/CN=Puavo KEK, O=Puavo/" \
  -keyout KEK.key -out KEK.crt

openssl req -new -x509 -newkey rsa:4096 -nodes -days 36500 \
  -subj "/CN=Puavo DB, O=Puavo/" \
  -keyout db.key -out db.crt

# Convert certificates to EFI signature lists
cert-to-efi-sig-list -g "$guid" PK.crt PK.final.esl
cert-to-efi-sig-list -g "$guid" KEK.crt KEK.final.esl
cert-to-efi-sig-list -g "$guid" db.crt db.esl

# Signature lists can be combined, but here we only have one certificate per list
cat db.esl > db.final.esl

# Sign the signature lists
sign-efi-sig-list -k PK.key -c PK.crt PK PK.final.esl PK.auth
sign-efi-sig-list -k PK.key -c PK.crt KEK KEK.final.esl KEK.auth
sign-efi-sig-list -k KEK.key -c KEK.crt db db.final.esl db.auth

# Clean up intermediate files
rm -f *.esl

echo "generated Secure Boot certificates successfully"
