#!/bin/bash

set -eu

cd /srv/aptirepo

old_version=$(readlink latest)

if [ $# -eq 0 ]; then
    new_version=$((old_version + 1))
elif [ $# -eq 1 ]; then
    new_version=$1
    shift
else
    echo "E: invalid number of arguments ($#), expected 0" >&2
    exit 1
fi

if [ -e "${new_version}" ]; then
    echo "E: version ${new_version} already exists" >&2
    exit 1
fi

cp -n -a "${old_version}" "${new_version}"

echo "Created new repository: /srv/aptirepo/${new_version}"
