#!/bin/sh

set -eu

openqa-cli api -X POST jobs                    \
  ARCH=x86_64                                  \
  DISTRI=debian                                \
  FLAVOR=cloud                                 \
  HDD_1=debian-12-genericcloud-amd64-20G.qcow2 \
  ISO=debian-cloud-init.iso                    \
  QEMURAM=2048                                 \
  NICTYPE=tap                                  \
  NICVLAN=0                                    \
  SCHEDULE=install_puavo_standalone            \
  TEST=install-puavo-standalone                \
  VERSION=bookworm
