#! /bin/sh

set -e

case "$1" in
    purge)
        # Remove inetd entry
	if [ -x "`which update-inetd 2>/dev/null`" ]; then
            update-inetd --pattern cups-lpd --remove printer 2>/dev/null || true
        fi

        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac

#DEBHELPER#
