#!/bin/sh

set -eu

HOSTNAME=$(hostname)
TIMESTAMP=$(date +"%Y%m%d-%H%M%S.%N")
CONF_DIR="${HOME}/.config/puavomenu"

if [ ! -d "${CONF_DIR}" ]; then
    mkdir -p "${CONF_DIR}"
fi

# Development or production mode? Development mode is the default.
DEV_MODE=1

if [ $# -gt 0 ]; then
    if [ "$1" = "--prod" ]; then
        DEV_MODE=0
    fi
fi

if [ $DEV_MODE -eq 1 ]; then
    # Development mode. Assume this is a local copy of the
    # puavo-os/opinsys-os repo.
    ./puavomenu \
        --res_dir "./res" \
        --menu_dir "../../rules/puavomenu/templates" \
        --user_dir "${CONF_DIR}" \
        --socket "${XDG_RUNTIME_DIR}/puavomenu_dev" \
        "$@" &
else
    # Production mode. Use real paths.
    /opt/puavomenu/puavomenu \
        --prod \
        --autohide \
        --log "/tmp/puavomenu_${TIMESTAMP}.log" \
        --res_dir "/opt/puavomenu/res" \
        --menu_dir "/etc/puavomenu/" \
        --user_dir "${CONF_DIR}" \
        --socket "${XDG_RUNTIME_DIR}/puavomenu" \
        &

    # Set the sticky bit to prevent automatic cleanup processes from
    # deleting the socket
    chmod u+t "${XDG_RUNTIME_DIR}/puavomenu"
fi
