#!/usr/bin/python3

# Welcome to PuavoMenu, the modern (?) WebMenu replacement.

import argparse


# Some kind of a help text
epilog = """
Socket names and IPC commands
-----------------------------
PuavoMenu uses a Unix domain socket for IPC. You can use it to send simple
commands to it. See send_command for more information. The main PuavoMenu
instance uses a socket file ~/.config/puavomenu/socket_(hostname); if
you're running other copies of PuavoMenu, you *need* to use other socket
names, so the commands you send to your copies do not interfere with the
system menu.

Known IPC commands are:
    show: Show the menu
    hide: Hide the menu
    toggle: Show or hide the menu, depending on its current visibility

'show' and 'toggle' also accept a position parameter, which tells the
menu where the window should be shown at. Known positions are:

    center: Center the window around the mouse cursor
    corner <X> <Y>: Position the lower left corner at (X, Y)

Examples on positioning:

    show corner 115 68: This shows the window and moves it so that the
                        lower left corner is located at (115, 68).
    show corner: Shows the window at whatever position it happens to
                 be at.
    show center: Shows the window and centers it around the mouse cursor.

Language codes
--------------
Like its predecessor, WebMenu, PuavoMenu supports multiple languages.
The language code is simply a two-letter code, like "fi", or "en". You
can use --lang=<code> to specify which language you want to use. If
--lang is omitted, PuavoMenu looks up LANG and GDM_LANG environment
variables (in that order) and takes the first two letters form its
value, lowercases them and then compares them to known languages. If
the environment variable(s) are missing, or the code is invalid, the
language defaults to English (en). Known language codes are:
    fi, en, sv, de.
"""

parser = argparse.ArgumentParser(
    formatter_class=argparse.RawDescriptionHelpFormatter,
    epilog=epilog)

parser.add_argument('--lang',
                    type=str,
                    required=False,
                    default=None,   # force autodetection
                    help='language code (see documentation)')

parser.add_argument('--log',
                    type=str,
                    required=False,
                    help='log file name (if omitted, logs to console)')

parser.add_argument('--autohide',
                    action='store_true',
                    required=False,
                    help='enable window autohide (use this in production!)')

parser.add_argument('--dev',
                    action='store_true',
                    required=False,
                    help='enable development mode')

parser.add_argument('--check',
                    action='store_true',
                    required=False,
                    help='load and verify all menu data files')

required = parser.add_argument_group('required arguments')

required.add_argument('--res_dir',
                      required=True,
                      type=str,
                      help='location of PuavoMenu\'s own resources')

required.add_argument('--menu_dir',
                      required=True,
                      type=str,
                      help='location of the menu data')

required.add_argument('--user_dir',
                      required=True,
                      type=str,
                      help='location of user-specific data (faves, etc.)')

required.add_argument('--socket',
                      required=True,
                      help='IPC command socket name')

args = parser.parse_args()

import os
import os.path
import logging
import time

from settings import SETTINGS

if args.log:
    # log to file
    logging.basicConfig(filename=args.log,
                        format='%(asctime)s %(levelname)s: %(message)s',
                        level=logging.DEBUG)
else:
    # log to console
    logging.basicConfig(format='%(asctime)s %(levelname)s: %(message)s',
                        level=logging.DEBUG)

logging.info('Logging starts')
logging.info('This is PuavoMenu v0.61 (c) Opinsys Oy 2017-2018')

SETTINGS.res_dir = os.path.join(args.res_dir, '')
SETTINGS.menu_dir = os.path.join(args.menu_dir, '')
SETTINGS.user_dir = os.path.join(args.user_dir, '')
SETTINGS.socket = args.socket
SETTINGS.dev_mode = args.dev
SETTINGS.autohide = args.autohide
SETTINGS.check_mode = args.check

if not args.dev and args.check:
    SETTINGS.check_mode = False

if args.lang:
    # Override autodetection
    SETTINGS.language = args.lang.lower()
else:
    # Autodetect from system
    if 'LANG' in os.environ:
        SETTINGS.language = os.environ['LANG'][0:2].lower()
    elif 'GDM_LANG' in os.environ:
        SETTINGS.language = os.environ['GDM_LANG'][0:2].lower()

# Regardless of where the language code comes from we validate it
if SETTINGS.language not in ('en', 'fi', 'sv', 'de'):
    logging.error('Invalid language code "%s", defaulting to "en"',
                  SETTINGS.language)
    SETTINGS.language = 'en'

logging.info('Resource directory.: "%s"', SETTINGS.res_dir)
logging.info('Menu data directory: "%s"', SETTINGS.menu_dir)
logging.info('User directory.....: "%s"', SETTINGS.user_dir)
logging.info('IPC socket name....: "%s"', SETTINGS.socket)
logging.info('Language code......: "%s"', SETTINGS.language)

if args.log:
    logging.info('Log (this) file....: "%s"', args.log)

# Detect the non-configurable settings
SETTINGS.detect_environment()

logging.info('Desktop directory..: "%s"', SETTINGS.desktop_dir)

if SETTINGS.dev_mode:
    logging.info('*** Development mode activated ***')

if SETTINGS.check_mode:
    logging.info('*** Configuration check mode ***')

if SETTINGS.autohide:
    logging.info('*** Autohide enabled ***')

logging.info('=' * 50)

# And go!
try:
    if SETTINGS.check_mode:
        # Only load and validate menu data, then exit
        import menudata
        menudata.Menudata().load()
    else:
        import_start = time.clock()
        import utils
        import main
        import_end = time.clock()

        utils.log_elapsed_time('Main import time', import_start, import_end)
        main.run()

except Exception as exception:
    # This is bad. Very bad. The exception bubbled all the way up to here,
    # so this is fatal.
    logging.critical(str(exception))

    import syslog
    syslog.syslog(syslog.LOG_CRIT, str(exception))

# Clean exit
logging.info('=' * 50)
logging.info('Shutdown complete')
logging.info('Logging ends')
logging.shutdown()

exit(0)
