#!/bin/sh

set -eu

export LANG=fi_FI.UTF-8
export TERM=vt100
setupcon
clear

printf "\
The kernel has crashed and the incident will be reported to system \
administrators. The system will reboot automatically after the report has been \
sent. If you want to skip reporting, type q and press ENTER.\
\n"

while true; do
    read -p "> " key
    [ "${key}" = "q" ] && break
done

reboot -f
