#!/bin/sh

export LANG=fi_FI.UTF-8
export TERM=vt100
setupcon
clear

dhclient eth0 &

echo
echo
echo 'This host is a wireless access point.'
echo
echo 'You can reboot this host by pressing ENTER.'
read answer
reboot
