#!/bin/bash
#
# ##############################################################################
#
# Copyright (C) 2014 Opinsys Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# ##############################################################################
#
# Author: Tuomas Räsänen <tuomasjjrasanen@tjjr.fi>

set -eu

. "${RESTRICTED_PKG_LIBDIR}/common.bash"

usage_error()
{
    echo "error $1" >&2
    echo "Try 'puavo-restricted-package-tool download --help' for more information." >&2
    return 1
}

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            shift
            echo "Usage: puavo-restricted-package-tool download PACKAGE"
            echo "Usage: puavo-restricted-package-tool download --all"
            echo "Usage: puavo-restricted-package-tool download --help"
            echo
            echo "Download a restricted package."
            echo
            echo "Options:"
            echo "    -h, --help                   print help and exit"
            echo "    --all                        download all available packages"
            echo
            exit 0
            ;;
        --all)
            shift
            packages=$(puavo-restricted-package-tool list \
                | awk '{ if ($3 == "PURGED") print $1 }')
            set -- ${packages}
            [ $# -eq 0 ] && exit 0
            break
            ;;
        --)
            shift
            break
            ;;
        -*)
            usage_error "invalid argument '$1'"
            ;;
        *)
            break
            ;;
    esac
done

if [ $# -lt 1 ]; then
    usage_error "invalid number of arguments ($#), expected at least 1"
fi

exitval=0

for package in "$@"; do
    "${RESTRICTED_PKG_LIBDIR}/helpers/download" "${package}" || {
        exitval=$?
        echo "E: failed to download package '${package}'" >&2
        # Continue until we have tried to download all given packages
        # and then fail.
    }
done

exit $exitval
