#!/bin/sh
#
# ##############################################################################
#
# Copyright (C) 2014 Opinsys Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# ##############################################################################
#
# Author: Tuomas Räsänen <tuomasjjrasanen@tjjr.fi>

set -eu

usage_error()
{
    echo "error $1" >&2
    echo "Try 'puavo-restricted-package-tool uninstall --help' for more information." >&2
    return 1
}

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            shift
            echo "Usage: puavo-restricted-package-tool uninstall PACKAGE"
            echo "Usage: puavo-restricted-package-tool uninstall --help"
            echo
            echo "Uninstall a restricted package."
            echo
            echo "Options:"
            echo "    -h, --help                   print help and exit"
            echo
            exit 0
            ;;
        --)
            shift
            break
            ;;
        -*)
            usage_error "invalid argument '$1'"
            ;;
        *)
            break
            ;;
    esac
done

if [ $# -ne 1 ]; then
    usage_error "invalid number of arguments ($#), expected 1"
fi

package=$1
shift

installdir="/state/restricted-packages/${package}/i"

if [ -x "/usr/share/puavo-ltsp-client/restricted-packages/${package}/prerm" ]; then
    "/usr/share/puavo-ltsp-client/restricted-packages/${package}/prerm" "${installdir}"
fi

rm -rf "${installdir}"

exit 0
