#!/bin/sh

set -eu

# XXX could also be conditional based on some puavo-conf

if [ "${EXAMMODE_SESSION:-}" = 'true' -o "${GUEST_SESSION:-}" = 'true' ]; then
  exit 0
fi

exec puavo-exammode-setup-applet "$@"
