#!/bin/sh

set -eu

## Find suitable WLAN interfaces and print their names to stdout, one
## per line.

. puavo-wlanap-env

if [ $# -ne 1 ]; then
    echo "$(basename $0): wrong number of arguments" >&2
    echo "Usage: $(basename $0) HW_MODE" >&2
    exit 1
fi

hw_mode=$1

for path in /sys/class/net/*; do
    iface=$(basename "${path}")

    ## We are only interested in wlan interfaces.
    grep -q '^DEVTYPE=wlan$' "${path}/uevent" || continue

    ## Find its driver.
    driver=$(sed -rn 's/^DRIVER=(.*)$/\1/p' "${path}/device/uevent")
    [ -n "${driver}" ] || {
        pwap_log "driver not found for ${iface}, ignoring"
        continue
    }

    ## Ignore if the driver is not whitelisted.
    grep -q "${driver}" "${PWAP_DATADIR}/supported_drivers" \
        || continue

    ## Ignore if it is of wrong type, i.e. the iwconfig output does
    ## not include the hw_mode char.
    iwconfig "${iface}" | sed -rn '1 s/^.*IEEE 802.11([a-z]+).*/\1/p' \
        | grep -q "${hw_mode}" || continue

    ## All tests passed, the current interface meets our
    ## requirements. Print its interface name.
    echo "${iface}"
done
