#!/bin/bash

set -eu

if [ $# -ne 1 ]; then
    echo "$(basename $0): wrong number of arguments ($#)" >&2
    echo "Usage: $(basename $0) IFACE" >&2
    exit 1
fi

iface=$1
bssid=()

IFS=':' read -a mac <"/sys/class/net/${iface}/phy80211/macaddress"
IFS=':' read -a mask <"/sys/class/net/${iface}/phy80211/address_mask"

## Prefix each element with 0x to make them proper base16 values for
## arithmetic evaluation.
mac=(${mac[@]/#/0x})
mask=(${mask[@]/#/0x})

model_id=$(sed -r -n 's|^PRODUCT=(.+)/(.+)/.*|0x\1 0x\2|p' "/sys/class/net/${iface}/device/uevent")
if [ -z "${model_id}" ]; then
    ## PCI-devices have PCI_ID field instead of PRODUCT field.
    model_id=$(sed -r -n 's|^PCI_ID=(.+):(.+)$|0x\1 0x\2|p' "/sys/class/net/${iface}/device/uevent")
fi

## Concatenate and zero-padd vendor and product ids.
printf -v model_id '%04x%04x' ${model_id}

## Model-specific quirks.
case "${model_id}" in
    168c0029|168c0030|168c002b|168c002e|168c0037)
        ## For some reason, at least with some driver versions, this
        ## device model reports empty adress mask. However, hostapd
        ## requires that mask >= 00:00:00:00:00:03 to support at most 4
        ## different BSSIDs. Mask 00:00:00:00:00:03 has been verified to
        ## work with the device in question.
        if [ "${mask[*]}" = "0x00 0x00 0x00 0x00 0x00 0x00" ]; then
            mask=(0x00 0x00 0x00 0x00 0x00 0x03)
        fi
        ;;
    *)
        ;;
esac

for (( i = 0; i < ${#mac[@]}; ++i )); do
    bssid[i]=$((mac[i] &~ mask[i]))
done

printf "%02x:" "${bssid[@]}" | head -c-1
