#!/bin/sh

set -eu

tapiface=$1
ssid=$2
rundir=$3

ifconfig "${tapiface}" up
brctl addbr "${ssid}"
brctl setfd "${ssid}" 0
ifconfig "${ssid}" up
brctl addif "${ssid}" "${tapiface}"
dhclient -pf "${rundir}/dhclient.pid" "${ssid}"
