#!/bin/bash

if [ $# -ne 2 ]; then
    echo "wrong number of arguments" >&2
    exit 1
fi

tap=$1
bridge=$2

ifconfig "${tap}" up || exit 1
brctl addif "${bridge}" "${tap}" || exit 1

source puavo-wlanap-env || exit 1

run-parts --arg="${tap}" --arg="${bridge}" -- "${PWAP_DATADIR}/vtun-up.d"
