#!/bin/sh

set -eu

upstream_version=$(dpkg-parsechangelog -S Version | sed -r -n 's/^(.*)-.*$/\1/p')
orig_tarball="../openwsman_${upstream_version}.orig.tar.gz"

if [ ! -e "${orig_tarball}" ]; then
  wget -O "${orig_tarball}.tmp" \
       "https://github.com/Openwsman/openwsman/archive/v${upstream_version}.tar.gz"
  tar -zxf "${orig_tarball}.tmp" --strip-components=1
  mv "${orig_tarball}.tmp" "${orig_tarball}"
fi
