#!/bin/bash

set -eu

user=$(id -nu)
group=$(id -g)

tmpdir=$(mktemp -d /var/tmp/ekapeli-${user}.XXXXXXXXXX)

cleanup() {
  # kill all java processes in our process group, in case the ekapeli
  # is still running
  pkill -g 0 '^java' 2>/dev/null || true

  sleep 3 || true

  fusermount -uz "${tmpdir}/ekapeli"      || true
  fusermount -uz "${tmpdir}/ekapeli.rofs" || true
}

trap cleanup EXIT


mkdir -p "${tmpdir}/ekapeli"     \
         "${tmpdir}/ekapeli.cow" \
         "${tmpdir}/ekapeli.rofs"

bindfs -u "$user" -g "$group" /opt/ekapeli/cache "${tmpdir}/ekapeli.rofs"

unionfs-fuse -o cow \
  "${tmpdir}/ekapeli.cow=RW:${tmpdir}/ekapeli.rofs=RO" \
  "${tmpdir}/ekapeli"

env EKAPELI_CACHE_PATH="${tmpdir}/ekapeli" \
    javaws -wait /opt/ekapeli/game.jnlp

# -nowait does not really do what one could expect, so we wait until
# all '^java' processes in our own process group have exited...
while sleep 3; do
  if [ "$(pgrep -c -g 0 '^java')" -eq 0 ]; then
    break
  fi
done
