#!/bin/bash

set -eu

print_help()
{
    echo "Commands:"
    echo "  help   - show this help"
    echo "  reboot - reboot the system immediately"
}

trap '' SIGINT

tty_dev=$(tty)
tty_n=$(echo "${tty_dev}" | sed -r -n 's|/dev/tty/||')

chvt "${tty_n}"

echo 'Welcome to the Dark side!' | /usr/games/cowsay -b

print_help

while true; do
    read -e -p "> " command || {
	echo
    }

    case "${command}" in
	'reboot')
	    reboot
	    ;;
	'help')
	    print_help
	    ;;
	*)
	    echo "Invalid command '${command}'"
	    echo "Type 'help' to get help"
	;;
    esac
done
