#!/bin/sh

set -eu


darkdm_reboot()
{
    local i

    for i in $(seq 5 -1 1); do
        echo -n -e "\rRebooting in ${i}s. (Press Ctrl-C to cancel)"
        sleep 1 || return 1
    done
    echo -e "\rRebooting now!                              "

    reboot
}

darkdm_install()
{
    /usr/sbin/puavo-install || return 1

    darkdm_reboot
}

darkdm_print_help()
{
    echo "Commands:"
    echo "  help     -  show this help"
    echo "  install  -  install Puavo OS to this device"
    echo "  reboot   -  reboot the system in 5 seconds"
}

darkdm_main()
{
    local command
    local tty_dev
    local tty_n

    tty_dev=$(tty)
    tty_n=$(echo "${tty_dev}" | sed -r -n 's|/dev/tty||p')

    if [ -n "${tty_n}" ]; then
	chvt "${tty_n}" || return 1
    fi

    echo 'Welcome to the Dark side!' | /usr/games/cowsay -b

    darkdm_print_help

    while true; do
	read -e -p "> " command

	case "${command}" in
	    'help')
		darkdm_print_help
		;;
            'install')
		darkdm_install
		;;
	    'reboot')
		darkdm_reboot
		;;
	    *)
		echo "Error: Invalid command '${command}'. Try 'help'." >&2
		;;
	esac
    done
}

darkdm_main
