#!/bin/sh

set -eu

# x2go session is a special case
if [ -n "${X2GO_SESSION:-}" ]; then
    geometry=$(perl -F, -ane 'for (@F) { /^geometry=(.*)$/ && print $1 }' \
	~/.x2go/C-${X2GO_SESSION}/options)

    if [ -n "$geometry" ]; then
        xrandr --output default --mode $geometry
    fi

    exit 0
fi
