#!/bin/sh

# Puavo USB stick factory session.  Executed by nodm (see /etc/default/nodm)

set -eu

# Start i3 and keep it running
(
  mkdir -p ~/.config/i3
  cat <<'EOF' > ~/.config/i3/config
# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!
# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8
# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
        colors {
                background #46606d
                statusline #ffffff
        }
}
EOF

  while true; do
    i3 || true
    logger -p local0.err -t ers-session \
           'i3 has exited or crashed, restarting it...'
    sleep 5
  done
) &

nm-applet &
unclutter -root &

# Disable screen blanking and power saving features
xset s 0 0
xset s off
xset s noblank
xset dpms 0 0 0
xset -dpms

(
  # Start puavo-usb-factory and keep it running
  while true; do
    puavo-manage-ers || true
    logger -p local0.err -t ers-session \
           'The Puavo ERS manage process has exited or crashed, restarting it...'
    sleep 5
  done
)

# We should never get here...
logger -p local0.err -t ers-session \
       'The Puavo ERS manage script is exiting!  This should not happen!'

exit 1
