#!/bin/sh

set -eu

read puavo_domain < /etc/puavo/domain
cert_version=$(puavo-conf puavo.admin.certs.versions | awk '{ print $1 }')

image_server=$(
  host -t SRV -W 5 "_imageserver_${cert_version}._tcp.${puavo_domain}" \
    | awk -v puavo_domain="$puavo_domain" '
        $2 == "has" && $3 == "SRV" && $4 == "record" {
          sub(/\.$/, "", $8)

          # check that $8 has puavo_domain-suffix
          i = index($8, puavo_domain)
          if (i == 0) { next }
          if ($8 == (substr($8, 0, i-1) puavo_domain)) {
            printf "%s:%s\n", $8, $7
            exit(0)
          }
      }')

if [ -z "$image_server" ]; then
  exit 1
fi

printf "%s\n" "$image_server"
