#!/bin/sh

set -eu

uppercase() { printf %s "$1" | tr '[:lower:]' '[:upper:]'; }

release=$(cat /etc/puavo-image/release)
hosttypes=$(ls /usr/share/puavo-conf/profile-overwrites/*.json \
              | xargs -I % -n 1 basename % .json)

if [ -z "$hosttypes" ]; then
  echo 'Could not determine hosttypes for release logos' >&2
  exit 1
fi

mkdir -p /usr/share/icons/release_logos

for hosttype in $hosttypes; do
  hosttype_uppercased="$(uppercase $hosttype)"
  convert -font Ubuntu-R -gravity center -background transparent \
      -matte -bordercolor none -border 3 \
      '(' pango:"<span foreground=\"#41786b\" font-size=\"x-small\">${hosttype_uppercased}</span>" ')' \
      '(' pango:"<span foreground=\"#41786b\" font-size=\"x-small\">${release}</span>" ')' \
      -append "/usr/share/icons/release_logos/${hosttype}.png"
done

exit 0
