#!/usr/bin/ruby

require 'json'
require 'puavo/conf'
require 'shellwords'

puavoconf = Puavo::Conf.new
puavo_xrandr_args = puavoconf.get('puavo.xrandr.args')
puavoconf.close

xrandr_args_list = JSON.parse(puavo_xrandr_args)

raise 'puavo.xrandr.args not in correct format' \
  unless xrandr_args_list.kind_of?(Array)

status = 0

xrandr_args_list.each do |xrandr_args_string|
  xrandr_args = Shellwords.shellwords(xrandr_args_string)
  system('xrandr', *xrandr_args)
  system_status = $?.exitstatus
  status = system_status if system_status != 0
end

exit(status)
