#!/usr/bin/ruby

require 'json'
require 'shellwords'

require 'puavo/conf'

puavoconf = Puavo::Conf.new

exit 0 unless puavoconf.get('puavo.xrandr.enabled') == 'true'

xrandr_args = Shellwords.shellwords(puavoconf.get('puavo.xrandr.args'))
puavoconf.close

connected_displays \
  = %x(xrandr -q).split("\n")                                               \
                 .map { |s| a = s.split; a[1] == "connected" ? a[0] : nil } \
                 .compact

system('xrandr', *xrandr_args)

exit $?.exitstatus
