#!/bin/sh

# Puavo USB stick factory session.  Executed by nodm (see /etc/default/nodm)

set -eu

# Download usb-factory images (if download script exists)
(
  image_downloader=$(whereis puavo-download-usb-factory-images \
                       | awk '{ print $2 }')
  if [ -n "$image_downloader" -a -x "$image_downloader" ]; then
    wait_seconds=1
    while true; do
      if $image_downloader; then
        # if image download succeeds, wait a long time for next check
        wait_seconds=4096
      elif [ "$wait_seconds" -eq 4096 ]; then
        # If image download fails but did succeed in previous attempt,
        # wait a short time again.
        wait_seconds=1
      else
        # Otherwise (image download has failed), try again with a bit longer
        # delay, but not too long.
        wait_seconds=$((2 * $wait_seconds))
        if [ "$wait_seconds" -gt 256 ]; then
          wait_seconds=256
        fi
      fi
      sleep "$wait_seconds"
    done
  fi
) &

# Start openbox and keep it running
(
  while true; do
    openbox || true
    logger -p local0.err -t puavo-usb-factory \
           'openbox has exited or crashed, restarting it...'
    sleep 5
  done
) &

unclutter -root &

# Disable screen blanking and power saving features
xset s 0 0
xset s off
xset s noblank
xset dpms 0 0 0
xset -dpms

(
  # Start puavo-usb-factory and keep it running
  while true; do
    puavo-usb-factory || true
    logger -p local0.err -t puavo-usb-factory \
           'The USB stick factory process has exited or crashed, restarting it...'
    sleep 5
  done
)

# We should never get here...
logger -p local0.err -t puavo-usb-factory \
       'The usb-factory-session script is exiting!  This should not happen!'

exit 1
