#!/bin/sh

# no "set -eu"!
# we should be run from nodm

export DESKTOP_SESSION=puavo-user-registration

SYSSESSIONDIR=/etc/X11/Xsession.d
SESSIONFILES=$(run-parts --list $SYSSESSIONDIR)
if [ -n "$SESSIONFILES" ]; then
  for SESSIONFILE in $SESSIONFILES; do
    . $SESSIONFILE
  done
fi

# Because puavo-user-registration is typically run when
# "puavo.admin.personally_administered" is "true", meaning incoming
# connections are not accepted, we should run this before going to
# desktop session.  This is to make it possible to remotely figure out
# possible problems with registration.
/usr/lib/puavo-ltsp-client/admin-remote-connections --accept-incoming || true

exec /usr/lib/puavo-ltsp-client/desktop-session "$@"
