#!/bin/bash
#
# ##############################################################################
#
# Copyright (C) 2014 Opinsys Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# ##############################################################################
#
# Author: Tuomas Räsänen <tuomasjjrasanen@tjjr.fi>

set -eu

. "${RESTRICTED_PKG_LIBDIR}/common"

package=$1

packagedir=$(packagedir "$package")
installdir="${packagedir}/i"
install_marker="${packagedir}/${PUAVOLTSP_IMAGE_NAME}"
prpdir="${packagedir}/PRP"

[ -e "${install_marker}" ] || {
    echo "E: failed to unconfigure package '${package}' because it is not installed" >&2
    exit 1
}

[ -x "${prpdir}/unconfigure" ] && "${prpdir}/unconfigure" "${installdir}" "${prpdir}"

exit 0
