#!/bin/sh
#
# ##############################################################################
#
# Copyright (C) 2014 Opinsys Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# ##############################################################################
#
# Author: Tuomas Räsänen <tuomasjjrasanen@tjjr.fi>

set -eu

. "${RESTRICTED_PKG_LIBDIR}/common"

package=$1
shift

packagedir=$(packagedir "$package")
installdir="${packagedir}/i"
prpdir="${packagedir}/PRP"

remove_install_link "$package"

for imglink in $(packagebase "$package")/*.img; do
  if [ ! -h "$imglink" ]; then
    # last install link removed, garbage collect this
    rm -rf "${installdir}" "${prpdir}"
    break
  fi
done


exit 0
