#!/bin/bash
#
# ##############################################################################
#
# Copyright (C) 2014 Opinsys Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# ##############################################################################
#
# Author: Tuomas Räsänen <tuomasjjrasanen@tjjr.fi>

set -eu

. /usr/lib/puavo-ltsp-client/restricted-packages/common

on_exit()
{
    local exitval=$?
    set +e

    if [ $exitval -ne 0 ]; then
	rm -rf "${prpdir}"
	rm -rf "${installdir}" "${installdir}.tmp"
    fi

    exit $exitval
}

package=$1

upstream_pack_md5sum=$(upstream_pack_md5sum "$package")
packagedir=$(packagedir "$package")
installdir="${packagedir}/i"
prpdir="${packagedir}/PRP"
[ -d "${installdir}" ] && exit 0

upstream_pack="${packagedir}/upstream.pack"
[ ! -f "${upstream_pack}" ] && {
    echo "E: cannot install package '${package}' because the upstream pack" \
        "is missing, download it first" >&2
    exit 1
}

trap on_exit EXIT

# Copy all packaging stuff from the template directory.
mkdir "${prpdir}"
cp -a -T "/usr/share/puavo-ltsp-client/restricted-packages/${package}" "${prpdir}"

echo "${upstream_pack_md5sum}  ${upstream_pack}" | md5sum --check --status || {
    echo "E: md5 checksum of the upstream pack '${upstream_pack}' does not" \
        "match the known checksum ${upstream_pack_md5sum}," \
        "perhaps you should purge the package and download it again?" >&2
    exit 1
}

# We own this directory!
rm -rf "${installdir}.tmp"
mkdir "${installdir}.tmp"

[ -x "${prpdir}/unpack" ] && "${prpdir}/unpack" "${upstream_pack}" "${installdir}.tmp"

mv -T "${installdir}.tmp" "${installdir}"

exit 0
