[package]
name = "puavo-kpsd"
version.workspace = true
edition.workspace = true

[[bin]]
name = "puavo-kpsd"
path = "src/main.rs"

[dependencies]
# Internal crates
puavo-hsm = { path = "../puavo-hsm" }

# CLI and configuration
clap = { version = "4.5", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true

puavo-ipc = { path = "../puavo-ipc" }
tokio = { version = "1.43", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2.0"
async-trait = "0.1"
bincode = "1.3"
anyhow = "1.0"
toml.workspace = true

# Cryptography
cryptoki.workspace = true
hex.workspace = true
rand.workspace = true
rsa.workspace = true
sha2.workspace = true
