#!/usr/bin/python3

import gi
import subprocess

gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

def on_button_clicked(widget):
    print('button clicked')

def puavoconf_get(puavoconf_key):
  return subprocess.check_output([ 'puavo-conf', puavoconf_key ]).rstrip() \
                   .decode('utf-8')

pkglist = puavoconf_get('puavo.pkgs.ui.pkglist').split()

win = Gtk.Window()
win.connect('destroy', Gtk.main_quit)
win.set_border_width(10)

box_outer = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
win.add(box_outer)

button = Gtk.Button(label='INSTALL ALL')
button.connect('clicked', on_button_clicked)
box_outer.pack_start(button, True, True, 0)

grid = Gtk.Grid()
box_outer.pack_start(grid, True, True, 0)

previous_label = None

for pkg in pkglist:
    label = Gtk.Label(label=pkg)
    button = Gtk.Button(label='INSTALL')
    if not previous_label:
        grid.add(label)
    else:
        grid.attach_next_to(label, previous_label, Gtk.PositionType.BOTTOM,
            1, 1)
    previous_label = label

    grid.attach_next_to(button, label, Gtk.PositionType.RIGHT, 1, 1)

win.show_all()

Gtk.main()
