#!/bin/sh

set -eu

xsession_dirs="
  /usr/share/gdm/BuiltInSessions
  /usr/share/wayland-sessions
  /usr/share/xsessions
"

if [ "$(puavo-conf puavo.xsessions.locked)" = "true" ]; then
  mkdir -p /etc/X11/sessions

  ln -fns /usr/share/puavo-ltsp-client/xsessions/puavo-desktop.desktop \
          /etc/X11/sessions/puavo-desktop.desktop

  for xsession_dir in $xsession_dirs; do
    for desktopfile in ${xsession_dir}/*.desktop; do
      test -e "$desktopfile" || continue
      mv "${desktopfile}" "${desktopfile}.puavo_disabled"
    done
  done
else
  for xsession_dir in $xsession_dirs; do
    for disabled_desktopfile in ${xsession_dir}/*.desktop.puavo_disabled; do
      test -e "$disabled_desktopfile" || continue
      mv "${disabled_desktopfile}" "${disabled_desktopfile%.puavo_disabled}"
    done
  done

  rm -f /etc/X11/sessions/puavo-desktop.desktop
fi
