#!/bin/sh

set -u

APTIREPO_ROOT=${APTIREPO_ROOT:-.}

cd "${APTIREPO_ROOT}" || {
    echo "could not change the current directory to repository root directory '${APTIREPO_ROOT}'" >&2
    exit 1
}

if [ ! -d .aptirepo ]; then
    echo "'$(pwd)' is not an aptirepo repository" >&2
    exit 1
fi


## - generate Sources and Packages For each architecture in each component in each distribution
## - generate Contents for each component in each distribution
## - generate Release for each distribution
find dists -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | while read dist; do
    find "dists/${dist}" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | while read comp; do
        apt-ftparchive contents "pool/${dist}/${comp}" | gzip >"dists/${dist}/${comp}/Contents.gz"
        find "dists/${dist}/${comp}" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | while read archdir; do
            if [ "${archdir}" = "source" ]; then
                apt-ftparchive sources "pool/${dist}/${comp}" >"dists/${dist}/${comp}/${archdir}/Sources"
                gzip -c "dists/${dist}/${comp}/${archdir}/Sources" >"dists/${dist}/${comp}/${archdir}/Sources.gz"
            else
                apt-ftparchive --arch "${archdir#binary-}" packages "pool/${dist}/${comp}" >"dists/${dist}/${comp}/${archdir}/Packages"
                gzip -c "dists/${dist}/${comp}/${archdir}/Packages" >"dists/${dist}/${comp}/${archdir}/Packages.gz"
            fi
        done
    done
    comps=$(find "dists/${dist}" -mindepth 1 -maxdepth 1 -type d -printf '%f ')
    archs=$(find "dists/${dist}" -mindepth 2 -maxdepth 2 -type d -printf '%f ')
    apt-ftparchive \
        -o "APT::FTPArchive::Release::Codename=${dist}" \
        -o "APT::FTPArchive::Release::Components=${comps}" \
        -o "APT::FTPArchive::Release::Architectures=${archs}" \
        release "dists/${dist}" >"dists/${dist}/Release"
done
