#!/bin/sh

export DESKTOP_SESSION=puavo-desktop

qiv -mx /usr/share/backgrounds/Colored_Pencils_by_Jess_Bailey.jpg

SYSSESSIONDIR=/etc/X11/Xsession.d
SESSIONFILES=$(run-parts --list $SYSSESSIONDIR)
if [ -n "$SESSIONFILES" ]; then
  for SESSIONFILE in $SESSIONFILES; do
    . $SESSIONFILE
  done
fi

exec /usr/bin/gnome-session "$@"
