#!/usr/bin/python3

import sys

import gi
gi.require_version('Gtk', '3.0')        # explicitly require Gtk3, not Gtk2
gi.require_version('WebKit2', '4.1')    # explicitly require version 4
from gi.repository import Gtk, WebKit2

class PuavoExamBrowser(Gtk.Window):
  def __init__(self, url):
    super(PuavoExamBrowser, self).__init__()

    self.connect('destroy', Gtk.main_quit)

    self.set_title('Puavo Exam Browser')
    self.set_position(Gtk.WindowPosition.CENTER)
    self.set_size_request(640, 480)
    self.maximize()

    # if a fullscreen is good, how to control it on/off?
    # XXX self.fullscreen()

    self.address_entry = None
    self.webview_shown = False

    self.webview = WebKit2.WebView()
    self.disable_cert_checks()  # XXX perhaps not okay?
    self.webview.connect('load-changed', self.on_load_changed)
    self.webview.connect('load-failed',  self.on_load_failed)

    self.load_failed = True

    if url == '':
      self.address_entry = Gtk.Entry()
      self.address_entry.expand = True
      self.address_entry.set_text(url)
      self.address_entry.connect('activate', self.on_change_uri)
      self.add(self.address_entry)
      self.show_all()
    else:
      self.load_failed = False
      self.webview.load_uri(url)


  def on_change_uri(self, widget):
    self.load_failed = False
    self.webview.load_uri( self.address_entry.get_text() )


  def on_load_failed(self, widget, load_event, failing_uri, error):
    self.load_failed = True
    return True


  def on_load_changed(self, widget, load_event):
    if load_event != WebKit2.LoadEvent.FINISHED:
      return True

    if self.load_failed:
      return True

    if self.address_entry:
      self.address_entry.destroy()
      self.address_entry = None

    if not self.webview_shown:
      self.add(self.webview)
      self.show_all()
      self.webview_shown = True

    return True


  # XXX is this okay?
  def disable_cert_checks(self):
    web_context = self.webview.get_context()
    web_context.set_tls_errors_policy(WebKit2.TLSErrorsPolicy.IGNORE)


url = ''
if len(sys.argv) == 2:
    url = sys.argv[1]

Gtk.init(sys.argv)
webwindow = PuavoExamBrowser(url)
Gtk.main()
