#!/usr/bin/python3

import sys

import gi
gi.require_version('Gtk', '3.0')        # explicitly require Gtk3, not Gtk2
gi.require_version('WebKit2', '4.1')    # explicitly require version 4
from gi.repository import Gtk, WebKit2

class PuavoExamBrowser(Gtk.Window):
  def __init__(self, url):
    super(PuavoExamBrowser, self).__init__()

    self.connect('destroy', Gtk.main_quit)

    self.set_title('Puavo Exam Browser')
    self.set_position(Gtk.WindowPosition.CENTER)
    self.set_size_request(640, 480)
    self.maximize()

    # if a fullscreen is good, how to control it on/off?
    # XXX self.fullscreen()

    self.urlbar = None
    self.webview_shown = False

    if url == '':
      self.urlbar = Gtk.Entry()
      self.urlbar.expand = True
      self.urlbar.set_text(url)
      self.urlbar.connect('activate', self.on_change_uri)
      self.add(self.urlbar)
      self.show_all()
    else:
      self.start_browser(url)


  def on_change_uri(self, widget):
    self.start_browser( self.urlbar.get_text() )


  def start_browser(self, url):
    self.webview = WebKit2.WebView()
    self.disable_cert_checks()  # XXX perhaps not okay?

    self.webview.connect('load-changed', self.load_changed)
    self.webview.load_uri(url)


  def load_changed(self, widget, load_event):
    if load_event != WebKit2.LoadEvent.FINISHED:
      return

    if self.urlbar:
      self.urlbar.destroy()
      self.urlbar = None

    if not self.webview_shown:
      self.add(self.webview)
      self.show_all()
      self.webview_shown = True


  # XXX is this okay?
  def disable_cert_checks(self):
    web_context = self.webview.get_context()
    web_context.set_tls_errors_policy(WebKit2.TLSErrorsPolicy.IGNORE)


url = ''
if len(sys.argv) == 2:
    url = sys.argv[1]

Gtk.init(sys.argv)
webwindow = PuavoExamBrowser(url)
Gtk.main()
