#!/bin/sh

if [ "$(tty)" = '/dev/tty42' ]; then
  clear
  exec env HOME=/var/lib/puavo-exammode/user      \
    bwrap --dev-bind / /                          \
          --tmpfs    /anon                        \
          --tmpfs    /home                        \
          --tmpfs    /images                      \
          --tmpfs    /state                       \
          --tmpfs    /tmp                         \
          --tmpfs    /var/lib/puavo-exammode/user \
          --tmpfs    /var/tmp                     \
      startx /usr/lib/puavo-ltsp-client/exammode-session -- :42 > /dev/null 2>&1
fi

exec /bin/bash
