#!/bin/sh

set -eu

maybe_run_command() {
  command=$1
  if [ "$SSH_ORIGINAL_COMMAND" = "$command" ]; then
    exec $command
  fi
}

backuppable_dirs="/etc/ /home/"

for dir in $backuppable_dirs; do
  maybe_run_command "rsync --server --sender -lHogDtprSe.iLsfxC . ${dir}"
done

echo 'Access not allowed' >&2
exit 1
