#!/bin/bash

if [ $# -ne 2 ]; then
    echo "wrong number of arguments" >&2
    exit 1
fi

tap=$1
bridge=$2

source puavo-wlanap-env || exit 1
source "${PWAP_DATADIR}/config"
source "${PWAP_DATADIR}/config" || true

networks="${PWAP_RUNDIR}/networks"

(
    flock "${networksfd}"

    sed -i -r "/${tap} ${bridge}/d" "${networks}"
) {networksfd}>"${networks}"
