#!/bin/sh

set -eu

manage_preferences() {
  tmpfile="${preferences_file}.tmp"

  if [ -e "$preferences_file" ]; then
    jq "$@" "$preferences_file" > "$tmpfile" || return 1
  else
    jq --null-input "$@" > "$tmpfile" || return 1
  fi

  mv "$tmpfile" "$preferences_file"
}

default_args="--disable-infobars --no-default-browser-check --no-first-run"

preferences_dir=~/.config/chromium/Default
preferences_file="${preferences_dir}/Preferences"

mkdir -p "$preferences_dir"

if [ -n "$HOMEPAGE" ]; then
  manage_preferences --arg homepage "$HOMEPAGE" '
    .browser.show_home_button = true
    | .homepage = $homepage
    | .homepage_is_newtabpage = false
    | .session.restore_on_startup = 4
    | .session.startup_urls = [ $homepage ]
  ' || true
fi

manage_preferences '.browser.custom_chrome_frame = false' || true

exec /usr/bin/chromium.distrib $default_args "$@"
