#!/bin/sh

set -eu

dbus-send --session --type=method_call --dest=org.gnome.Shell \
          /org/gnome/Shell org.gnome.Shell.Eval 'string:
if (Main.overview.visible)
    Main.overview.hide();
else
    Main.overview.show();
'
