#!/bin/sh

set -eu

if [ $# -ne 0 ]; then
    echo "E: wrong number of arguments" >&2
    echo "Usage: $0" >&2
    exit 1
fi

switch-to-unity-greeter-vt

## The "Guest Session" widget might NOT be the active one, click down
## arrow to activate the guest login widget.
xte 'key Down'
sleep 1

xte 'key Return'
