#!/bin/sh
#
# ##############################################################################
#
# Copyright (C) 2014 Opinsys Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# ##############################################################################
#
# Author: Tuomas Räsänen <tuomasjjrasanen@tjjr.fi>

set -e

RESTRICTED_PKG_LIBDIR=${RESTRICTED_PKG_LIBDIR:-/usr/lib/puavo-ltsp-client/restricted-packages}
RESTRICTED_PKG_SHAREDIR=${RESTRICTED_PKG_SHAREDIR:-/usr/share/puavo-ltsp-client/restricted-packages}
RESTRICTED_PKG_STATEDIR=${RESTRICTED_PKG_STATEDIR:-/state/restricted-packages}

if [ -z "$PUAVOLTSP_IMAGE_NAME" ]; then
  PUAVOLTSP_IMAGE_NAME=$(cat /etc/ltsp/this_ltspimage_name)
fi

set -u

export PUAVOLTSP_IMAGE_NAME    \
       RESTRICTED_PKG_LIBDIR   \
       RESTRICTED_PKG_SHAREDIR \
       RESTRICTED_PKG_STATEDIR

usage_error()
{
    echo "error $1" >&2
    echo "Try '$0 --help' for more information." >&2
    return 1
}

print_help_and_exit()
{
    echo "Usage: $0 [COMMAND] [COMMAND_OPTIONS]"
    echo
    echo "Manage restricted packages."
    echo
    echo "Commands:"
    echo "    install                      install package"

    echo
    exit 0
}

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            shift
            print_help_and_exit
            ;;
        --)
            shift
            break
            ;;
        -*)
            usage_error "invalid argument '$1'"
            ;;
        *)
            break
            ;;
    esac
done

if [ $# -lt 1 ]; then
    print_help_and_exit
fi

command=$1
shift

case "${command}" in
    install)
        "${RESTRICTED_PKG_LIBDIR}/commands/${command}" "$@"
        ;;
    *)
        usage_error "unknown command '${command}'"
esac

exit 0
