#!/bin/sh

exit_requested=0

postponed_graceful_exit()
{
    exit_requested=1
}

stop_hostapd()
{
    [ -f /var/tmp/puavo-wlanap/hostapd.pid ] || return
    kill $(cat /var/tmp/puavo-wlanap/hostapd.pid)
    rm /var/tmp/puavo-wlanap/hostapd.pid
}

stop_vtund()
{
    [ -f /var/run/vtund.puavo-wlanap-$vtun_gateway.pid ] || return
    kill $(cat /var/run/vtund.puavo-wlanap-$vtun_gateway.pid)
    rm /var/run/vtund.puavo-wlanap-$vtun_gateway.pid
}

graceful_exit()
{
    stop_hostapd
    stop_vtund
    exit 0
}

. /etc/puavo-wlanap/config

puavo-wlanap-update-configs
exitval=$?

if [ $exitval -eq 1 ]
then
    # puavo-wlanap-update-configs exits with 1 if hostap_channel is
    # not set. That is fine, the user did not want puavo-wlanap to
    # run.
    exit 0
fi

if [ $exitval -gt 1 ]
then
    exit $exitval
fi

trap postponed_exit INT TERM HUP

vtund -f /var/tmp/puavo-wlanap/vtund.conf puavo-wlanap $vtun_gateway
if [ $? -ne 0 ]
then
    echo "error: failed to start vtun" | logger -t puavo-wlanap -s -p user.err
    exit 1
fi

hostapd -B -P /var/tmp/puavo-wlanap/hostapd.pid /var/tmp/puavo-wlanap/hostapd.conf
if [ $? -ne 0 ]
then
    echo "error: failed to start hostapd" | logger -t puavo-wlanap -s -p user.err
    stop_vtund
    exit 1
fi

trap graceful_exit INT TERM HUP

if [ $exit_requested -ne 0 ]
then
    graceful_exit
fi

while true
do
    sleep 300
    puavo-wlanap-send-status
done
