#!/bin/sh

stop_hostapd()
{
    kill $(cat /var/tmp/puavo-wlanap/hostapd.pid)
    rm /var/tmp/puavo-wlanap/hostapd.pid
}

stop_vtund()
{
    kill $(cat /var/run/vtund.wlan-$vtun_gateway.pid)
    rm /var/run/vtund.wlan-$vtun_gateway.pid
}

on_exit()
{
    stop_hostapd
    stop_vtund
    exit 0
}

. /etc/puavo-wlanap/config

puavo-wlanap-update-configs

if [ $? -eq 1 ]
then
    exit 0
fi

if [ $? -gt 1 ]
then
    exit $?
fi

trap on_exit INT TERM HUP

vtund -f /var/tmp/puavo-wlanap/vtund.conf wlan $vtun_gateway
if [ $? -ne 0 ]
then
    echo "error: failed to start vtun" | logger -t puavo-wlanap -s -p user.err
    exit 1
fi

hostapd -B -P /var/tmp/puavo-wlanap/hostapd.pid /var/tmp/puavo-wlanap/hostapd.conf
if [ $? -ne 0 ]
then
    echo "error: failed to start hostapd" | logger -t puavo-wlanap -s -p user.err
    stop_vtund
    exit 1
fi

while true
do
    sleep 300
    puavo-wlanap-send-status
done
