#!/bin/sh

set -eu

puavo_hosttype="$(puavo-conf puavo.hosttype)"

# XXX get rid of hosttype handling
if [ "$puavo_hosttype" != 'bootserver' ]; then
  exit 0
fi

read puavo_ldap_base   < /etc/puavo/ldap/base
read puavo_ldap_server < /etc/puavo/ldap/master

cat <<EOF > /etc/ldap/ldap.conf.tmp
BASE        ${puavo_ldap_base}
NETWORK_TIMEOUT 15
SASL_MECH   GSSAPI
TIMEOUT     15
TLS_CACERT  /etc/puavo/certs/rootca.pem
TLS_REQCERT demand
URI         ldapi:/// ldap://${puavo_ldap_server}
EOF

mv /etc/ldap/ldap.conf.tmp /etc/ldap/ldap.conf
