#!/bin/sh

# This script is called from udev rules when udev detects a change in 
# monitor configuration. All xrandr commands are called to restore 
# the configuration. This is needed e.g. with document cameras that 
# cause displays to come and go on regular basis.
#
# udev rule example:
#
# ACTION=="change", SUBSYSTEM=="drm", RUN+="/usr/bin/udev-hotplug-monitor"

puavo_xrandr_settings_are_forced() {
  jq -r .device.tags[] /etc/puavo/device.json | grep -qx force_puavo_xrandr
}

there_is_a_desktop_session() {
  pgrep -fx '/bin/sh /usr/lib/puavo-ltsp-client/puavo-desktop-session' \
    >/dev/null
}

if there_is_a_desktop_session && !puavo_xrandr_settings_are_forced; then
  # if puavo xrandr settings are not forced and we are on a desktop session,
  # we depend on the gnome-settings-daemon xrandr plugin to handle the displays
  exit 0
fi

export DISPLAY=:0.0
export XAUTHORITY=/var/run/lightdm/root/:0

/usr/lib/puavo-ltsp-client/puavo-run-xrandr
