#!/bin/sh

set -eu

# This script is called from udev rules when udev detects a change in 
# monitor configuration. All xrandr commands are called to restore 
# the configuration. This is needed e.g. with document cameras that 
# cause displays to come and go on regular basis.
#
# udev rule example:
#
# ACTION=="change", SUBSYSTEM=="drm", RUN+="/usr/bin/udev-hotplug-monitor"

there_is_a_desktop_session() {
  pgrep -fx '/bin/sh /usr/lib/puavo-ltsp-client/puavo-desktop-session' \
    >/dev/null
}

is_forced=$(puavo-conf -b puavo.xrandr.forced)

if there_is_a_desktop_session && [ "${is_forced}" = false ]; then
    # Depend on the gnome-settings-daemon xrandr plugin to handle the displays.
    exit 0
fi

export DISPLAY=:0.0
export XAUTHORITY=/var/run/lightdm/root/:0

/usr/lib/puavo-ltsp-client/puavo-run-xrandr
