#!/bin/bash
# puavo-autopilot - automatic test tool for Puavo desktop sessions
# Copyright (C) 2013 Opinsys Oy
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -eu

on_exit()
{
    ## No need to short-circuit exit on error anymore: we are already cleaning
    ## up and exiting.
    set +e

    if [ -n "${workdir}" ]; then
        rm -rf "${workdir}" || exitval=$?
    fi

    exit $exitval
}

if [ $# -ne 1 ]; then
    echo "E: missing argument" >&2
    echo "Usage: $0 PNG" >&2
    exit 1
fi

png=$(readlink -e "$1")
if [ $? -ne 0 ]; then
    echo "E: image '$1' does not exist" >&2
    exit 1
fi

exitval=1
workdir=''

# After this point, we are going to make permanent changes, hence we
# setup cleanup hook to make sure we do not leave anything behind us.

trap on_exit EXIT

workdir=$(mktemp -d)

cd "${workdir}"

scrot screenshot.png || {
    echo "E: failed to take a screenshot" >&2
    exit 1
}

visgrep screenshot.png "${png}" | sed -nr 's/^([0-9]+),([0-9]+) .*$/\1 \2/p'

exitval=0
