#!/bin/sh

set -eu

upstream_version=$(dpkg-parsechangelog -S Version | sed -r -n 's/^(.*)-.*$/\1/p')
orig_tarball="../gnome-network-displays_${upstream_version}.orig.tar.bz2"

if [ ! -e "${orig_tarball}" ]; then
  wget -O "${orig_tarball}.tmp" \
       "https://gitlab.gnome.org/GNOME/gnome-network-displays/-/archive/d9087b5b69c51f5252e87a8e69cd36d779b1ba25/gnome-network-displays-d9087b5b69c51f5252e87a8e69cd36d779b1ba25.tar.bz2"
  tar -jxf "${orig_tarball}.tmp" --strip-components=1
  mv "${orig_tarball}.tmp" "$orig_tarball"
fi
