#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

mkdir -p ${rootmnt}/var/local/lib/puavo-conf
cp /var/local/lib/puavo-conf/parameters.db ${rootmnt}/var/local/lib/puavo-conf
