#!/bin/sh

set -eu

{

status=0

USER=$(id -nu)
HOME=$(getent passwd "$USER" | awk -F: '{ print $6 }')

export HOME USER

for pwa_dir in /var/lib/puavo-pwa/*; do
  test -d "$pwa_dir" || continue

  pwa_browser=$(cat "${pwa_dir}/browser" 2>/dev/null || true)
  if [ -n "$pwa_browser" ]; then
    browser_list="$pwa_browser"
  else
    browser_list='chrome chromium'
  fi

  for browser in $browser_list; do
    pwa_name="$(basename "$pwa_dir")"                       || status=1
    puavo-pwa --browser "$browser" --setup-only "$pwa_name" || status=1
  done
done

exit $status

} > /tmp/puavo-setup-guestuser-pwas.log 2>&1
