#!/bin/sh

set -eu

# Clean up the network connections made in login screen
# (made by "Debian-gdm"-user).  Normal users are allowed to have their
# own networks and we want that information to persist.

# XXX This should be checked out if it works in Debian.

awk '
  BEGIN { FS = "="; ORS = "\0" }
  $1 == "permissions" {
    split($2, userlist, /;/)
    for (i in userlist) {
      if (userlist[i] == "user:Debian-gdm:") {
        print FILENAME
      }
    }
  }
' /etc/NetworkManager/system-connections/* \
  | xargs -0 rm -f
