#!/bin/sh

set -eu

read puavo_domain          < /etc/puavo/domain
read puavo_kerberos_master < /etc/puavo/kerberos/master
read puavo_kerberos_realm  < /etc/puavo/kerberos/realm

krb5_config() {
  local use_kerberos_master use_kerberos_slave

  use_kerberos_master=$1
  use_kerberos_slave=$2

  toprealm_config=''

  if $use_kerberos_master; then
    puavo_kerberos_toprealm=$(cat /etc/puavo/kerberos/toprealm 2>/dev/null \
                                || true)
    puavo_topdomain=$(cat /etc/puavo/topdomain 2>/dev/null || true)
    if [ -n "$puavo_kerberos_toprealm" -a -n "$puavo_topdomain" ]; then
      toprealm_config=$(cat <<EOF
        ${puavo_kerberos_toprealm} = {
                kdc = ${puavo_kerberos_master}
                default_domain = ${puavo_topdomain}
        }
EOF
)
    fi

  fi

  slave_kdc_config=''
  if $use_kerberos_slave \
    && [ "$puavo_kerberos_master" != "kerberos.${puavo_domain}" ]; then
      # Use a possible bootserver kerberos as the fallback server in case
      # it can be found.
      slave_kdc_config="                kdc = kerberos.${puavo_domain}"
  fi

  realms=$(
    cat <<EOF
[realms]
        ${puavo_kerberos_realm} = {
                kdc = ${puavo_kerberos_master}
EOF
    if [ -n "$slave_kdc_config" ]; then printf "%s\n" "$slave_kdc_config"; fi
    cat <<EOF
                default_domain = ${puavo_domain}
        }
${toprealm_config}
EOF
)

  cat <<EOF
[libdefaults]
    default_realm = ${puavo_kerberos_realm}
    default_tgs_enctypes = des3-hmac-sha1
    default_tkt_enctypes = des3-hmac-sha1
    dns_lookup_kdc = false
    dns_lookup_realm = false
    allow_weak_crypto = true
    rdns = false   # Do not use reverse DNS queries and force use of fqdn names for everything

${realms}

[appdefaults]
        pam = {
                debug = false
                ticket_lifetime = 604800
                renew_lifetime = 604800
                forwardable = true
                krb4_convert = false
                ignore_k5login = true
        }
EOF
}

use_master_kerberos=true
if [ -e /run/puavo/nbd-server ]; then
  # on networking clients, we can rely on bootserver kerberos server
  use_master_kerberos=false
fi

krb5_config "$use_master_kerberos" true > /etc/krb5.conf.tmp
mv /etc/krb5.conf.tmp /etc/krb5.conf

krb5_config true false > /etc/krb5.conf.masteronly.tmp
mv /etc/krb5.conf.masteronly.tmp /etc/krb5.conf.masteronly
