#!/bin/sh

set -eu

dm=$(puavo-conf puavo.xsessions.display_manager)

case "$dm" in
  gdm)
    default_dm='/usr/sbin/gdm3'
    dm_service='/lib/systemd/system/gdm3.service'
    ;;
  nodm)
    # Activate the "nodm"-mode
    default_dm='/usr/sbin/nodm'
    dm_service='/lib/systemd/system/nodm.service'
    ;;
  *)
    echo "Unsupported display manager ${dm}" >&2
    exit 1
    ;;
fi

echo "$default_dm" > /etc/X11/default-display-manager

ln -fns "$dm_service" /etc/systemd/system/display-manager.service
