#!/bin/sh

set -eu

data_root_in_home=$(puavo-conf puavo.dockerd.data_root_in_home)

if [ "${data_root_in_home}" = true ]; then
  install -T -m0700 -oroot -groot -d /home/.dockerd_data_root
  install -T -m0400 -oroot -groot /dev/null /etc/docker/daemon.json
  cat >/etc/docker/daemon.json <<'EOF'
{
  "data-root": "/home/.dockerd_data_root"
}
EOF
fi
