#!/bin/sh

set -eu

read puavo_kerberos_realm < /etc/puavo/kerberos/realm

krb5_config() {
  hosttype=$1
  masteronly=$2

  if [ "$hosttype" = 'laptop' ] || $masteronly; then
    dns_lookup_kdc=false
    dns_lookup_realm=false

    read puavo_domain          < /etc/puavo/domain
    read puavo_kerberos_master < /etc/puavo/kerberos/master
    read puavo_topdomain       < /etc/puavo/topdomain

    toprealm_config=''
    puavo_kerberos_toprealm=$(cat /etc/puavo/kerberos/toprealm 2>/dev/null \
                                || true)
    if [ -n "$puavo_kerberos_toprealm" ]; then
      toprealm_config=<<EOF
        ${puavo_kerberos_toprealm} = {
                kdc = ${puavo_kerberos_master}
                default_domain = ${puavo_topdomain}
        }
EOF
    fi

    org_kdc_config=''
    if ! $masteronly; then
      org_kdc_config="kdc = kerberos.${puavo_domain}"
    fi

    realms=$(cat <<EOF)
[realms]
        ${puavo_kerberos_realm} = {
                ${org_kdc_config}
                kdc = ${puavo_kerberos_master}
                default_domain = ${puavo_domain}
        }
${toprealm_config}
EOF
  else
    dns_lookup_kdc=true
    dns_lookup_realm=true
    realms=''
  fi

  cat <<EOF
[libdefaults]
    default_realm = ${puavo_kerberos_realm}
    default_tgs_enctypes = des3-hmac-sha1 des-cbc-crc
    default_tkt_enctypes = des3-hmac-sha1 des-cbc-crc
    dns_lookup_kdc = ${dns_lookup_kdc}
    dns_lookup_realm = ${dns_lookup_realm}
    allow_weak_crypto = true
    rdns = false   # Do not use reverse DNS queries and force use of fqdn names for everything

${realms}

[appdefaults]
        pam = {
                debug = false
                ticket_lifetime = 604800
                renew_lifetime = 604800
                forwardable = true
                krb4_convert = false
                ignore_k5login = true
        }
EOF
}

krb5_config laptop false > /etc/krb5.conf.tmp
mv /etc/krb5.conf.tmp /etc/krb5.conf

krb5_config laptop true > /etc/krb5.conf.masteronly.tmp
mv /etc/krb5.conf.masteronly.tmp /etc/krb5.conf.masteronly
