#!/bin/sh

set -eu

install_puavo_pkg_conf() {
  puavo_pkg_cachedir=$1
  puavo_pkg_rootdir=$2

  puavo_pkg_conf_path='/etc/puavo-pkg/puavo-pkg.conf'

  mkdir -p /etc/puavo-pkg

  cat <<EOF > "${puavo_pkg_conf_path}.tmp"
PUAVO_PKG_CACHEDIR=${puavo_pkg_cachedir}
PUAVO_PKG_ROOTDIR=${puavo_pkg_rootdir}
EOF

  mv "${puavo_pkg_conf_path}.tmp" "$puavo_pkg_conf_path"
}

status=0

image_puavo_pkg_cachedir='/var/cache/puavo-pkg'
image_puavo_pkg_rootdir='/var/lib/puavo-pkg'

install_puavo_pkg_conf "$image_puavo_pkg_cachedir" "$image_puavo_pkg_rootdir"

test_puavopkg_installation() {
  # this is faster than "puavo-pkg show $1"
  puavo_pkg=$1
  installed_path="${puavo_pkg_rootdir}/packages/${puavo_pkg}/installed"
  [ -h "$installed_path" -a -d "$installed_path" ]
}

# We configure the "smartboard" and "ti-nspire-cx-cas-ss" puavo-pkg packages
# in system image in case those are installed, because they are unconfigured
# by default and their configuration is dependent on puavo-conf variables
# "puavo.nonfree.smartboard.enabled" and
# "puavo.nonfree.ti_nspire_cx_cas_ss.enabled".
if test_puavopkg_installation smartboard; then
  puavo-pkg reconfigure smartboard || status=1
fi
if test_puavopkg_installation ti-nspire-cx-cas-ss; then
  puavo-pkg reconfigure ti-nspire-cx-cas-ss || status=1
fi

# Then setup puavo-pkg configuration to include possible locally installed
# puavo-pkg images.  (Note that this does not install or update
# the puavo-pkg packages, only sets them up at boottime).

host_puavo_pkg_cachedir='/images/puavo-pkg/cache'
host_puavo_pkg_rootdir='/images/puavo-pkg/root'

install_puavo_pkg_conf "$host_puavo_pkg_cachedir" "$host_puavo_pkg_rootdir"

# Setup puavo-pkgs from under /images/puavo-pkg only if they are missing
# from the system image, or the versions under /images/puavo-pkg are
# newer than the versions in system image (we determine the age of
# a puavo-pkg from the installation time).

for localpkg_instlink in ${host_puavo_pkg_rootdir}/packages/*/installed; do
  test -e "$localpkg_instlink" || continue

  localpkg_name="$(basename "${localpkg_instlink%%/installed}")"

  sysinst_link="${image_puavo_pkg_rootdir}/packages/${localpkg_name}/installed"
  if [ ! -e "$sysinst_link" \
       -o "$sysinst_link" -ot "$localpkg_instlink" ]; then
    puavo-pkg reconfigure "$localpkg_name" || status=1
  fi
done

exit $status
