#!/bin/sh

set -eu

firewall_enable=0
if [ "$(puavo-conf puavo.hosttype)" = 'bootserver' ]; then
  firewall_enable=1

  touch /var/log/ulog/shorewall.log
  chown ulog:adm /var/log/ulog/shorewall.log
  chmod 640 /var/log/ulog/shorewall.log
fi

sed -i "s/^startup=.*\$/startup=${firewall_enable}/" \
       /etc/default/shorewall
