#!/bin/sh

set -eu

upstream_version=$(dpkg-parsechangelog -S Version | sed -r -n 's/^(.*)-.*$/\1/p')
upstream_dir=$(dpkg-parsechangelog -S Version | sed -r -n 's/^([0-9]+\.[0-9]+)\..*$/\1/p')
orig_tarball="../libpam-envfeed_${upstream_version}.orig.tar.xz"

if [ ! -e "${orig_tarball}" ]; then
    wget -O "${orig_tarball}.tmp" \
         "ftp://ftp.uhulinux.hu/pub/sources/pam_envfeed/pam_envfeed-${upstream_version}.tar.gz"
    mv "${orig_tarball}.tmp" "${orig_tarball}"
fi

tar -z -x -f "${orig_tarball}" --strip-components=1
