#!/bin/sh

set -eu

veyon_keys_dir=/images/veyon/keys

if [ -e "${veyon_keys_dir}/private" -a -e "${veyon_keys_dir}/public" ]; then
  exit 0
fi

rm -f /etc/veyon/keys/private/veyonkey/key \
      /etc/veyon/keys/public/veyonkey/key

veyon-cli authkeys create veyonkey

mkdir -p "$veyon_keys_dir"

# XXX security!
install -o root -g root -m 644 /etc/veyon/keys/private/veyonkey/key \
        "${veyon_keys_dir}/private.pem"
install -o root -g root -m 644 /etc/veyon/keys/public/veyonkey/key \
        "${veyon_keys_dir}/public.pem"
