#!/bin/sh
set -e

PORT=43248

# start local http server
python3 -m http.server $PORT &
HTTP_PID=$!
trap "kill $HTTP_PID" EXIT TERM INT
# let the http server settle down
for i in $(seq 30); do
    ss -nlt | grep -qF :$PORT && break
    sleep 1
done

aria2c -d $AUTOPKGTEST_TMP http://localhost:$PORT/debian/control

# verify that files are identical
cmp debian/control $AUTOPKGTEST_TMP/control
