#!/bin/sh

set -eu

build_basedir=$1

previous_buildtarget_file=~/.config/puavo-build-image/previous-ask-buildtarget

get_dirs() {
  build_basedir=$1
  test -d "$build_basedir" || return 0
  for dir in $(ls -1 "$build_basedir"); do
    [ -d "${build_basedir}/${dir}" ] && echo "${dir}"
  done
}

write_output_and_exit() {
  target_dir=$1

  mkdir -p "$(dirname $previous_buildtarget_file)"
  echo "$target_dir" > "$previous_buildtarget_file"

  echo "${build_basedir}/${target_dir}" # THE output of the script
  exit 0
}

target_dirs=$(get_dirs "$build_basedir")

if [ -z "$target_dirs" ]; then
  echo "No build directories could be found under ${build_basedir}" >&2
  exit 1
fi

if [ "$(echo "$target_dirs" | wc -l)" -eq 1 ]; then
  # do not bother asking anything, only one choice
  write_output_and_exit "$target_dirs"
fi

default_choice_name=$(cat "$previous_buildtarget_file" 2>/dev/null || true)

default_choice_num=$(
  echo "$target_dirs" \
    | awk -v default_choice_name="$default_choice_name" '
        $1 == default_choice_name { print NR }
      ')

while true; do
  {
    echo "Available image builds are:"
    echo
    echo "$target_dirs" | xargs -n1 | awk '{ printf "\t[%d] %s\n", NR, $1 }'
    echo
  } | more >&2

  read -p "Choose build [$default_choice_num]: " target_dir_num
  target_dir=$(
    echo "$target_dirs" \
      | awk -v default_choice_num="$default_choice_num" \
            -v target_dir_num="$target_dir_num" '
          NR == target_dir_num { print $1; exit(0) }
          NR == default_choice_num { target_dir = $1 }
          END { if (target_dir_num == "") { print target_dir } }
        ')

  [ -n "${target_dir}" -a -d "${build_basedir}/${target_dir}" ] && break

  echo 'No such target directory' >&2
  sleep 1
  echo >&2
done

write_output_and_exit "$target_dir"
