#!/bin/sh

set -eu

usage() {
    cat <<EOF
Usage:
  puavo-imgbuild-tool --build imagetype
                      --buildrule-dirs buildrule-dirs
                      --buildrules buildrules
                      --chroot-configure-script chroot-configure-script
                      --configure-bootstrap-rules rule-classes
                      --image-configure-script image-configure-script
                      --extra-packages-dir extra-packages-dir
                      --image-excludes-file image-excludes-file
                      --release-name release-name
                      --target-dir target-dir

  puavo-imgbuild-tool --apply-buildrules
                      --buildrule-dirs buildrule-dirs
                      --buildrules buildrules
                      --chroot-configure-script chroot-configure-script
                      --image-configure-script image-configure-script
                      --target-dir target-dir

  puavo-imgbuild-tool --setup-local-packages
                      --buildrule-dirs buildrule-dirs
                      --chroot-configure-script chroot-configure-script
                      --image-configure-script image-configure-script
                      --extra-packages-dir extra-packages-dir
                      --target-dir target-dir

  puavo-imgbuild-tool --update-chroot
                      --buildrule-dirs buildrule-dirs
                      --buildrules buildrules
                      --chroot-configure-script chroot-configure-script
                      --image-configure-script image-configure-script
                      --extra-packages-dir extra-packages-dir
                      --target-dir target-dir

  puavo-imgbuild-tool --image
                      --image-excludes-file image-excludes-file
                      --images-dir images-dir
                      --release-name release-name
                      --target-dir target-dir

  puavo-imgbuild-tool --chroot         --target-dir target-dir
  puavo-imgbuild-tool --cleanup-chroot --target-dir target-dir

  An optional --builds-dir argument can be given to all actions.  If
  --target-dir is not set but --builds-dir is, --target-dir is asked
  interactively.

  --image-excludes-file defaults to /etc/puavo-image-tools/puavoimage.excludes

  --buildrule-dirs is a comma-separated list of directories
    that contain rules for building images

  --buildrules is a comma-separated list of buildrules
    (currently a list of puppet classes)

  --build takes optional arguments:

    --apt-proxy    [default is "localhost:3142", "no" may be used to turn off]
    --arch         [default is the same as in buildhost]
    --distribution [default is the same as in buildhost]
    --mirror       [default is "ftp.debian.org"]

EOF
    exit 1
}

get_default_for() {
  if [ -e ~/.config/puavo-build-image/defaults ]; then
    awk -v key="$1" '$1 == key { print $2 }' \
      ~/.config/puavo-build-image/defaults
  fi
}

if ! args=$(getopt -n "$0" -o + \
              -l 'apply-buildrules,apt-proxy:,arch:,build:,buildrules:,buildrule-dirs:,builds-dir:,chroot,chroot-configure-script:,cleanup-chroot,configure-bootstrap-rules:,distribution:,extra-packages-dir:,image,image-configure-script:,image-excludes-file:,images-dir:,setup-local-packages,mirror:,release-name:,target-dir:,update-chroot' \
              -- "$@"); then
  usage
fi

# defaults for these parameters (can be overridden on the command line args)
arch=$(dpkg --print-architecture)
distribution=$(lsb_release -cs) # take the buildhost distribution as default
                                # (jessie, stretch, ...)

buildrules=
extra_packages_dir=
imagetype=
release_name=
target_dir=

# parameters with config defaults
apt_proxy=$(get_default_for apt-proxy)
buildrule_dirs=$(get_default_for buildrule-dirs)
builds_dir=$(get_default_for builds-dir)
chroot_configure_script=$(get_default_for chroot-configure-script)
configure_bootstrap_rules=$(get_default_for configure-bootstrap-rules)
image_configure_script=$(get_default_for image-configure-script)
image_excludes_file=$(get_default_for image-excludes-file)
images_dir="$(get_default_for images-dir)"
mirror="$(get_default_for mirror)"

[ -z "$apt_proxy"           ] && apt_proxy="localhost:3142"
[ -z "$images_dir"          ] && images_dir="/opt/ltsp/images"
[ -z "$mirror"              ] && mirror="ftp.debian.org"
[ -z "$image_excludes_file" ] \
  && image_excludes_file="/etc/puavo-image-tools/puavoimage.excludes"

eval "set -- $args"
while [ $# -ne 0 ]; do
  case "$1" in
    --apply-buildrules       \
    | --chroot               \
    | --cleanup-chroot       \
    | --image                \
    | --setup-local-packages \
    | --update-chroot)
      action=${1#--}; shift
      ;;
    --build)
      action=${1#--}; imagetype=$2; shift; shift
      ;;

    --apt-proxy)
      apt_proxy=$2; shift; shift
      ;;
    --arch)
      arch=$2; shift; shift
      ;;
    --buildrule-dirs)
      buildrule_dirs=$2; shift; shift
      ;;
    --buildrules)
      buildrules=$2; shift; shift
      ;;
    --builds-dir)
      builds_dir=$2; shift; shift
      ;;
    --chroot-configure-script)
      chroot_configure_script=$2; shift; shift
      ;;
    --configure-bootstrap-rules)
      configure_bootstrap_rules=$2; shift; shift
      ;;
    --distribution)
      distribution=$2; shift; shift
      ;;
    --extra-packages-dir)
      extra_packages_dir=$2; shift; shift
      ;;
    --image-configure-script)
      image_configure_script=$2; shift; shift
      ;;
    --image-excludes-file)
      image_excludes_file=$2; shift; shift
      ;;
    --images-dir)
      images_dir=$2; shift; shift
      ;;
    --mirror)
      mirror=$2; shift; shift
      ;;
    --release-name)
      release_name=$2; shift; shift
      ;;
    --target-dir)
      target_dir=$2; shift; shift
      ;;
    --)
      shift; break;
      ;;
    *)
      usage
      ;;
  esac
done

[ "$apt_proxy" = "no" ] && apt_proxy=
if [ -n "$apt_proxy" ]; then
  mirror_maybe_proxied="http://${apt_proxy}/${mirror}/debian/"
else
  mirror_maybe_proxied="http://${mirror}/debian/"
fi

chroot_arch=$(run_configure_chroot -- --get-arch 2>/dev/null || true)
if [ -n "$chroot_arch" ]; then
  if [ -n "$arch" -a "$chroot_arch" != "$arch" ]; then
    echo "Requested arch ($arch) does not match chroot arch ($chroot_arch)" >&2
    exit 1
  fi
  arch=$chroot_arch
fi

if [ -z "$target_dir" ]; then
  if [ -z "$builds_dir" ]; then
    echo 'Cannot determine target dir, set --target-dir or --builds-dir' >&2
    usage
  fi

  if [ "$action" = "build" ]; then
    if [ -z "$imagetype" ]; then
      echo 'Imagetype must be set' >&2
      usage
    fi
    target_dir="${builds_dir}/${imagetype}-${distribution}-${arch}"
  else
    target_dir=$(/usr/lib/puavo-image-tools/puavo-ask-buildtarget-dir \
		 "$builds_dir")
  fi
fi


run_configure_chroot() {
  if [ ! -x "$chroot_configure_script" ]; then
    echo "Chroot configure script '${chroot_configure_script}' not found" \
         "or not executable" >&2
    return 1
  fi

  "$chroot_configure_script" --target-dir "$target_dir" "$@"
}

dirs_with_postfix() {
  dirlist=$1
  postfix=$2

  echo "$dirlist" \
    | awk -F, -v postfix="$postfix" '
        { for (i = 1; i <= NF; i++) { print $i postfix } }
      '
}

get_imagetype() { run_configure_chroot -- --get-imagetype; }

log_phase() { echo ">>>>> IN PHASE: $1 <<<<<"; }

wipe_chroot() {
  log_phase 'wipe-chroot'
  run_configure_chroot --wipe-chroot
}

build_chroot() {
  wipe_chroot

  log_phase 'debootstrap'
  debootstrap --arch="$arch"                                   \
              --components=main,restricted,universe,multiverse \
              --include=lsb-release                            \
              "$distribution" "$target_dir" "$mirror_maybe_proxied"
}

apply_buildrules() {
  buildrules_to_be_applied=$1; shift

  log_phase 'apply-buildrules'
  run_configure_chroot --apply-buildrules                       \
                       --buildrule-dirs "$buildrule_dirs"       \
                       --                                       \
                       --buildrules "$buildrules_to_be_applied" \
                       "$@"
}

setup_local_packages() {
  log_phase 'setup-local-packages'

  package_dirs="$(dirs_with_postfix \
                    "${buildrule_dirs}" \
                    "/packages/$(get_imagetype)-${distribution}-${arch}")"
  package_dirs="$package_dirs $extra_packages_dir"

  run_configure_chroot --setup-local-packages "$package_dirs"
}

apt_dist_upgrade() {
  log_phase 'dist-upgrade'
  run_configure_chroot -- --apt-dist-upgrade
}

apt_update() {
  log_phase 'apt-update'
  run_configure_chroot -- --apt-update
}

bootstrap_configure() {
  configure_bootstrap_rules=$1

  log_phase 'bootstrap-configure'
  run_configure_chroot --bootstrap                                        \
                       --image-configure-script "$image_configure_script" \
                       -- --apt-proxy "$apt_proxy"                        \
                          --imagetype "$imagetype"                        \
                          --mirror    "$mirror"

  if [ -n "$configure_bootstrap_rules" ]; then
    apply_buildrules "$configure_bootstrap_rules"
  fi
}

update_chroot() {
  buildrules=$1

  setup_local_packages
  apt_update
  apply_buildrules "$buildrules"
  apt_dist_upgrade
  apply_buildrules "$buildrules" --verify-rule-stability

  touch "${target_dir}/tmp/.update_chroot_done"
}

make_image() {
  release_name=$1

  log_phase 'make-image'

  run_configure_chroot -- --prepare-image --image-release "$release_name"

  ltspimage_name=$(run_configure_chroot -- --get-imagename)

  mkdir -p "$images_dir"
  mksquashfs "$target_dir" "${images_dir}/${ltspimage_name}.tmp" \
             -noappend                                         \
             -ef "${image_excludes_file}"                      \
             -wildcards
  mv "${images_dir}/${ltspimage_name}.tmp" "${images_dir}/${ltspimage_name}"
  echo "Successfully created a squashfs image: ${images_dir}/${ltspimage_name}"
}

if [ "$(id -u)" -ne 0 ]; then
  echo 'Run me as root' >&2
  exit 1
fi

case "$action" in
  apply-buildrules)
    apply_buildrules "$buildrules" --verify-rule-stability
    ;;
  build)
    if [ -e "${target_dir}/tmp/.update_chroot_done" ]; then
      {
        echo "Build for $(basename $target_dir) has already been successfully"
        echo "done.  Do --cleanup-chroot if you want to throw away the build."
      } >&2
      exit 1
    fi

    build_chroot
    bootstrap_configure "$configure_bootstrap_rules"
    update_chroot "$buildrules"
    make_image "$release_name"
    ;;
  chroot)
    run_configure_chroot -- --shell
    ;;
  cleanup-chroot)
    rm -rf "$target_dir"
    ;;
  image)
    make_image "$release_name"
    ;;
  setup-local-packages)
    setup_local_packages
    ;;
  update-chroot)
    update_chroot "$buildrules"
    ;;
esac

exit 0
