#!/bin/sh

set -eu

on_exit()
{
    local exitval=$?

    set +eu
    trap '' EXIT HUP INT QUIT ABRT ALRM TERM USR1 USR2

    [ -z "${tmpfile}" ] || rm -f "${tmpfile}"

    exit $exitval
}

if [ $# -ne 3 ]; then
    echo "$(basename $0): wrong number of arguments" >&2
    echo "Usage: $(basename $0) VTUND_PID VTUND_CONF_FILE BRIDGE" >&2
    exit 1
fi

vtund_pid=$1
vtund_conf_file=$2
bridge=$3

read network

## Quit if the network is already there.
sed -nr "/^${network} \{/q1" "${vtund_conf_file}" || exit

. puavo-wlangw-env

tmpfile=""

trap on_exit EXIT HUP INT QUIT ABRT ALRM TERM USR1 USR2

tmpfile=$(mktemp)

cp -a "${vtund_conf_file}" "${tmpfile}"

sed -e "s|#{LIBDIR}|${PWGW_LIBDIR}|g" \
    -e "s|#{BRIDGE}|${bridge}|g" \
    -e "s|#{NETWORK}|${network}|g" \
    "${PWGW_DATADIR}/vtund_network.conf" \
    >>"${tmpfile}"

mv "${tmpfile}" "${vtund_conf_file}"

kill -HUP "${vtund_pid}"
