#!/bin/sh

set -eu

upstream_version=$(dpkg-parsechangelog -S Version | sed -r -n 's/^(.*)-.*$/\1/p')
orig_tarball="../openjdk-11_${upstream_version}.orig.tar.xz"

if [ ! -e "${orig_tarball}" ]; then
  wget -O "${orig_tarball}.tmp" \
       "deb.debian.org/debian/pool/main/o/openjdk-11/openjdk-11_${upstream_version}.orig.tar.xz"
  tar -Jxf "${orig_tarball}.tmp" --strip-components=1
  mv "${orig_tarball}.tmp" "${orig_tarball}"
fi
