#!/bin/sh

set -eu

echo ">>>>> Configuring bootserver network interfaces"

apt-get -y install bridge-utils vlan

cat <<'EOF' > /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet manual
 
auto eth1
iface eth1 inet manual

auto inet0
iface inet0 inet dhcp
        bridge_ports eth0
        bridge_stp off
        bridge_fd 0
        bridge_maxwait 0

auto ltsp0
iface ltsp0 inet static
	address 10.249.0.240
	netmask 255.255.252.0
	bridge_ports eth1
	bridge_stp off
	bridge_fd 0
	bridge_maxwait 0

auto wlan0
iface wlan0 inet static
	address 10.249.239.254
	netmask 255.255.240.0
	bridge_ports none
	bridge_stp off
	bridge_fd 0
	bridge_maxwait 0
EOF
