#!/bin/sh

MINKVER="2.6.17"
PREREQ=""

# Output pre-requisites
prereqs()
{
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

test "$BOOT" = "puavo" || exit 0

if [ -e /dev/mapper/puavo-crypthome ]; then
  clevis luks unlock -d /dev/mapper/puavo-crypthome -n puavo-home
fi
