#!/bin/sh

# THIS SCRIPT OVERWRITES PUAVO-CONF VARIABLES

set -eu

graphics_driver=$(puavo-conf puavo.graphics.driver)

glx_alternative=
nvidia_alternative=
use_nvidia_persistenced=false

case "$graphics_driver" in
  nvidia)
    glx_alternative=/usr/lib/nvidia
    nvidia_alternative=current
    use_nvidia_persistenced=true
    xserver_driver=nvidia
    ;;
  nvidia-390)
    glx_alternative=/usr/lib/nvidia
    nvidia_alternative=legacy-390xx
    use_nvidia_persistenced=true
    xserver_driver=nvidia
    ;;
  *)
    xserver_driver=${graphics_driver}
    ;;
esac

if [ -n "$glx_alternative" ]; then
  update-glx --set glx "$glx_alternative" >/dev/null 2>&1
fi

if [ -n "$nvidia_alternative" ]; then
  if [ -d "/usr/lib/nvidia/${nvidia_alternative}" ]; then
    update-glx --set nvidia "/usr/lib/nvidia/${nvidia_alternative}" \
      >/dev/null 2>&1
  else
    update-glx --set nvidia /usr/lib/nvidia/current \
      >/dev/null 2>&1
  fi
fi

if $use_nvidia_persistenced; then
  puavo-conf puavo.service.nvidia-persistenced.enabled true
fi
