Document: logrelay
Title: Debian logrelay Manual
Author: <insert document author here>
Abstract: This manual describes what logrelay is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/logrelay/logrelay.sgml.gz

Format: postscript
Files: /usr/share/doc/logrelay/logrelay.ps.gz

Format: text
Files: /usr/share/doc/logrelay/logrelay.text.gz

Format: HTML
Index: /usr/share/doc/logrelay/html/index.html
Files: /usr/share/doc/logrelay/html/*.html
