#!/bin/sh

set -e

## Initramfs hook for Puavo devices.

MINKVER="2.6.17"
PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac


. /usr/share/initramfs-tools/hook-functions

manual_add_modules aufs
manual_add_modules overlay
manual_add_modules overlayfs
manual_add_modules squashfs

mkdir -p ${DESTDIR}/usr/bin/ \
         ${DESTDIR}/usr/lib/ \
         ${DESTDIR}/usr/lib/x86_64-linux-gnu/ \
         ${DESTDIR}/usr/local/lib/ \
         ${DESTDIR}/usr/sbin/

copy_exec /usr/bin/lspci                  /usr/bin
copy_exec /usr/bin/lsusb                  /usr/bin
copy_exec /usr/bin/ruby                   /usr/bin
copy_exec /usr/local/bin/puavo-conf       /usr/bin
copy_exec /usr/local/sbin/puavo-conf-mkdb /usr/bin
copy_exec /usr/sbin/dmidecode             /usr/sbin

cp -R /usr/lib/ruby ${DESTDIR}/usr/lib/
cp -R /usr/lib/x86_64-linux-gnu/libffi* ${DESTDIR}/usr/lib/x86_64-linux-gnu
cp -R /usr/lib/x86_64-linux-gnu/ruby ${DESTDIR}/usr/lib/x86_64-linux-gnu/
cp -R /usr/local/lib/site_ruby ${DESTDIR}/usr/local/lib

ln -s libpuavoconf.so.0 ${DESTDIR}/usr/local/lib/libpuavoconf.so
