# Signing backend:
# - file: PEM keys on disk
# - pkcs11: HSM token (.uri files contain HSM token URIs)
SIGNING_BACKEND=file

# OpenSSL engine for PKCS#11.
# The engine is used by both ukify and sbsign.
SIGNING_ENGINE="pkcs11"

# OpenSSL 3.x provider.
# The engine is used by ukify.
SIGNING_PROVIDER=""
