#!/bin/sh

# For now, use the ltsp upstream X configuration mechanism,
# but get the values for it from /etc/puavo/device.json.
PUAVO_XSERVER=$(jq -r .graphics_driver /etc/puavo/device.json)
XSERVER=${PUAVO_XSERVER:-$XSERVER}

# Do X settings using the standard LTSP configuration tools
. /usr/share/ltsp/screen-x-common

# Link to the ltsp-generated xorg.conf (created above) so that lightdm/X can
# use it.  However, do not overwrite the default /etc/X11/xorg.conf if it
# exists, in case something has created it in some way.
ln -s /var/run/ltsp-xorg.conf /etc/X11/xorg.conf 2>/dev/null
