class packages::backports {
  # This list is used by apt::backports so that these packages will be picked
  # up from backports instead of the usual channels.  The inclusion of a
  # package on this list does not trigger the installation of a package,
  # that has to be defined elsewhere.

  $package_list = [
    # firmware packages
      'firmware-amd-graphics'
    , 'firmware-ath9k-htc'
    , 'firmware-atheros'
    , 'firmware-b43-installer'
    , 'firmware-b43legacy-installer'
    , 'firmware-bnx2'
    , 'firmware-bnx2x'
    , 'firmware-brcm80211'
    , 'firmware-carl9170'
    , 'firmware-cavium'
    , 'firmware-intel-graphics'
    , 'firmware-intel-misc'
    , 'firmware-intel-sound'
    , 'firmware-ipw2x00'
    , 'firmware-ivtv'
    , 'firmware-iwlwifi'
    , 'firmware-libertas'
    , 'firmware-linux'
    , 'firmware-linux-free'
    , 'firmware-linux-nonfree'
    , 'firmware-marvell-prestera'
    , 'firmware-mediatek'
    , 'firmware-misc-nonfree'
    , 'firmware-myricom'
    , 'firmware-netronome'
    , 'firmware-netxen'
    , 'firmware-nvidia-graphics'
    , 'firmware-nvidia-gsp'
    , 'firmware-qcom-media'
    , 'firmware-qcom-soc'
    , 'firmware-qlogic'
    , 'firmware-realtek'
    , 'firmware-samsung'
    , 'firmware-siano'
    , 'firmware-sof-signed'
    , 'firmware-ti-connectivity'
    , 'firmware-zd1211'

    # Libreoffice from backports
    , 'fonts-opensymbol'
    , 'liblibreoffice-java'
    , 'libreoffice'
    , 'libreoffice-base'
    , 'libreoffice-base-core'
    , 'libreoffice-base-drivers'
    , 'libreoffice-calc'
    , 'libreoffice-common'
    , 'libreoffice-core'
    , 'libreoffice-draw'
    , 'libreoffice-gnome'
    , 'libreoffice-gtk3'
    , 'libreoffice-help-common'
    , 'libreoffice-help-de'
    , 'libreoffice-help-en-gb'
    , 'libreoffice-help-fi'
    , 'libreoffice-help-fr'
    , 'libreoffice-help-sv'
    , 'libreoffice-impress'
    , 'libreoffice-java-common'
    , 'libreoffice-l10n-de'
    , 'libreoffice-l10n-en-gb'
    , 'libreoffice-l10n-en-za'
    , 'libreoffice-l10n-fi'
    , 'libreoffice-l10n-fr'
    , 'libreoffice-l10n-sv'
    , 'libreoffice-l10n-uk'
    , 'libreoffice-librelogo'
    , 'libreoffice-math'
    , 'libreoffice-nlpsolver'
    , 'libreoffice-report-builder'
    , 'libreoffice-report-builder-bin'
    , 'libreoffice-script-provider-bsh'
    , 'libreoffice-script-provider-js'
    , 'libreoffice-script-provider-python'
    , 'libreoffice-sdbc-firebird'
    , 'libreoffice-sdbc-hsqldb'
    , 'libreoffice-sdbc-mysql'
    , 'libreoffice-sdbc-postgresql'
    , 'libreoffice-style-colibre'
    , 'libreoffice-style-elementary'
    , 'libreoffice-uiconfig-base'
    , 'libreoffice-uiconfig-calc'
    , 'libreoffice-uiconfig-common'
    , 'libreoffice-uiconfig-draw'
    , 'libreoffice-uiconfig-impress'
    , 'libreoffice-uiconfig-math'
    , 'libreoffice-uiconfig-report-builder'
    , 'libreoffice-uiconfig-writer'
    , 'libreoffice-wiki-publisher'
    , 'libreoffice-writer'
    , 'libuno-cppu3t64'
    , 'libuno-cppuhelpergcc3-3t64'
    , 'libunoloader-java'
    , 'libuno-purpenvhelpergcc3-3t64'
    , 'libuno-sal3t64'
    , 'libuno-salhelpergcc3-3t64'
    , 'python3-uno'
    , 'uno-libs-private'
    , 'ure'
    , 'ure-java'

    # updates needed by VirtualBox
    , 'curl'
    , 'libcurl3t64-gnutls'
    , 'libcurl3t64-gnutls:i386'
    , 'libcurl4-openssl-dev'
    , 'libcurl4t64'
    , 'libcurl4t64:i386'
    , 'libnghttp3-9'
    , 'libnghttp3-9:i386'
    , 'libnghttp3-dev'
    , 'libngtcp2-16'
    , 'libngtcp2-16:i386'
    , 'libngtcp2-crypto-gnutls8'
    , 'libngtcp2-crypto-gnutls8:i386'
    , 'libngtcp2-dev'
  ]
}
