#!/bin/sh

set -eu

output=$(hostapd_cli all_sta)
devices=$(echo -n $output | sed -n 's/^dot11RSNAStatsSTAAddress=//p' | tr '\n' ',')

puavo-wlanap-report <<EOF
wlan_event:hotspot_state
connected_devices:[$devices]
EOF
