#!/bin/sh

ifconfig $1 up
brctl addbr $2
brctl setfd $2 0
ifconfig $2 up
brctl addif $2 $1
sleep 2
hostapd -B -P /var/run/puavo-wlanap/hostapd.pid /var/run/puavo-wlanap/hostapd.conf
sleep 2
dhclient -pf /var/run/puavo-wlanap/dhclient.pid $2
