'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH OpenBoard 1 "Dec 2020" "Version 1.5.4" "OpenBoard"
.SH NAME
OpenBoard \- cross-platform Interactive White-Board Application
.SH SYNOPSIS
'nh
.fi
.ad l
\fBOpenBoard\fR

.SH DESCRIPTION
\fBOpenBoard\fR is an open source cross-platform interactive white board
application designed primarily for use in schools. It was originally
forked from Open-Sankoré, which was itself based on Uniboard.
.PP
Supported platforms are Windows (7+), OS X (10.9+) and Linux.
.PP
.SH OPTIONS
\fBOpenBoard\fR does not have any known application specific options.
However, it (probably) command line options provided by the Qt5 widget
toolkit (which is used by OpenBoard for rendering its graphical UI).
.PP
.SH AUTHOR
This manual has been written by Mike Gabriel
<mike.gabriel@das-netzwerkteam.de> for the Debian project
(https://www.debian.org/) and may be used by others.
