#! /bin/sh

### BEGIN INIT INFO
# Provides:		ltspsshd
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	OpenBSD Secure Shell server
### END INIT INFO

set -e

# /etc/init.d/ltspssh: start and stop the OpenBSD "secure shell(tm)" daemon

test -x /usr/sbin/ltspsshd || exit 0
( /usr/sbin/ltspsshd -\? 2>&1 | grep -q OpenSSH ) 2>/dev/null || exit 0

chrooted() {
    # borrowed from udev's postinst
    # and then borrowed from initramfs-tools's preinst
    if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]; then
	# the devicenumber/inode pair of / is the same as that of
	# /sbin/init's root, so we're *not* in a chroot and hence
	# return false.
	return 1
    fi
    return 0
}

# The init.d script is only for chroots
if [ -e /etc/init/ltspssh.conf ] && ! chrooted; then
    exec /lib/init/upstart-job ltspssh "$@"
fi

umask 022

if test -f /etc/default/ltspssh; then
    . /etc/default/ltspssh
fi

. /lib/lsb/init-functions

if [ -n "$2" ]; then
    SSHD_OPTS="$SSHD_OPTS $2"
fi

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_for_no_start() {
    # forget it if we're trying to start, and /etc/ssh/ltspsshd_not_to_be_run exists
    if [ -e /etc/ssh/ltspsshd_not_to_be_run ]; then 
	if [ "$1" = log_end_msg ]; then
	    log_end_msg 0 || true
	fi
	if ! run_by_init; then
	    log_action_msg "OpenBSD Secure Shell server not in use (/etc/ssh/ltspsshd_not_to_be_run || true
	fi
	exit 0
    fi
}

check_dev_null() {
    if [ ! -c /dev/null ]; then
	if [ "$1" = log_end_msg ]; then
	    log_end_msg 1 || true
	fi
	if ! run_by_init; then
	    log_action_msg "/dev/null is not a character device!" || true
	fi
	exit 1
    fi
}

check_privsep_dir() {
    # Create the PrivSep empty dir if necessary
    if [ ! -d /var/run/ltspsshd ]; then
	mkdir /var/run/ltspsshd
	chmod 0755 /var/run/ltspsshd
    fi
}

check_config() {
    if [ ! -e /etc/ssh/ltspsshd_not_to_be_run ]; then
	/usr/sbin/ltspsshd $LTSPSSHD_OPTS -t || exit 1
    fi
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	check_privsep_dir
	check_for_no_start
	check_dev_null
	log_daemon_msg "Starting OpenBSD Secure Shell server" "ltspsshd" || true
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/ltspsshd.pid --exec /usr/sbin/ltspsshd -- $LTSPSSHD_OPTS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping OpenBSD Secure Shell server" "ltspsshd" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/ltspsshd.pid then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  reload|force-reload)
	check_for_no_start
	check_config
	log_daemon_msg "Reloading OpenBSD Secure Shell server's configuration" "ltspsshd" || true
	if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /var/run/ltspsshd.pid --exec /usr/sbin/ltspsshd; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	check_privsep_dir
	check_config
	log_daemon_msg "Restarting OpenBSD Secure Shell server" "ltspsshd" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/ltspsshd.pid
	check_for_no_start log_end_msg
	check_dev_null log_end_msg
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/ltspsshd.pid --exec /usr/sbin/ltspsshd -- $LTSPSSHD_OPTS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  try-restart)
	check_privsep_dir
	check_config
	log_daemon_msg "Restarting OpenBSD Secure Shell server" "ltspsshd" || true
	RET=0
	start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/ltspsshd.pid || RET="$?"
	case $RET in
	    0)
		# old daemon stopped
		check_for_no_start log_end_msg
		check_dev_null log_end_msg
		if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/ltspsshd.pid --exec /usr/sbin/ltspsshd -- $LTSPSSHD_OPTS; then
		    log_end_msg 0 || true
		else
		    log_end_msg 1 || true
		fi
		;;
	    1)
		# daemon not running
		log_progress_msg "(not running)" || true
		log_end_msg 0 || true
		;;
	    *)
		# failed to stop
		log_progress_msg "(failed to stop)" || true
		log_end_msg 1 || true
		;;
	esac
	;;

  status)
	status_of_proc -p /var/run/ltspsshd.pid /usr/sbin/ltspsshd ltspsshd && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/ltspssh {start|stop|reload|force-reload|restart|try-restart|status}" || true
	exit 1
esac

exit 0
