#!/bin/sh

set -eu

if [ "$(puavo-conf puavo.abitti.factory.enabled)" = "true" ]; then
    session_manager='/usr/lib/puavo-ltsp-client/abitti-factory-session'

    abitti_home='/home/abitti'
    abitti_uid='997'
    abitti_user='abitti'

    useradd --system --create-home --home-dir "$abitti_home"      \
            --comment "Abitti USB Factory" --groups "disk" --user-group \
            --shell /bin/bash --uid "$abitti_uid" "$abitti_user"
    ;;
else
    session_manager='/usr/bin/gnome-session'
fi

ln -fns "$session_manager" /etc/alternatives/x-session-manager

exit 0
