#!/bin/sh

set -eu

source puavo-wlanap-dnsproxy-env
source "${PWAP_DATADIR}/config"
source "${PWAP_CONFDIR}/config" || true

networkcache="${PWAP_DNSPROXY_STATEDIR}/networkcache"
touch "${networkcache}"
echo "vtun-up $2" | nc -U "${PWAP_DNSPROXY_RUNDIR}/control.socket" || {
    flock "${networkcache}" -c "echo $2 >>'${networkcache}'"
}
