#!/usr/bin/ruby
#
# Copyright 2013, 2026 Opinsys Oy
#
# Script to do dynamic DNS updates. Both forward and reverse records are
# updated. Multiple servers can be updated simultaneously.
#
#
# CONFIGURATION
#
# The script uses defaults that work out-of-the-box when used on Puavo
# LTSP bootservers and internal networks are in 10.0.0.0/8 range.
#
# Configuration Defaults
#
# domain         is read from /etc/puavo/domain
# reverse_domain 10.in-addr.arpa
# servers        127.0.0.1:553
# key_name       is read from /etc/dhcp/ddns-keys/nsupdate.key
# key            is read from /etc/dhcp/ddns-keys/nsupdate.key
#
# The /etc/puavo-conf/scripts/setup_dns script sets up
# /etc/bind/named.conf.local and /etc/dhcp/ddns-keys/nsupdate.key at boot.

require 'dnsruby'
require 'net/ldap'
require 'openssl'
include Dnsruby

$server_puavo_domain = File.read('/etc/puavo/domain').chomp

def lookup_hostname_by_mac(mac)
  base                  = File.read('/etc/puavo/ldap/base'    ).chomp
  dn                    = File.read('/etc/puavo/ldap/dn'      ).chomp
  password              = File.read('/etc/puavo/ldap/password').chomp
  server_puavo_hostname = File.read('/etc/puavo/hostname'     ).chomp

  ldap = Net::LDAP.new(
    host:       "#{ server_puavo_hostname }.#{ $server_puavo_domain }",
    encryption: {
      method: :start_tls,
      tls_options: {
        ca_file:     '/etc/puavo-conf/rootca.pem',
        verify_mode: OpenSSL::SSL::VERIFY_PEER,
      },
    },
    auth: { method: :simple, username: dn, password: password },
  )

  filter = Net::LDAP::Filter.equals('macAddress', mac)

  begin
    entries = ldap.search(base: "ou=Hosts,#{ base }",
                          filter: filter,
                          attributes: ['cn'])
    unless entries then
      warn("LDAP search failed: #{ ldap.get_operation_result.message }")
      return nil
    end
  rescue Net::LDAP::Error, SystemCallError => e
    warn("LDAP connection failed: #{ e.message }")
    return nil
  end

  entry = entries.first
  entry ? entry[:cn].first : nil
end

type, mac, ip, subdomain = *ARGV

config = {
  'domain'          => $server_puavo_domain,
  'reverse_domain'  => '10.in-addr.arpa',
  'servers'         => [ '127.0.0.1:553' ],
}

tmp = File.read('/etc/dhcp/ddns-keys/nsupdate.key')
if /key "(.*?)"/.match(tmp) then
  config['key_name'] = $1
end
if /secret "(.*?)"/.match(tmp) then
  config['key'] = $1
end

if type.eql?('mac') then
  mac = mac.split(':').map {|x|
    if x.length == 1
      "0#{x}"
    else
      x
    end
  }.join(':')

  hostname = lookup_hostname_by_mac(mac)

  if !hostname then
    puts("No name for mac #{ mac }")
    exit 0
  end
elsif type.eql?('hostname') then
  hostname = mac
else
  raise("type should be either 'hostname' or 'mac'")
end

fqdn = "#{ hostname }.#{ subdomain }.#{ $server_puavo_domain }"

# Loop through all servers and update the A and reverse PTR records.
# The records are first deleted and then added.

exitstatus = 0

config['servers'].each do |url|
  begin
    port = 53
    server = url

    if /(.*):(\d+)/.match(url) then
      server = $1
      port = Integer($2)
    end

    resolver = Dnsruby::Resolver.new({ :nameserver => server })
    resolver.port = (port)
    resolver.tsig = config['key_name'], config['key']

    update = Dnsruby::Update.new(config['domain'])
    update.delete(fqdn, 'A')
    update.add(fqdn, 'A', 60, ip)

    update_reverse = Dnsruby::Update.new(config['reverse_domain'])
    in_addr = "#{ ip.split('.').reverse.join('.') }.in-addr.arpa"

    update_reverse.delete(in_addr)
    update_reverse.add(in_addr, 'PTR', 60, "#{ fqdn }.")

    resolver.send_message(update)
    resolver.send_message(update_reverse)
  rescue StandardError => e
    warn("Update to url '#{ url }' failed: #{ e.message }")
    exitstatus = 1
  end
end

exit(exitstatus)
