[workspace]

[package]
name = "slab"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
publish = false

[[bin]]
name = "slab"
path = "src/main.rs"

[dependencies]
# Raw UEFI protocol structs for writing the next stage loaded image device.
uefi-raw = "0.11"
# UEFI boot services and protocols.
uefi = { version = "0.35", features = ["alloc", "global_allocator", "panic_handler", "logger"] }
# Used for TPM commands and responses.
zerocopy = { version = "0.8", default-features = false, features = ["derive"] }
# Used for internal Secure Boot verifier:
authenticode = { version = "0.5", default-features = false, features = ["object"], optional = true }
object = { version = "0.37", default-features = false, features = ["read_core", "pe", "unaligned"], optional = true }
cms = { version = "0.2", default-features = false, optional = true }
const-oid = { version = "0.9", default-features = false, features = ["db"], optional = true }
der = { version = "0.7", default-features = false, features = ["oid"], optional = true }
rsa = { version = "0.9", default-features = false, features = ["sha2"], optional = true }
sha2 = { version = "0.10", default-features = false, optional = true }

[features]
verifier = [
  "dep:authenticode",
  "dep:cms",
  "dep:const-oid",
  "dep:der",
  "dep:object",
  "dep:rsa",
  "dep:sha2",
]

# Used for internal Secure Boot verifier authorities.
[build-dependencies]
uuid = "1"
rsa = "0.9"
quote = "1"
proc-macro2 = "1"

[profile.dev]
panic = "abort"

# Optimized for size with link time optimization to keep the signed image small.
[profile.release]
panic = "abort"
opt-level = "z"
lto = true
