[workspace]

[package]
name = "slab"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
publish = false

[[bin]]
name = "slab"
path = "src/main.rs"

[dependencies]
# Raw UEFI protocol structs for writing the next stage loaded image device.
uefi-raw = "0.11"
# UEFI boot services and protocols.
uefi = { version = "0.35", features = ["alloc", "global_allocator", "panic_handler", "logger"] }
# Used for TPM commands and responses.
zerocopy = { version = "0.8", default-features = false, features = ["derive"] }

[profile.dev]
panic = "abort"

# Optimized for size with link time optimization to keep the signed image small.
[profile.release]
panic = "abort"
opt-level = "z"
lto = true
