#!/usr/bin/env python3

import dbus
import dbus.mainloop.glib
import getpass
import gettext
import gi
import json
import os
import signal
import sys

gi.require_version('AyatanaAppIndicator3', '0.1')
gi.require_version('Gtk', '3.0')
gi.require_version('Notify', '0.7')

from gi.repository import AyatanaAppIndicator3
from gi.repository import GLib
from gi.repository import Gtk 
from gi.repository import Notify

gettext.bindtextdomain('puavo-exammode-applet', '/usr/share/locale')
gettext.textdomain('puavo-exammode-applet')
_tr = gettext.gettext

dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

# XXX some kind of logging to syslog would be nice

ICON_PATH = '/usr/share/icons/Adwaita/64x64/legacy/text-editor-symbolic.symbolic.png'

class PuavoExamModeApplet:

  def __init__(self):
    Notify.init('puavo-exammode-applet')

    self.dbus_iface = self.get_dbus_iface()
    self.dbus_iface.connect_to_signal('ExamsAvailable', self.exams_available)

    self.indicator \
      = AyatanaAppIndicator3.Indicator.new('puavo-exammode-applet',
          ICON_PATH, AyatanaAppIndicator3.IndicatorCategory.SYSTEM_SERVICES)
    self.indicator.set_status(AyatanaAppIndicator3.IndicatorStatus.ACTIVE)

    self.available_exams = []
    self.update_menu()

    self.register_to_exam_service()


  def get_dbus_iface(self):
    bus = dbus.SystemBus()
    dbusobj = bus.get_object('org.puavo.Exam', '/exammode')
    return dbus.Interface(dbusobj, dbus_interface='org.puavo.Exam.exammode')


  def register_to_exam_service(self):
    try:
      username = getpass.getuser()
      krb5ccname_env = os.environ['KRB5CCNAME']
      lang_locale = os.environ['LANG']
    except:
      # XXX log error
      sys.exit(1)

    self.dbus_iface.Register(username, lang_locale, krb5ccname_env,
                             reply_handler=lambda: None,
                             error_handler=self.register_dbus_error_handler)


  def register_dbus_error_handler(self, dbusexception):
    raise Exception('unexpected dbus error in register, that is bad')


  def update_menu(self):
    self.menu = Gtk.Menu()

    if len(self.available_exams) > 0:
      header = Gtk.MenuItem(label=_tr('Available exams:'))
      header.set_sensitive(False)
      header.show()
      self.menu.append(header)

      separator = Gtk.SeparatorMenuItem()
      separator.show()
      self.menu.append(separator)

      self.menuitems = []
      for exam in self.available_exams:
        # XXX should pick some info from menu
        exam_choice = Gtk.MenuItem(label=exam)
        exam_choice.set_sensitive(True)
        exam_choice.connect('activate', self.choose_exam)
        exam_choice.show()
        self.menu.append(exam_choice)

      self.indicator.set_status(AyatanaAppIndicator3.IndicatorStatus.ACTIVE)
      self.indicator.set_menu(self.menu)

      self.menu.show_all()
    else:
      self.indicator.set_status(AyatanaAppIndicator3.IndicatorStatus.PASSIVE)


  def choose_exam(self, widget):
    # XXX should pass exam id somehow (which one is chosen)
    self.dbus_iface.StartSession(
      reply_handler=lambda: None,
      error_handler=self.start_session_dbus_error_handler)


  def start_session_dbus_error_handler(self, dbusexception):
    raise Exception('unexpected dbus error in start session, that is bad')


  def main(self):
    Gtk.main()


  def exams_available(self, examinfo):
    self.available_exams = json.loads(examinfo)
    self.update_menu()


applet = PuavoExamModeApplet()

if __name__ == '__main__':
  signal.signal(signal.SIGINT, signal.SIG_DFL)
  applet.main()
