[package]
name = "puavo-boot-trust-manager"
version = "0.1.0"
edition = "2024"

[lib]
name = "puavo_boot_trust_manager"
path = "src/lib.rs"

[[bin]]
name = "puavo-boot-trust-manager"
path = "src/main.rs"

[dependencies]
libcryptsetup-rs = { version = "0.15.0", features = ["mutex"] }
loopdev-3 = "0.5.2"
nix = "0.30.1"
tempfile = "3.21.0"
thiserror = "2.0.16"
udev = "0.9.3"
log = "0.4"
env_logger = "0.11"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
rpassword = "7"
sha2 = "0.10.9"
efivar = { git = "https://github.com/iTrooz/efivar-rs", rev = "7ff7ead356a24a3aed61fb755160fe7888224e76" }
tss-esapi = { version = "7.5.1", default-features = false }
tss-esapi-sys = "0.5.0"
hex = "0.4.3"

[dev-dependencies]
serial_test = "3.0"
ctor = "0.2"

[profile.release]
strip = true
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
