#!/bin/sh

CMD=$1
TYPE=$2

if [ ${CMD} = "add" ]; then
  echo "ADD" >> /tmp/jep

  if [ ${TYPE} = "usb" ]; then
    PID=$(ps -ef|grep [j]etpipe\ /dev/usb|awk '{print $2}')

    if [ "x${PID}" != "x" ]; then
      kill $PID
    fi

    /usr/sbin/jetpipe ${DEVNAME} 9100
  else
    PID=$(ps -ef|grep [j]etpipe\ ${DEVNAME}|awk '{print $2}')
    if [ "x${PID}" != "x" ]; then
      kill $PID
    fi

    PORT=$(( $MINOR + 9101 ))

    /usr/sbin/jetpipe ${DEVNAME} ${PORT}
  fi
fi
