#!/bin/sh

homepage_args() {
  if [ -n "$HOMEPAGE" ]; then
    echo "$HOMEPAGE" \
      | awk -F\| '{ for (i = 1; i <= NF; i++) { print "--homepage", $i } }'
  fi
}

default_args="--new-window --no-default-browser-check"

# we do not try to pass --homepage args when we get command line options,
# because it is likely we have an url and chromium-browser will open also
# --homepage args to tabs... we do not want to open all of those.
if [ $# -gt 0 ]; then
  exec /usr/bin/chromium-browser.distrib $default_args "$@"
else
  exec /usr/bin/chromium-browser.distrib $default_args $(homepage_args)
fi
