#!/bin/sh

set -eu

upstream_version=$(dpkg-parsechangelog -S Version | sed -r -n 's/^([0-9]+:)?(.+)-.*$/\2/p')
orig_tarball="../ubuntu-font-family-sources_${upstream_version}.orig.tar.gz"

if [ ! -e "${orig_tarball}" ]; then
    wget -O "${orig_tarball}.tmp" \
         "http://archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-font-family-sources/ubuntu-font-family-sources_${upstream_version}.orig.tar.gz"
    mv "${orig_tarball}.tmp" "${orig_tarball}"
fi

tar -z -x -f "${orig_tarball}" --strip-components=1
