#!/bin/sh

set -eu

puavo_conf_json_dir='/state/etc/puavo/local'
puavo_conf_json_path="${puavo_conf_json_dir}/puavo_conf.json"

read_old_config() {
  if [ -e "$puavo_conf_json_path" ]; then
    cat "$puavo_conf_json_path"
  else
    echo '{}'
  fi
}

if [ $# -ne 2 ]; then
  echo "usage: $(basename $0) key value" >&2
  exit 1
fi

key=$1
value=$2

case "$key" in
  puavo.abitti.version \
  | puavo.grub.boot_default \
  | puavo.grub.developer_mode.enabled \
  | puavo.pkg.* \
  | puavo.xsessions.user_registration.enabled)
    ;;
  *)
    echo "no permission to change puavo-conf '$key' --> '$value'" >&2
    exit 1
    ;;
esac

install -d -o root -g root -m 755 "$puavo_conf_json_dir"

puavo-conf "$key" "$value"

read_old_config \
  | jq --arg key "$key" --arg value "$value" '.[$key] = $value' \
  > "${puavo_conf_json_path}.tmp"
mv "${puavo_conf_json_path}.tmp" \
   "$puavo_conf_json_path"
