#!/bin/bash

set -xeu

sink=$(jq -r .default_audio_sink /etc/puavo/device.json)
source=$(jq -r .default_audio_source /etc/puavo/device.json)

# jq outputs null for non-existing fields, treat them as empty
# strings.
[ "${sink}" = "null" ] && sink=
[ "${source}" = "null" ] && source=

# Quirk for smartboards: if the default sink was not set in Puavo
# and if smartboard audio is connected, set it as default.
if [ -z "${sink}" ]; then
    sink=$(pacmd list-sinks \
        | sed -r -n '/^\s+index: [0-9]+$/ n; s/^\s+name: <(.*C-Media.*)>$/\1/p')
fi

# Default sink/source values provided by Puavo can be in two different
# formats:
# 1) Fields separated by | (ASCII 0x7c)
# 2) Just the sink/source name

if [ -n "${sink}" ]; then
    if grep -q '|' <<<"${sink}"; then
        IFS='|' read card profile sink <<<"${sink}"
        pacmd set-card-profile "${card}" "${profile}"
    fi
    pacmd set-default-sink "${sink}"
fi

if [ -n "${source}" ]; then
    if grep -q '|' <<<"${source}"; then
        IFS='|' read card profile source <<<"${source}"
        pacmd set-card-profile "${card}" "${profile}"
    fi
    pacmd set-default-source "${source}"
fi
