#!/bin/sh

add_account()
{
  USER="guest-$(hostname)"
  HOME=`mktemp -td ${USER}-XXXXXX`

  if PWSTAT=`passwd -S "$USER"` 2>/dev/null; then
    echo "User exists"
  else
    adduser --disabled-password --no-create-home --system --home $HOME --gecos "Guest" --group --shell /bin/bash $USER
  fi

  chown -R $USER:$USER "$HOME"

  SOCKETDIR="/run/puavo/${USER}"
  mkdir -p ${SOCKETDIR}
  chown -R $USER:$USER "${SOCKETDIR}"

  echo $USER
}

remove_account ()
{
  USER=$1

  PWENT=`getent passwd "$USER"` || {
    echo "Error: invalid user $USER"
    exit 1
  }
  UID=`echo "$PWENT" | cut -f3 -d:`
  HOME=`echo "$PWENT" | cut -f6 -d:`

  if [ "$UID" -ge 500 ]; then
    echo "Error: user $USER is not a system user."
    exit 1
  fi

  # kill all remaining processes
  while ps h -u "$USER" >/dev/null; do 
    killall -9 -u "$USER" || true
    sleep 0.2;
  done

  rm -rf "$HOME"
  find /tmp -mindepth 1 -maxdepth 1 -uid "$UID" -print0 | xargs -0 rm -rf || true

  deluser --system "$USER"
}

case "$1" in
  add)
    add_account
    ;;
  remove)
    if [ -z $2 ] ; then
      echo "Usage: $0 remove [account]"
      exit 1
    fi
    remove_account $2
    ;;
  *)
    echo "Usage: $0 add|remove"
    exit 1
esac
