#!/bin/sh

set -eu

mode=${1:---manual}

puavo_hosttype=$(puavo-conf puavo.hosttype)

status=0

statedirlist=''
if [ "$puavo_hosttype" = 'bootserver' ]; then
  statedirlist='
    /state/etc/network/interfaces.d
    /state/etc/shorewall
  '
fi

done_first=false
for statedir in $statedirlist; do
  if ! $done_first; then done_first=true; else echo; fi
  puavo-sysmerge-onedir "$mode" "$statedir" || status=1
done

if [ "$status" -ne 0 ]; then
  echo 'There were errors!' >&2
fi

exit $status
