#!/bin/sh -eu

current_testing=forky

# Check that we are on a branch
if ! git diff --quiet HEAD; then
   echo >&2 "E: Working tree has uncommitted changes"
   exit 1
fi
status="$(git status -b --porcelain)"
if [ "${status%\?\? *}" != "$status" ]; then
    echo >&2 "E: Working tree has files that are untracked and not ignored"
    exit 1
fi
head="${status#\#\# }"
if [ "$head" = "HEAD (no branch)" ]; then
   echo >&2 "E: HEAD is not a branch"
   exit 1
fi
branch="${head%...*}"
real_branch="$branch"

dist="$(dpkg-parsechangelog -S Distribution)"
if [ "$dist" != UNRELEASED ]; then
   echo >&2 "E: Changelog distribution is already set to $dist"
   exit 1
fi

package="$(dpkg-parsechangelog -S Source)"
ver="$(dpkg-parsechangelog -S Version)"

# Default urgency set to medium
urgency='medium'

case "$branch" in
debian/latest)
    case "$ver" in
    *~exp*)
        dist=experimental
        ;;
    *)
        dist=unstable
        ;;
    esac
    ;;
debian/sid)
    echo >&2 "E: Use debian/unstable not debian/sid"
    exit 1
    ;;
debian/*/${current_testing} | debian/${current_testing})
    dist=unstable
    ;;
debian/*/*)
    dist=${branch#debian/*/}
    ;;
debian/*)
    dist=${branch#debian/}
    ;;
*)
    echo >&2 "E: Can't release from private or unsupported branch $real_branch"
    exit 1
    ;;
esac

case "$dist" in
*-security | *-security-embargoed)
    dist=${dist%-embargoed}
    # https://www.debian.org/doc/manuals/developers-reference/ch05.en.html#bug-security-building
    urgency='high'
    ;;
*-updates)
    dist=${dist%-updates}
    ;;
esac

dch --release --distribution "$dist" --urgency "$urgency" --no-force-save-on-release ''
git commit -m "Prepare to release $package ($ver)" debian/changelog

echo "Remember to tag after building and verifying the package"
