class image::bundle::opinsys {
  include crash_reporting,
	  desktop,
	  disable_accounts_service,
	  disable_geoclue,
	  disable_gnome_keyring_autostart,
	  firefox,
	  gnome_terminal,
	  graphics_drivers,
	  image::bundle::basic,
	  kaffeine,
	  keyutils,
	  libreoffice,
	  ltspimage_java::tools,
	  ltspimage_kdump,
	  ltspimage_opinsys_desktop,
	  ltspimage_plymouth_theme,
	  network_manager,
	  open-sankore,
	  puavo_openvpn,
	  puavo_wlan,
	  pycharm,
	  tuxpaint,
	  wacom,
	  xexit
}
