#!/bin/sh

set -eu

if [ "$(puavo-conf puavo.puavomenu.enabled)" = "true" ]; then
    exec /opt/puavomenu/launch
    exit 0
fi

webmenu_args=''

if [ "$(puavo-conf puavo.localadmin.enabled)" = 'true' ]; then
  PUAVO_PERSONALLY_ADMINISTERED=true
  WM_CONFIG_JSON_PATH=/etc/webmenu/personally-administered-device/config.json
  export PUAVO_PERSONALLY_ADMINISTERED WM_CONFIG_JSON_PATH
else
  : # Do not set PUAVO_PERSONALLY_ADMINISTERED at all (to 0 or false),
    # webmenu/menu.yaml only checks if variable is set and not at its value.
fi

if [ "$(puavo-conf puavo.webmenu.feedback.enabled)" = 'true' ]; then
  # XXX Enable back again once we resolve issues.
  : # export WM_FEEDBACK_ACTIVE=true
fi

if [ "$(puavo-conf puavo.webmenu.webkiosk)" = 'true' ]; then
  webmenu_args="${webmenu_args} --webkiosk"
fi

exec webmenu $webmenu_args "$@"
