#!/bin/sh

set -e

# do not start mimio stuff if we do not have a license
if ! [    -e "/var/opt/mimio/global/global.reg" \
       -a -e "/var/opt/mimio/global/shared.reg" ]; then
  exit 1
fi

# do not start mimio stuff if we do not have a mimio device connected
if ! lsusb | awk '$6 ~ /^08d3:0003/' | grep -q .; then
  exit 1
fi

# workaround a problem with NFS and fifos
rm -f ~/.mimio/msgbus-lock ~/.mimio/system.mimio.com

exec "/var/opt/mimio/mimio-mimiosys" "$@"
