class image::bundle::desktop {
  include acroread,
          crash_reporting,
          ::desktop,
          disable_accounts_service,
          disable_geoclue,
          firefox,
          fontconfig,
          gnome_terminal,
          graphics_drivers,
          image::bundle::basic,
          kaffeine,
          keyutils,
          ktouch,
          laptop_mode_tools,
          libreoffice,
          network_manager,
          pycharm,
          tuxpaint,
          wacom,
          workaround_firefox_local_swf_bug,
          xexit
}
