# Puavo module signing configuration with unique key for
# each clean build and not included in the final image.
mok_signing_key="/puavo-os/.module-signing-key.pem"
mok_certificate="/puavo-os/.module-signing-key.pem"

