#!/bin/sh

set -eu

run_cmd() {
  local user_id

  user_id=$(ps -C pipewire -o uid= \
              | awk '(951 <= $1 && $1 <= 999) || 10000 <= $1 { print $1 }' \
              | sort | uniq)
  if [ -z "$user_id" ]; then
    echo 'pipewire is not running' >&2
    exit 1
  fi

  if ! printf %s "$user_id" | grep -qE '^[0-9]+$'; then
    echo 'pipewire is running by multiple users' >&2
    exit 1
  fi

  sudo -n -u "#${user_id}" env "XDG_RUNTIME_DIR=/run/user/${user_id}" "$@"
}

usage() {
  local progname
  progname=$(basename "$0")
  cat <<EOF
Usage:
  ${progname} help
  ${progname} pw-dump ...
  ${progname} priorities
  ${progname} show-user-configuration
  ${progname} wpctl ...
EOF
}

case "${1:-}" in
  help)
    usage
    ;;
  pw-dump|wpctl)
    run_cmd "$@"
    ;;
  priorities)
    run_cmd pw-dump | jq -r '
      "CLASS\t\tID\tPRIORITY\tNAME",
      (
        [
          .[] | select(.info.props."media.class" | IN("Audio/Sink", "Audio/Source"))
        ]
        | sort_by(
            if .info.props."media.class" == "Audio/Sink" then 0 else 1 end,
            -(.info.props."priority.session" | tonumber)
          )
        | .[]
        | {
            id,
            class: .info.props."media.class",
            name: .info.props."node.name",
            priority_session: .info.props."priority.session",
          }
        | "\(.class)\t\(.id)\t\(.priority_session)\t\t\(.name)"
      )
      '
    ;;
  show-user-configuration)
    shift
    sudo -n /usr/lib/puavo-desktop/puavo-pipewire-show-user-configuration "$@"
    ;;
  *)
    usage
    exit 1
    ;;
esac
