#!/usr/bin/ruby

# Copyright (C) 2016 Opinsys Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#
# 1. image defaults
# 2. feature-profiles
# 3. hardware quirks database
# 4. settings from puavo
# 5. primary user preferences (currently unimplemented)
# 6. kernel arguments
#

#
# tested speed on Lenovo ThinkCentre Edge (1578D7G)
#   with 100 hardware-quirks.json files, with 1000 pci-id keys on each:
#   took about 0.8 seconds (not to be taken as an exact value, code may
#   have changed)
#
# ways to optimize:
#   - rewrite in C
#   - have only a few json-files to parse
#   - replace calls for dmidecode, lspci, lsusb with something more efficient
#

require 'json'
require 'puavo/conf'

$deviceinfo = {}
def get_device_setting(key)
    # returns nil in case there was a failure
    return $deviceinfo[key] if $deviceinfo.has_key?(key)

    case key
        when 'dmidecode-baseboard-asset-tag',
             'dmidecode-baseboard-manufacturer',
             'dmidecode-baseboard-product-name',
             'dmidecode-baseboard-serial-number',
             'dmidecode-baseboard-version',
             'dmidecode-bios-release-date',
             'dmidecode-bios-vendor',
             'dmidecode-bios-version',
             'dmidecode-chassis-asset-tag',
             'dmidecode-chassis-manufacturer',
             'dmidecode-chassis-serial-number',
             'dmidecode-chassis-type',
             'dmidecode-chassis-version',
             'dmidecode-processor-family',
             'dmidecode-processor-frequency',
             'dmidecode-processor-manufacturer',
             'dmidecode-processor-version',
             'dmidecode-system-manufacturer',
             'dmidecode-system-product-name',
             'dmidecode-system-serial-number',
             'dmidecode-system-uuid',
             'dmidecode-system-version'
                cmdarg = key[ "dmidecode-".length .. -1]
                result = %x(dmidecode -s #{ cmdarg })
                status = $?.exitstatus 
                if status != 0 then
                    warn("dmidecode -s #{ cmdarg } returned #{ status }")
                    $deviceinfo[key] = nil
                else
                    $deviceinfo[key] = [ result.strip ]
                end
        when 'pci-id'
            # might return nil, that is okay
            $deviceinfo[key] = take_field('lspci -n', 3)
        when 'usb-id'
            # might return nil, that is okay
            $deviceinfo[key] = take_field('lsusb', 6)
        else
            warn("Unknown device key #{ key }")
            $deviceinfo[key] = nil
    end

    return $deviceinfo[key]
end

def lookup_features_by_key(matchmethod, hwquirkset)
    hwquirkset.each do |quirktype, quirkmap|
        if !quirktype.kind_of?(String) then
            warn("input type error: quirktype is not a string")
            return
        end

        if !quirkmap.kind_of?(Hash) then
            warn("input type error: quirkmap is not a hash")
            return
        end

        case quirktype
            when ':exact:', ':glob:', ':logic:', ':regex:'
                lookup_features_by_key(quirktype, quirkmap)

            when /\Admidecode-.*\Z/, 'pci-id', 'usb-id'
                device_setting = get_device_setting(quirktype)
                device_setting.each do |id|
                    quirkmap.each do |pattern, featureconf|
                        if match_hwquirk(id, matchmethod, pattern) then
                            $features.merge!(featureconf)
                        end
                    end
                end
            else
                warn("Unknown quirktype: #{ quirktype }")
                return
        end
    end
end

def match_hwquirk(target, matchmethod, pattern)
    if !target.kind_of?(String) then
        warn("asked to match something that was not a string: " \
                + target.inspect)
        return false
    end

    case matchmethod
        when ':exact:'
            return target == pattern
        when ':glob:'
            return File.fnmatch(pattern, target)
        when ':logic:'
            warn(":logic: matcher not implemented yet")
            return false
        when ':regex:'
            return target.match(pattern) ? true : false
        else
            warn("Match method #{ matchmethod } is unsupported")
    end

    return false
end

def take_field(cmd, fieldnum)
    result = %x(#{ cmd })
    status = $?.exitstatus
    if status != 0 then
        warn("#{ cmd } returned #{ status }")
        return nil
    end

    result.split("\n").map { |line| (line.split(' '))[fieldnum-1] }
end

if Process.euid != 0 then
    warn("#{ File.basename($0) } must be run as root")
    exit 1
end

Hardware_quirks_globpattern = "/usr/share/puavo/hwquirks/*/*.json"
Image_defaults_globpattern  = "/usr/share/puavo/features/*/info.json"

$features = {}

# 1. image defaults

image_defaults_files = Dir.glob(Image_defaults_globpattern)
if image_defaults_files.count == 0 then
    warn('No image defaults files found')
end

image_defaults_files.each do |file|
    begin
        feature_info = JSON.parse( IO.read(file) )
        # XXX typecheck info
        feature_info['keys'].each do |key, keyinfo|
            # XXX typecheck info and info['default']
            $features[key] = keyinfo['default']
        end
    rescue StandardError => e
        warn("Could not read feature defaults from #{ file }: #{ e.message }")
    end
end

# 2. feature-profiles

# XXX

# 3. check settings based on hardware quirks (dmidecode, pci, usb, ...)

deviceinfo = {}

# List available dmidecode fields.  Comment out if uninteresting so we can
# save time with dmidecode-lookups (other alternative is to make those faster).
# (Should check these only on demand.)

Dir.glob(Hardware_quirks_globpattern).each do |hwquirk_file|
    hwquirklist = JSON.parse( IO.read(hwquirk_file) )
    hwquirklist.each do |hwquirkset|
        lookup_features_by_key(':exact:', hwquirkset)
    end
end

# 4. check settings from puavo

begin
    device_json = JSON.parse( IO.read('/etc/puavo/device.json') )
    device_features = device_json['features']
    # XXX typecheck device_features
    $features.merge!(device_features)
rescue StandardError => e
    warn("Could not read features from /etc/puavo/device.json: #{ e.message }")
end

# 5. check primary user preferences

# XXX

# 6. check kernel arguments

# XXX should blow up if /proc/cmdline can not be read?
cmdline_path = '/proc/cmdline'
IO.read(cmdline_path).split.each do |kernel_arg|
    match = kernel_arg.match(/\Apuavo\.feature\.(.*?)=(.*)\Z/)
    if match then
        key   = match[1]
        value = match[2]
        $features[key] = value
    end
end

#
# make db
#

# XXX value could be be of type { '+': [ ... ], '-': [ ... ]},
# XXX ... could be Arrays, we could them serialize
# XXX those into the database with [].join(',').
# XXX this should have been handled previously

puts "Creating puavo-conf database with the following values:\n"
puavoconf = Puavo::Conf.new()
$features.sort.each do |key, value|
    puavoconf.set(key, value)
    puts "    #{ key }=#{ value }"
end
puavoconf.close
