#!/usr/bin/ruby

# Copyright (C) 2016 Opinsys Oy

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'dbus'

require 'puavo/conf'

class Conf1 < DBus::Object

  def initialize(object_path, puavoconf)
    super(object_path)
    @puavoconf = puavoconf
  end

  dbus_interface "org.puavo.Conf1" do

    dbus_method :Add, 'in key:s, in value:s' do |key, value|
      @puavoconf.add(key, value)
    end

    dbus_method :Clear, '' do
      @puavoconf.clear()
    end

    dbus_method :Get, 'in key:s, out s' do |key|
      @puavoconf.get(key)
    end

    dbus_method :GetAll, 'out t, out as, out as' do
      keys, values = @puavoconf.get_all()
      [keys.length, keys, values]
    end

    dbus_method :HasKey, 'in key:s, out b' do |key|
      @puavoconf.has_key?(key)
    end

    dbus_method :Overwrite, 'in key:s, in value:s' do |key, value|
      @puavoconf.overwrite(key, value)
    end

    dbus_method :Set, 'in key:s, in value:s' do |key, value|
      @puavoconf.set(key, value)
    end

  end

end

bus = DBus::SystemBus.instance

service = bus.request_service("org.puavo.Conf1")
puavoconf = Puavo::Conf.new
service.export(Conf1.new('/org/puavo/Conf1', puavoconf))

loop = DBus::Main.new
loop << bus

begin
  loop.run
ensure
  puavoconf.close
end
