#!/bin/sh

PREREQ=""

prereqs()
{
        echo "${PREREQ}"
}

case ${1} in
        prereqs)
                prereqs
                exit 0
                ;;
esac

for x in $(cat /proc/cmdline); do
  case "$x" in
    puavo.abitti.mount_kernel_modules=true)
      mkdir -p /image /root/lib/modules
      mount -r -o loop /root/lib/live/mount/medium/ltsp.img /image
      mount --bind /image/lib/modules /root/lib/modules
      ;;
  esac
done
