#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

mkdir -p /var/local/lib/puavo-conf
puavo-conf-mkdb --sources defaults,profiles,hwquirks,kernelargs
