#!/bin/sh

set -eu

rootdir=$1
srcdir=$(dirname $0)

. $srcdir/common.sh

boot_scripts="
  $server_scripts
  boot/network_interfaces
  boot/dhcpd_configuration
  boot/nfs_server
"

setup $rootdir $srcdir $boot_scripts
