#!/bin/sh

set -eu

rootdir=$1
srcdir=$(dirname $0)

. $srcdir/common.sh

ltsp_scripts="
  $server_scripts
  ltsp/network_interfaces
  ltsp/client
  ltsp/ssh_config
"

setup $rootdir $srcdir $ltsp_scripts
