#!/bin/sh

set -u

puavo_rest_request() {
    urlpath=$1

    puavo_rest_server=$(puavo-resolve-api-server) || return
    curl --cacert /etc/puavo/certs/rootca.pem \
        --config - \
        --fail \
        --max-time 60 \
        --silent \
        "${puavo_rest_server}/${urlpath}" <<EOF
user=$(cat /etc/puavo/ldap/dn):$(cat /etc/puavo/ldap/password)
EOF
}

puavo_rest_request_and_replace() {
    urlpath=$1
    filepath=$2

    tmp_filepath="${filepath}.tmp"
    install -o root -g root -m 600 /dev/null "$tmp_filepath" || return

    puavo_rest_request "$urlpath" > "$tmp_filepath" || return
    replace_if_changed "$filepath"  "$tmp_filepath"
}

replace_if_changed() {
    dest=$1
    src=$2

    if cmp "$src" "$dest" >/dev/null 2>&1; then
        rm -f "$src"
    else
        mv "$src" "$dest"
    fi
}

update_device_json() {
    puavo_rest_request_and_replace "v3/devices/$(cat /etc/puavo/hostname)" \
        /state/etc/puavo/device.json || return
    chmod 644 /state/etc/puavo/device.json
}

update_external_files() {
    puavo-sync-external-files || return
    puavo-handle-external-files-actions
}

update_ltsconf() {
    install -o root -g root -m 600 /dev/null /state/etc/lts.conf.tmp || return
    puavo-lts > /state/etc/lts.conf.tmp                              || return
    replace_if_changed /state/etc/lts.conf /state/etc/lts.conf.tmp
}

update_wlan_configurations() {
    wlan_networks_uri="v3/devices/$(cat /etc/puavo/hostname)/wlan_networks"
    puavo_rest_request_and_replace "$wlan_networks_uri" \
        /state/etc/puavo/wlan.json
}

update_grub_environment() {
  kernel_version=$(  jq -r .kernel_version   /state/etc/puavo/device.json)
  kernel_arguments=$(jq -r .kernel_arguments /state/etc/puavo/device.json)
  personally_administered=$(jq -r .personally_administered \
				  /state/etc/puavo/device.json)

  if [ -n "$kernel_version" -a "$kernel_version" != "null" ]; then
    grub-editenv /images/boot/grub/grubenv set \
                 "puavo_kernel_version=$kernel_version"
  else
    grub-editenv /images/boot/grub/grubenv unset puavo_kernel_version
  fi

  if [ "$personally_administered" = "true" ]; then
    grub-editenv /images/boot/grub/grubenv set "puavo_show_imageoverlays=true"
  else
    grub-editenv /images/boot/grub/grubenv unset puavo_show_imageoverlays
  fi

  if [ -n "$kernel_arguments" -a "$kernel_arguments" != "null" ]; then
    grub-editenv /images/boot/grub/grubenv set \
		 "puavo_kernel_arguments=$kernel_arguments"
  else
    grub-editenv /images/boot/grub/grubenv unset puavo_kernel_arguments
  fi
}

# Update several (different) things.  Even if one thing cannot be updated,
# try to update others (order does not matter here, but do this sequentially
# anyway).

update_ltsconf             || true
update_device_json         || true
update_external_files      || true
update_wlan_configurations || true
update_grub_environment    || true
