anki/*.py			usr/share/anki/anki
anki/importing/*.py		usr/share/anki/anki/importing
anki/template/*.py		usr/share/anki/anki/template
aqt/*.py			usr/share/anki/aqt
aqt/forms/*.py			usr/share/anki/aqt/forms
web/*				usr/share/anki/web
debian/browsersel.js		usr/share/anki/web

locale/*/			usr/share/locale
anki.xpm			usr/share/pixmaps
anki.png			usr/share/pixmaps
debian/anki.svg			usr/share/icons/hicolor/scalable/apps
anki.desktop			usr/share/applications
