#!/bin/sh

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    # get pre-requisites
    prereqs)
        prereqs
        exit 0
        ;;
esac

if [ "$BOOT" != "puavo" ]; then
  exit 0
fi

mkdir -p /run/puavo

exec > /run/puavo/initrd.log 2>&1

puavo-conf-update --init --verbose

# apply kernel module configurations based on puavo-conf here

puavo_nvidia_driver=

case "$(puavo-conf puavo.graphics.driver)" in
  nvidia)
    puavo_nvidia_driver=current
    ;;
  nvidia-304)
    puavo_nvidia_driver=legacy-304xx
    ;;
  nvidia-340)
    puavo_nvidia_driver=legacy-340xx
    ;;
  nvidia-375)
    puavo_nvidia_driver=legacy-375xx
    ;;
esac

if [ -n "$puavo_nvidia_driver" ]; then
  puavo_nvidia_dir="/etc/nvidia/${puavo_nvidia_driver}"

  if [ -e "${puavo_nvidia_dir}/nvidia-blacklists-nouveau.conf" ]; then
    echo "copying ${puavo_nvidia_dir}/nvidia-blacklists-nouveau.conf to" \
         "/etc/modprobe.d/nvidia-blacklists-nouveau.conf"
    cp "${puavo_nvidia_dir}/nvidia-blacklists-nouveau.conf" \
       /etc/modprobe.d/nvidia-blacklists-nouveau.conf
  elif [ -e /etc/nvidia/nvidia-blacklists-nouveau.conf ]; then
    echo "copying /etc/nvidia/nvidia-blacklists-nouveau.conf to" \
         "/etc/modprobe.d/nvidia-blacklists-nouveau.conf"
    cp /etc/nvidia/nvidia-blacklists-nouveau.conf \
       /etc/modprobe.d/nvidia-blacklists-nouveau.conf
  else
    echo 'ERROR: should blacklist nouveau,' \
         "but ${puavo_nvidia_dir}/nvidia-blacklists-nouveau.conf is missing"
  fi

  if [ -e "${puavo_nvidia_dir}/nvidia-modprobe.conf" ]; then
    echo "copying ${puavo_nvidia_dir}/nvidia-modprobe.conf to" \
         "/etc/modprobe.d/nvidia.conf"
    cp "${puavo_nvidia_dir}/nvidia-modprobe.conf" \
       /etc/modprobe.d/nvidia.conf
  elif [ -e "/etc/nvidia/nvidia-modprobe.conf" ]; then
    echo "copying /etc/nvidia/nvidia-modprobe.conf to" \
         "/etc/modprobe.d/nvidia.conf"
    cp /etc/nvidia/nvidia-modprobe.conf /etc/modprobe.d/nvidia.conf
  else
    echo 'ERROR: should use nvidia,' \
         "but ${puavo_nvidia_dir}/nvidia-modprobe.conf is missing"
  fi
else
  echo "removing /etc/modprobe.d/nvidia-blacklists-nouveau.conf and" \
       "/etc/modprobe.d/nvidia.conf if they exist"
  rm -fv /etc/modprobe.d/nvidia-blacklists-nouveau.conf \
         /etc/modprobe.d/nvidia.conf
fi
