#!/bin/sh

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    # get pre-requisites
    prereqs)
        prereqs
        exit 0
        ;;
esac

if [ "$BOOT" = "puavo" ]; then
    puavo-conf-update --init --verbose
fi

# apply kernel module configurations based on puavo-conf here

puavo_blacklist_nouveau=false
puavo_nvidia_modprobe_file=

case "$(puavo-conf puavo.graphics.driver)" in
  nvidia)
    puavo_blacklist_nouveau=true
    puavo_nvidia_modprobe_file=nvidia-modprobe.conf
    ;;
  nvidia-304)
    puavo_blacklist_nouveau=true
    puavo_nvidia_modprobe_file=nvidia-legacy-304xx-modprobe.conf
    ;;
  nvidia-340)
    puavo_blacklist_nouveau=true
    puavo_nvidia_modprobe_file=nvidia-legacy-340xx-modprobe.conf
    ;;
  nvidia-367)
    puavo_blacklist_nouveau=true
    puavo_nvidia_modprobe_file=nvidia-legacy-367xx-modprobe.conf
    ;;
esac

{
  if $puavo_blacklist_nouveau; then
    if [ -e /etc/nvidia/nvidia-blacklists-nouveau.conf ]; then
      cp -v /etc/nvidia/nvidia-blacklists-nouveau.conf \
	    /etc/modprobe.d/nvidia-blacklists-nouveau.conf
    else
      echo 'ERROR: should blacklist nouveau,' \
	   'but /etc/nvidia/nvidia-blacklists-nouveau.conf is missing'
    fi
  else
    rm -fv /etc/modprobe.d/nvidia-blacklists-nouveau.conf
  fi

  if [ -n "$puavo_nvidia_modprobe_file" ]; then
    if [ -e "/etc/nvidia/${puavo_nvidia_modprobe_file}" ]; then
      cp -v "/etc/nvidia/${puavo_nvidia_modprobe_file}" \
	    /etc/modprobe.d/nvidia.conf
    elif [ -e "/etc/nvidia/nvidia-modprobe.conf" ]; then
      cp -v /etc/nvidia/nvidia-modprobe.conf /etc/modprobe.d/nvidia.conf
    else
      echo 'ERROR: should use nvidia,' \
	   "but /etc/nvidia/${puavo_nvidia_modprobe_file} is missing"
    fi
  else
    rm -fv /etc/modprobe.d/nvidia.conf
  fi
} >> /run/puavo-initrd.log
