#!/bin/sh

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    # get pre-requisites
    prereqs)
        prereqs
        exit 0
        ;;
esac

if [ "$BOOT" = "puavo" ]; then
    mkdir -p /var/lib/puavo-conf
    puavo-conf-mkdb
    puavo-conf-update
fi

# apply kernel module configurations based on puavo-conf here
